### ISSUE TITLE
AMP status toggle appears in Redirect Rule post in Safe Redirect Manager

### ISSUE THREAD

**Issue by westonruter** [ampproject/amp-wp#1011]
This may be a bug with the Safe Redirect Manager, but the AMP status toggle should not appear when editing a redirect rule:

![image](https://user-images.githubusercontent.com/134745/37230670-2e6736d4-239d-11e8-8f99-52d404fdc0c3.png)

**Comment by rickalee** [comment]
Submitted pull request https://github.com/Automattic/amp-wp/pull/1043 to fix this issue.

Updated boolean for adding AMP Status toggle to post_type_supports() instead of is_post_type_viewable() since Safe Redirect Manager sets public_queryable to true in post type registration.

**Comment by westonruter** [comment]
This is still relevant.

**Comment by pierlon** [comment]
Closing this issue as the AMP status toggle is no longer being rendered. The reason for why it was being previously rendered is because we are now verifying that a post type [is eligible for AMP](https://github.com/ampproject/amp-wp/blob/0f7a3a93e33d30fe3810e0850d892fa8d35acf1f/includes/admin/class-amp-post-meta-box.php#L305), where previously we were only checking if a post type [is viewable](https://github.com/ampproject/amp-wp/blob/bdb0ec8f081faa36182279b7130aac1162d343eb/includes/admin/class-amp-post-meta-box.php#L137).
