### ISSUE TITLE
Implement amp-next-page as optional toggle

### ISSUE THREAD

**Issue by ericlindley-g** [ampproject/amp-wp#1255]
[amp-next-page](https://www.ampproject.org/docs/reference/components/amp-next-page) makes easy to support infinite-scroll capabilities for AMP documents.

This feature request is to implement amp-next-page as an optional toggle in the AMP WP plugin. Users could just check a box and their documents would get an infinite scroll treatment.

Note that currently amp-next-page requires static markup with 3 related URLs. In the future it will support a server call to get URLs (potentially personalized per user) at runtime. Based on the way WP & the plugin work, I'm not sure if it makes sense to wait until this additional functionality is possible before starting implementation.

/cc @westonruter @amedina @aghassemi

**Comment by westonruter** [comment]
The adjacent-post navigation (e.g. the post previously published) would be what the plugin provides for WordPress core out of the box, since WordPress doesn't have related post suggestions as a core feature. Plugins, however, which do provide related posts functionality (like Jetpack) could hook into this amp-next-page functionality to provide a more relevant suggestion.  /cc @gravityrail

**Comment by westonruter** [comment]
This will make the most sense as implemented in Jetpack to use `amp-next-page` in the implementation of Infinite Scroll module.
