### ISSUE TITLE
Unexpected validation Handling of `<details>` tag 

### ISSUE THREAD

**Issue by amedina** [ampproject/amp-wp#1493]
The `<details>` HTML tag is not allowed by AMP's specification yet. It will likely be added soon but its current status allows us to see an seemingly unexpected behavior in validation handling. This tag is used as follows:

```html
<details>
  <summary>Copyright 1999-2018.</summary>
   <p>- by Awesome Author. All Rights Reserved.</p>
   <p>All content and graphics on this web site are the property of the author.</p>
</details>
```
Which results in the following view in the non-AMP version:

<img width="738" alt="screen shot 2018-10-07 at 1 15 09 pm" src="https://user-images.githubusercontent.com/506089/46586510-72ec5080-ca34-11e8-83dd-17e51ffb9eaf.png">

On the AMP side the following takes place:

* The plugin correctly flags the HTML error and points out to the `<details>` tag as the offending markup.
<img width="1353" alt="screen shot 2018-10-07 at 1 15 36 pm" src="https://user-images.githubusercontent.com/506089/46586526-9fa06800-ca34-11e8-8177-f2e1dacf0f48.png">
<img width="1204" alt="screen shot 2018-10-07 at 1 15 45 pm" src="https://user-images.githubusercontent.com/506089/46586532-aaf39380-ca34-11e8-95ad-465c792cf8de.png">

* Upon accepting the error, the plugin is effectively instructed to remove the details tag
* Upon updating the post, the plugin removes the `details` tag and flags a new error associated with the `<summary>` tag

<img width="1344" alt="screen shot 2018-10-07 at 1 16 24 pm" src="https://user-images.githubusercontent.com/506089/46586541-c78fcb80-ca34-11e8-92b4-f1f4183b19ec.png">
<img width="1274" alt="screen shot 2018-10-07 at 1 16 34 pm" src="https://user-images.githubusercontent.com/506089/46586543-ceb6d980-ca34-11e8-8195-78c5fd294385.png">

**Expected behavior**:
* Since the `summary` tag is a child of the  Details tag, the expected behavior is that removing the details tag should also remove the summary tag and therefore no error should be flagged for the latter once the former has been accepted

**Comment by westonruter** [comment]
At first look, it feels similar to what was fixed in #1461. At the very least the behavior is similar, where accepting one validation error causes another one to take its place. It could be a different underlying cause however.

**Comment by amedina** [comment]
Why is it that a nested element is not sanitized when the parent is?

**Comment by westonruter** [comment]
That is the question. I'm guessing it has something to do with the code around here:

https://github.com/Automattic/amp-wp/blob/a3983a0758dc5357592f6461c56e5345b78cacb3/includes/sanitizers/class-amp-tag-and-attribute-sanitizer.php#L1817-L1823

This is where that `replace_node_with_children` method is surely being called when the sanitizer encounters the `details` element:

https://github.com/Automattic/amp-wp/blob/a3983a0758dc5357592f6461c56e5345b78cacb3/includes/sanitizers/class-amp-tag-and-attribute-sanitizer.php#L367-L371

**Comment by amedina** [comment]
Makes sense;

**Comment by kienstra** [comment]
**Question About Moving To v1.0 Project**

Hi @westonruter and @alcurrie,
What do you think about adding this to the [v1.0 project](https://github.com/Automattic/amp-wp/projects/6), to be part of the `1.0` release? 

It'd be good to have this in `1.0`. And it's not a new feature, so I think it would be fair to add it in another `RC`, like `RC2`.

**Comment by alcurrie** [comment]
@kienstra  - Adding this fix, to the [v1.0 project](https://github.com/Automattic/amp-wp/projects/6) makes sense to me. It is arguably in the grey area between feature improvement and bug fix, but since this is intended make the core functionality of work more completely/correctly it makes sense to me add it to another 'RC' for the '1.0', but as I'm new to the project interested in @westonruter opinion.

**Comment by westonruter** [comment]
It's not a blocker for 1.0. We can have it come in 1.1.

**Comment by westonruter** [comment]
# Testing instructions

1. Create a Custom HTML block and supply it with: `<outer-bad><inner-bad>🙈</inner-bad></outer-bad>`  
2. Hit Save Draft and you should see:
![image](https://user-images.githubusercontent.com/134745/64979506-ba967180-d86c-11e9-84de-c4b6a4182579.png)
3. Click the “Review Issues” link.
4. Reject the `outer-bad` and accept the `inner-bad` and Update. The Details column should always have the parent of `inner-bad` shown as `outer-bad`, and the parent of `outer-bad` should always be `div` (or whatever the theme has). This should not change based on the status of the individual validation errors, whereas before the fix the parent of the `inner-bad` could be incorrectly `div`: ![image](https://user-images.githubusercontent.com/134745/64979837-66d85800-d86d-11e9-89a6-f76723d9be84.png)

Aside: I just noticed that before #3243, the above testing steps causes PHP warning/notice:

> PHP Warning:  Couldn't fetch DOMElement. Node no longer exists in /app/public/content/plugins/amp/includes/sanitizers/class-amp-tag-and-attribute-sanitizer.php on line 276
> PHP Notice:  Undefined property: DOMElement::$parentNode in /app/public/content/plugins/amp/includes/sanitizers/class-amp-tag-and-attribute-sanitizer.php on line 276

This doesn't happen when the fix is applied.

**Comment by kienstra** [comment]
**Testing Looks Good**

Hi @westonruter,
Using your [testing instructions](https://github.com/ampproject/amp-wp/issues/1493#issuecomment-531879060), this behaves as expected.

In step 4, the parent of the `inner-bad` is `outer-bad`, not `div`:
