### ISSUE TITLE
Implement unique constraint in whitelist sanitizer

### ISSUE THREAD

**Issue by csossi** [ampproject/amp-wp#1580]
Went to https://native-ampconfdemo.pantheonsite.io/

Got the attached amp validation errors:
![image](https://user-images.githubusercontent.com/16945664/47875757-bf396f00-dded-11e8-91f7-5349f9721701.png)

**Comment by kienstra** [comment]
**Thanks, Will Work On This**

Hi @csossi,
Thanks for opening this. I'm moving this into 'To Do' in the `1.0` project, and I'll work on it.

**Comment by kienstra** [comment]
**amp-geo error**

Hi @westonruter,
@csossi correctly [pointed out](https://github.com/Automattic/amp-wp/issues/1580#issue-376543765) that there's a validation error from there being 2 `<amp-geo>` elements.

That's because I added 2 of them to [this post](https://native-ampconfdemo.pantheonsite.io/wp-admin/post.php?post=512&action=edit) via Custom HTML elements, for testing:

<img width="1184" alt="amp-geo-test-2" src="https://user-images.githubusercontent.com/4063887/47945684-3859c480-dec9-11e8-97e9-8d30cc31ba85.png">

Maybe eventually there could be a way for a sanitizer to remove the extra `<amp-geo>` elements and raise a validation error. But is it OK to leave this as is for the `1.0` release?

Thanks!

**Comment by westonruter** [comment]
In this way, it is a similar issue to #1507.

**Comment by alcurrie** [comment]
Good catch @csossi  -  @westonruter @kienstra Based on the discussion above, I'm moving this issue in for review in V1.1. Let me know if there is anything discussed here that you think we should resolve in V 1.0

**Comment by kienstra** [comment]
H @alcurrie,
Thanks, good idea to move it into the [v1.1 project](https://github.com/Automattic/amp-wp/projects/7).

**Comment by westonruter** [comment]
Support forum topic where more than one meta viewport in the `head` is causing a validation error: https://wordpress.org/support/topic/the-tag-meta-nameviewport-appears-more-than-once-in-the-document-3/

Another topic for meta charset appearing more than once: https://wordpress.org/support/topic/amp-error-for-google-webmaster-tools/

**Comment by westonruter** [comment]
I think an efficient approach could be:

1. Upon encountering an element with a [`unique` constraint](https://github.com/ampproject/amphtml/blob/f7d6f31ceeb1b937a68172f2e0dd9d71e5dc3d7d/validator/validator-main.protoascii#L423).
2. Serialize the tag spec and and use it as the key for a new `encountered_uniques` array, with a value of `1`.
3. The next time another element is encountered with a `unique` constraint and its tag spec already exists in the `encountered_uniques` array, then it should be reported as an AMP validation error (and removed).
