### ISSUE TITLE
release date

### ISSUE THREAD

**Issue by ineagu** [ampproject/amp-wp#1633]
I am waiting for v1 for a long time :), we added out of the box compatibility with v1 AMP plugin on our latest theme : 
https://wordpress.org/themes/download/neve.1.0.9.zip?nostats=1 and would love to have at least some idea about when v1 is out.

We are already using the RC version on production at themeisle.com/blog/ and is doing well!

**Comment by westonruter** [comment]
Yeah, sorry about that. We've been having to make continual updates to the release candidates as development of WordPress 5.0 is causing changes to the Gutenberg APIs. There will be a new RC published today. We're essentially tracking WordPress 5.0 as the release date for AMP 1.0 as well.

**Comment by ineagu** [comment]
good to know, thanks!

**Comment by fthead9** [comment]
I just saw today that WP 5.0 won’t be released on the 27th. Does that mean AMP 1.0 is also getting pushed back? 

Now that we’ve integrated your plugin instead of using our framework we’re stuck waiting to release our AMP WooCommerce plugin. Would really like to see AMP 1.0 out before EOM so we can finally launch. Please provide a release date update so we can plan accordingly. 
Thanks,
Toren

**Comment by amedina** [comment]
Currently we are targeting December 4th as the release date. Unless something unforeseen happens, that will be the release date.

**Comment by ineagu** [comment]
Let's hope for the best :D

**Comment by fthead9** [comment]
Is the release still on track for this week? 

Toren

**Comment by westonruter** [comment]
Yes

**Comment by westonruter** [comment]
Update: Release is now scheduled for tomorrow. (Since nothing else is happening that day 😉.)
