### ISSUE TITLE
AMP stories Interface fixes and enhancements for the Demo

### ISSUE THREAD

**Issue by alcurrie** [ampproject/amp-wp#1673]
- [x] _AC-1_ - Because the display of the arrows is limited to the hover state, and changing it to be persistent on hover is blocked by Gutenberg, implement a solution using to 'show' the arrows in selected state and then the hide the CSS on hover when the can see and take action to move the page, block, or layer up or down. 
- [x] _AC-2_ - Remove/hide the add layer interface from showing over the AMP story interface (user can add layers from the new 'add Layer' link above the block navigation
![removeaddlayerfromoverinterface](https://user-images.githubusercontent.com/18579988/49250799-d1f39380-f3ed-11e8-9b80-73bd8a8a4b56.png)
- [x] _AC-3_ - Make the block navigation _stay put_ and not move up and down with respect to the presence of the add layer button

**Comment by mehigh** [comment]
Fixed. Merged just now, so it should hit staging in a little while.

add layer inserter inside of the page is hidden when block navigation is visible: http://cloud.urldocs.com/5a99e782f703

block navigation doesn’t move up & down depending on the presence of the Add Layer button - http://cloud.urldocs.com/fbfad1b54f70

arrow display when the element is selected rather than just when hovering them - video demo:
http://cloud.urldocs.com/8b4dd430f0ae

**Comment by alcurrie** [comment]
@mehigh  - I confirmed issues for AC-1 display of Arrows, AC-2- Remove/hide the add layer interface from showing over the AMP story interface (user can add layers from the new 'add Layer' link above the block navigation)  AC-3 block navigation doesn’t move up & down depending on the presence of the Add Layer button.

Re. AC-2  the user can still add a new block (ie. paragraph) within the layer, and add a new layer when the page is selected, but the Add layer is  now moved  to the Block navigation interface.
