### ISSUE TITLE
AMP Stories - Minor recommended interface improvements/fixes

### ISSUE THREAD

**Issue by alcurrie** [ampproject/amp-wp#1686]
Based on QA review here are some outstanding minor recommended  interface improvements/fixes to make the AMP Stories interface easier for users:
- [ ] ~_1._ In the block navigation Page should be labelled Story Page in the block navigation
https://cl.ly/931b7c82df96~   - _Per @miina 's note below (https://github.com/Automattic/amp-wp/issues/1686#issuecomment-443753533), this is part of the requested relabelling to remove 'AMP Story' and would affect the demo - Recommend re-looking at it post AMP stories 1.5_
- [ ]  ~_2._ The ghosted story page should always be visible below the active story, on default view
 https://cl.ly/9d795d2e7272~ _Per @miina 's note below (https://github.com/Automattic/amp-wp/issues/1686#issuecomment-443753533), this is currently blocked by Gutenberg. Also this is a minor issue as the Ghosted page does appear on scroll and when pages/layers/blocks are selected_
- [ ]  _3._ Move the icon in the ghosted AMP story up from the middle of the Ghosted page to the top third, to make the icon more visible without scrolling down
https://cl.ly/3cdb181371ed
 - [ ] _4._ @jwold - flagged an issue where there is a strange issue that if you click 'Delete' on your keyboard the layer is deleted but there is a 'paragraph' tag added without any Parent layer: https://v.usetapes.com/Ffua2WTf7f

Related to: #1532

**Comment by miina** [comment]
Thank you for QA-ing the tickets, @alcurrie.

1: For doing that we would need to rename the block name -- then it would appear as "Story Page" everywhere. Initially it was "AMP Story Page" but that was [specifically requested](https://github.com/Automattic/amp-wp/issues/1525) to be removed from all the blocks and then it was left just with "Page". I'm fine either way but this is probably something that would be good to confirm since the names of the blocks was something under discussion previously.
2: Unfortunately that doesn't seem to be possible at this moment -- the ghosted page is basically restyled from the default Inserter (the Plus icon) -- that's something that is displayed according to the default behavior of Gutenberg and not actually added by us at all. Mike restyled it but didn't add it himself. One option would be to rework the current solution entirely and instead make the ghosted page part of the Page block -- this way we would have more control over it but not sure if that would be the best option and also not sure if it would make sense in terms of time at this moment.

**Comment by miina** [comment]
@alcurrie As talked this ticket can be removed to backlog for future iteration.

**Comment by alcurrie** [comment]
Thanks @miina  - I've moved this to the backlog to be looked at for a future iteration for AMP stories.

**Comment by westonruter** [comment]
I believe this is obsolete now.
