### ISSUE TITLE
Problem: "URL validation failed to due to the absence of the expected JSON-containing AMP_VALIDATION comment after the body"

### ISSUE THREAD

**Issue by vitorfernandes1976** [ampproject/amp-wp#1733]
Hello.

I have a problem.
Without understanding the reason, when validating pages / articles this error message appears:

"URL validation failed to due to the absence of the expected JSON-containing AMP_VALIDATION comment after the body."

What is the reason ?
What is the best solution?

Thank you

Vitor Fernandes

**Comment by westonruter** [comment]
Are there any errors in your PHP error log?

What plugins do you have active?

**Comment by vitorfernandes1976** [comment]
Hi westonruter; very thanks.

I have few plugins. All paid and legal.
I can not find any errors in the PHP log.
It's very weird; because it worked well, and without anything done it began to present that problem.

![print_rr_error](https://user-images.githubusercontent.com/45834146/49904130-245a9880-fe61-11e8-82ac-716740848661.png)

very thks
VF

**Comment by westonruter** [comment]
I assume that this only is a problem when you have switched to the native mode. If you go back to classic then you don't have a problem, correct?

Try going to a URL on your site and while you are logged in add `?amp_validate` to the end of the URL. Does anything get rendered?

The other suggestion I have is to try deactivating plugins one by one and for each deactivated plugin, re-check to see if the problem has gone away. That will narrow down if there is a plugin compatibility.

Also, enable `WP_DEBUG` on your site to ensure error messages are shown.

**Comment by vitorfernandes1976** [comment]
Hi;

see please (all ok):  [https://radioregional.pt/franca-atentado-causa-4-mortos-e-varios-feridos-graves/?amp_validate](https://radioregional.pt/franca-atentado-causa-4-mortos-e-varios-feridos-graves/?amp_validate)

**Comment by westonruter** [comment]
That URL does not work for me because I am not logged-in as an admin. The `amp_validate` URL only works if you are logged-in.

But I'm not seeing that https://radioregional.pt/franca-atentado-causa-4-mortos-e-varios-feridos-graves/ is an AMP document. Even though you have Native mode selected, it is not an AMP page, as you can see from https://validator.ampproject.org/#url=https%3A%2F%2Fradioregional.pt%2Ffranca-atentado-causa-4-mortos-e-varios-feridos-graves%2F

You may have another plugin that is conflicting with AMP. Since you haven't shared the list of plugins you have active, you'll have to deactivate them one by one untul you see `amp` appear in the root `html` element.

**Comment by vitorfernandes1976** [comment]
Thanks 

I deactivated all plugins (except AMP) and continue the same errors.

I activated WP_DEBUG

In Classic mode works well yes.

I'll give you access admin:


181/5000
Hello.

I deactivated all plugins (except AMP) and continue the same errors.

I activated WP_DEBUG

In Classic works well yes.

I'll give you access admin:

https://radioregional.pt/wp-admin/
user: westonruter
pass: westonruter123456789

I was very happy if I could solve this "mystery"

Very very thanks

**Comment by westonruter** [comment]
@vitorfernandes1976 Please don't share passwords on GitHub. I've changed the password but someone could have defaced your site.

**Comment by westonruter** [comment]
There was in fact a PHP error. Look at the bottom of the page:

> Uncaught Error: Call to undefined function Sabberworm\CSS\iconv() in wp-content/plugins/amp/vendor/sabberworm/php-css-parser/lib/Sabberworm/CSS/Parser.php:294

You need to install the iconv extension to PHP. This error will be caught with a better error message in v1.0.1 via #1727.

You may need to contact your server administrator to do this for you. Documentation: http://php.net/manual/en/iconv.installation.php

**Comment by vitorfernandes1976** [comment]
Thanks a lot

I installed ICONV for Apache 2.4, PHP 5.5, PHP 5.6 and PHP 7.0 on my VPS
server (WHM and Cpanel)

Worked !!!!

THANK YOU VERY MUCH.

Vitor Fernandes

Weston Ruter <notifications@github.com> escreveu no dia quarta, 12/12/2018
à(s) 23:34:

**Comment by quickelink** [comment]
I have used AMP plugin but there is a validation Problem , How can i Use AMP in wordpress using my own theme, my Blog <a href='https://quickelink.com/health-and-wellness/keto-for-weight-loss-benefits-of-keto-diet-and-best-keto-diet-plan-to-lose-weight-quickly/">Website (check it please and suggest me)</a> is showing error : AMP validity for your site. URL validation failed to due to unexpected JSON in the AMP_VALIDATION HTML comment

**Comment by westonruter** [comment]
@quickelink The probably fix for this was implemented in #3898, which will be part of the next release (v1.5) at the end of the month. In the meantime, please try this pre-release build: [amp.zip](https://github.com/ampproject/amp-wp/files/4309710/amp.zip) (v1.5.0-alpha-20200309T185726Z-4ba19bfd9)
