### ISSUE TITLE
Option to remove “Powered by WordPress” from footer

### ISSUE THREAD

**Issue by nabtron** [ampproject/amp-wp#1749]
Kindly add option to disabled this text, so that the plugin complies with WordPress guidelines. 

Some reasons:

1. This is a plugin, not a theme.
2. This is not a "default" theme or "default" plugin. Thus logic that something default has it does not apply to it.
3. An option can easily be given in settings to show or hide it, like the WordPress policy says.
4. Not everyone in the world who uses WordPress is a coder and can't override the footer.php file.

I hope it helps in giving people an option to remove a cross site backlink from a non-default WordPress plugin generated code, without giving them any flexibility to hide it, let alone asking them first before showing it. 

Thanks.

**Comment by westonruter** [comment]
@tanjoymor I believe the footer was put there in the first place because the plugin was first developed for WordPress.com, which as you know [requires such a footer](https://en.support.wordpress.com/footer-credits/). 

On WordPress.com business plan, the platform could provide this option to disable the footer by filtering `amp_post_template_file` to override with a custom `footer.php` that lacks the footer. Otherwise, site owners can install this little plugin to remove the footer as well, without any coding required:

https://gist.github.com/westonruter/7aa079125a656fd96554d6d9123d53a4

I'm wary of providing any _option_ to disable the footer credits. Either the template should have the credits or it should be removed entirely. [Decisions not options](https://wordpress.org/about/philosophy/#decisions), and all. Since the AMP plugin isn't part of WordPress.com, I'm inclined to just removed it entirely, and on WordPress.com a mu-plugin can be added which re-adds the footer credits as required according to the policies there.

In the end, the footer credits only applies to the Classic mode. When using Native/Paired modes, the active theme's templates are used along with whatever they put in the footer, so this question becomes irrelevant. In any case, I'll also open a PR to remove the footer credits from the plugin for a future release.

**Comment by westonruter** [comment]
@tanjoymor I can't speak to what is included on WordPress.com 😄
