### ISSUE TITLE
Allow iframe placeholder to be customized, and default to inline data: URI amp-img

### ISSUE THREAD

**Issue by nabtron** [ampproject/amp-wp#1750]
The CSS calls an image placeholder:

`amp/assets/images/placeholder-icon.png`

Kindly change that to base64 data so that there is no extra callback to server for such a small data.

Like this: 
`
url('data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAGAAAABgAQMAAADYVuV7AAAABlBMVEUAAAD///+l2Z/dAAAAAXRSTlMAQObYZgAAAJtJREFUOMvd07sNAyEQBNA9ERBSwpVCaVAapVACIQFiLsAMi2UHl1jWTfaiXe1H5GlxeKWIiJ9oIhIm+jvA3MAs+AuYpmC7gsNHHFHBJAWbFVxROKuCbwqhq6LAaucAIhvdYIBEWCATbqxm4AQq4ceeBsJYjXDwIliIBolIFnnBoRBZo5yoRPVoRAvoRL95B3+M7xe/Pcb2Ms/KBe/MuxNhHM2TAAAAAElFTkSuQmCC')
`
Filename: | placeholder-icon.png
Filesize: | 243 Byte
Encoded: | 324 Byte
Width: | 96 px
Height: | 96 px

Thanks.

**Comment by westonruter** [comment]
It actually doesn't make sense to use CSS for this at all. This should be changed in the `AMP_Iframe_Sanitizer` to output a data URL as part of the underlying `placeholder` for the `amp-iframe`, right here:

https://github.com/ampproject/amp-wp/blob/d2d31849ec5f3fca1faf6607249ec3c37bc652c9/includes/sanitizers/class-amp-iframe-sanitizer.php#L245-L272

The element used to construct the placeholder should also be defined via sanitizer arg so that it could be customized.

**Comment by westonruter** [comment]
Relates to #783.

**Comment by westonruter** [comment]
The placeholder for iframes can now be controlled as of #4292.
