### ISSUE TITLE
Inline style adding a fixed width to responsive images within a <figure>

### ISSUE THREAD

**Issue by kevinlisota** [ampproject/amp-wp#1787]
Updated our site to AMP 1.0.1 and we are experiencing style issues for images within `<figure>` tags.

Our `<figure>` tags are set to center align using `margin: 0 auto`. The plugin is now adding the following inline CSS style:

```
/* Inline stylesheets */
:root:not(#_):not(#_):not(#_):not(#_):not(#_) .amp-wp-30b254f{width:630px}
```
The `amp-wp-##` class is an md5 hash generated by the plugin.

The fixed width declaration on the `<figure>` is causing images to overflow the viewport and not behave responsively. This does not occur on non-captioned images that are not enclosed in `<figure>`.

I have removed the `amp_post_template_css` action as a temporary workaround.

**Comment by westonruter** [comment]
@kevinlisota It seems this issue has also been reported on WordPress.org: https://wordpress.org/support/topic/image-not-in-right-size/

On the [non-AMP page](https://www.der-bank-blog.de/fuehrung-digitalisierung-und-andere-herausforderungen-fuer-die-zukunft/strategie/15118/) there is this markup:

```html
<div id="attachment_26845" style="width: 760px" class="wp-caption aligncenter">
    <img class="size-full wp-image-26845 lazyload" src="data:image/gif;base64,R0lGODdhAQABAIAAANk7awAAACH5BAEAAAEALAAAAAABAAEAAAICTAEAOw==" data-src="https://www.der-bank-blog.de/wp-content/uploads/2017/03/stefan-schindler-sparda-nürnberg.jpg" alt="Stefan Schindler, Sparda-Bank Nürnberg" width="750" height="596" data-srcset="https://www.der-bank-blog.de/wp-content/uploads/2017/03/stefan-schindler-sparda-nürnberg.jpg 750w, https://www.der-bank-blog.de/wp-content/uploads/2017/03/stefan-schindler-sparda-nürnberg-600x477.jpg 600w" sizes="(max-width: 750px) 100vw, 750px" />
    <p class="wp-caption-text">Stefan Schindler ist Vorsitzender des Vorstandes der Sparda-Bank Nürnberg</p>
</div>
```

In the [AMP version](https://www.der-bank-blog.de/fuehrung-digitalisierung-und-andere-herausforderungen-fuer-die-zukunft/strategie/15118/amp/), it comes out as:

```html
<div id="attachment_26845" class="wp-caption aligncenter amp-wp-05acb6f">
    <amp-img class="size-full wp-image-26845 amp-wp-enforced-sizes" src="https://www.der-bank-blog.de/wp-content/uploads/2017/03/stefan-schindler-sparda-n%C3%BCrnberg.jpg" alt="Stefan Schindler, Sparda-Bank Nürnberg" width="750" height="596" srcset="https://www.der-bank-blog.de/wp-content/uploads/2017/03/stefan-schindler-sparda-nürnberg.jpg 750w, https://www.der-bank-blog.de/wp-content/uploads/2017/03/stefan-schindler-sparda-nürnberg-600x477.jpg 600w" sizes="(max-width: 750px) 100vw, 750px" layout="intrinsic"></amp-img>
    <p class="wp-caption-text">Stefan Schindler ist Vorsitzender des Vorstandes der Sparda-Bank Nürnberg</p>
</div>
```

And it renders incorrectly:

![image](https://user-images.githubusercontent.com/134745/51286690-e1806900-19a8-11e9-80ff-a57a843b6046.png)

The issue is the `amp-wp-05acb6f` class added to the containing `div` where it has the associated stylesheet:

```css
:root:not(#_):not(#_):not(#_):not(#_):not(#_) .amp-wp-05acb6f {
    width: 760px;
}
```

This is expected since it is extracting the `style="width: 760px"` inline style to the `style[amp-custom]` stylesheet.

What is not expected is the fact that it is causing the image to be displayed outside the viewport.

Removing the `amp-wp-05acb6f` class causes the problem to go away. It seems the problem is that the AMP version of the page is not including this CSS in [`style.php`](https://github.com/ampproject/amp-wp/blob/develop/templates/style.php):

```css
.post-content img,
.post-content .wp-caption {
    max-width: 100%;
    height: auto;
}
```

@kevinlisota Would you please try restoring the `amp_post_template_css` action and then add this code to your theme's `functions.php` or a custom plugin:

```php
add_action( 'amp_post_template_css', function() {
    ?>
    .post-content img,
    .post-content .wp-caption {
        max-width: 100%;
        height: auto;
    }
    <?php
} );
```

**Comment by westonruter** [comment]
@kevinlisota Also, do you have CSS like the above in the non-AMP version of the page? If so, where is it coming from?

**Comment by bankblog** [comment]
Hi

thanks for the help here. First, I am not a developer so therefore not very good on php.
The problem comes with version 1, including 1.0.1
It is not in the previous version 0.7

The "normal" URL of the example article is https://www.der-bank-blog.de/fuehrung-digitalisierung-und-andere-herausforderungen-fuer-die-zukunft/strategie/15118/

> Would you please try restoring the amp_post_template_css action 
What erxactly do I have to do here?

> @kevinlisota Also, do you have CSS like the above in the non-AMP version of the page? If so, where is it coming from?
I am not sure.  

> On the non-AMP page there is this markup:
> 
> <div id="attachment_26845" style="width: 760px" class="wp-caption aligncenter">
>     <img class="size-full wp-image-26845 lazyload" src="data:image/gif;base64,R0lGODdhAQABAIAAANk7awAAACH5BAEAAAEALAAAAAABAAEAAAICTAEAOw==" data-src="https://www.der-bank-blog.de/wp-content/uploads/2017/03/stefan-schindler-sparda-nürnberg.jpg" alt="Stefan Schindler, Sparda-Bank Nürnberg" width="750" height="596" data-srcset="https://www.der-bank-blog.de/wp-content/uploads/2017/03/stefan-schindler-sparda-nürnberg.jpg 750w, https://www.der-bank-blog.de/wp-content/uploads/2017/03/stefan-schindler-sparda-nürnberg-600x477.jpg 600w" sizes="(max-width: 750px) 100vw, 750px" />
>     <p class="wp-caption-text">Stefan Schindler ist Vorsitzender des Vorstandes der Sparda-Bank Nürnberg</p>
> </div>
This comes from the theme4 in combination with the caching plugin (Borlabs). But the amp-version is not cached

> 
add this code to your theme's functions.php or a custom plugin:
I added it to the function as I do not know how to build a custom plugin

Your code in the functions.php solves the problem. So it should be included in the nect version.

Cheers
Hansjörg

**Comment by westonruter** [comment]
@bankblog would you be able to deactivate Borlabs momentarily so that I can determine the origin of the CSS on the non-AMP version of the page? You could copy the page source and put it in a [gist](https://gist.github.com/) so that you don't have to wait for me to do so.

**Comment by bankblog** [comment]
Hi

thanks for your help. You may just use an URL with ?nocache at the end like
https://www.der-bank-blog.de/cyber-bedrohungen-kultur/trends/38678/?nocache
to avoid caching load.

**Comment by westonruter** [comment]
@bankblog Thanks.

```css
.post-content img, .post-content .wp-caption {
    max-width: 100%;
    height: auto;
}
```

This CSS is coming from your theme's stylesheet: https://www.der-bank-blog.de/wp-content/themes/smart-mag/style.css?ver=4.9.9

In the immediate term, the above `amp_post_template_css` action makes sense for you. 

If a CSS rule like this is common among themes, then we should include it in the CSS for the classic templates.

**Comment by westonruter** [comment]
@bankblog Do you know where the `width` attribute is coming from in your markup:

```html
<div id="attachment_26845" style="width: 760px" class="wp-caption aligncenter">
    <img class="size-full wp-image-26845 lazyload" src="data:image/gif;base64,R0lGODdhAQABAIAAANk7awAAACH5BAEAAAEALAAAAAABAAEAAAICTAEAOw==" data-src="https://www.der-bank-blog.de/wp-content/uploads/2017/03/stefan-schindler-sparda-nürnberg.jpg" alt="Stefan Schindler, Sparda-Bank Nürnberg" width="750" height="596" data-srcset="https://www.der-bank-blog.de/wp-content/uploads/2017/03/stefan-schindler-sparda-nürnberg.jpg 750w, https://www.der-bank-blog.de/wp-content/uploads/2017/03/stefan-schindler-sparda-nürnberg-600x477.jpg 600w" sizes="(max-width: 750px) 100vw, 750px" />
    <p class="wp-caption-text">Stefan Schindler ist Vorsitzender des Vorstandes der Sparda-Bank Nürnberg</p>
</div>
```

What is the underlying raw HTML for this image in the post content? Is it a `caption` shortcode?

**Comment by bankblog** [comment]
@westonruter Thanks a lot. I told the theme author to have a look.
The width should also come from the theme, all the rest from Borlabs cache Plugin

**Comment by westonruter** [comment]
@bankblog Can you share the underlying raw content from the post for that image and caption?

**Comment by bankblog** [comment]
@westonruter what exactly do you mean by "raw content"?

**Comment by westonruter** [comment]
@bankblog In the post editor, switch from Visual to the HTML view, and then select the HTML for that image and caption.

**Comment by bankblog** [comment]
@westonruter Thanks. Here is the code inisde the article

`[caption id="attachment_15119" align="aligncenter" width="600"]<img class="size-full wp-image-15119" src="https://www.der-bank-blog.de/wp-content/uploads/2014/11/moderne_fuehrung.gif" alt="Moderne Führung" width="600" height="300" /> Moderne Führung bedeutet die Betonung der gemeinsamen Arbeit, um Ziele zu erreichen.<br />© <a href="http://www.shutterstock.com/de/pic-147480179/stock-photo-teamwork-works-together-to-build-a-gear-system.html?src=8rGqj9Q_P8RocQL7mTPUFQ-5-18 " target="_blank">Shutterstock</a>[/caption]
`

**Comment by bankblog** [comment]
@westonruter Do you need more info?

**Comment by westonruter** [comment]
Not at the moment. Just need some time to figure out the best way to incorporate the CSS changes.

Another report of this issue: https://wordpress.org/support/topic/centered-images-in-full-size-dont-fit-on-page/

**Comment by westonruter** [comment]
Maybe this is something that was missed as part of https://github.com/ampproject/amp-wp/pull/1728

Actually, it seems rather that your custom templates are not using the `amp-wp-article-content` class on the element around the content:

https://github.com/ampproject/amp-wp/blob/39b15688771c5809b91b40bd6bd6bb3e5154f7b2/templates/single.php#L19

So that is why the rule added in #1728 is not working.

**Comment by westonruter** [comment]
@bankblog  please try adding the `amp-wp-article-content` class to the element similarly, and confirm whether that fixes the issue instead of including the extra CSS.

**Comment by bankblog** [comment]
@westonruter 
Thanks
I did not change the plugin template. Maybe it comes from the theme. I will check.

**Comment by kevinlisota** [comment]
@westonruter Sorry for the delay. Circling back on your request above. Just intalled 1.0.2, and the issue persists.

adding the CSS for the `post-content` class doesn't help, as the AMP template does not contain a `post-content` class. 

We are using the classic template, and styles all come from `style.php`. We override `style.php` in our theme folder with our own custom CSS, utilizing a bunch of the base CSS from your `style.php`.

We do have responsive img CSS in our non-AMP pages as you describe. That comes from our own stylesheet, which is not served on AMP pages.

I'm capable of tweaking CSS to overcome this, but think there is likely an underlying issue for anyone out there using the AMP classic template.

Here is a sample AMP page for us: https://www.geekwire.com/2018/microsoft-ceo-satya-nadella-explains-hes-not-worried-alexa-windows-pcs/amp/

Note, I have the `amp_post_template_css` action turned off, so the offending CSS on captioned images is not being inserted at the moment.

**Comment by westonruter** [comment]
@kevinlisota What about if you restore the `amp_post_template_css` action include this in your `functions.php`:

```php
add_action( 'amp_post_template_css', function() {
    ?>
    .amp-wp-article-content amp-img {
        max-width: 100%;
    }
    <?php
} );
```

I'm thinking that this selector needs to be added to this rule:

https://github.com/ampproject/amp-wp/blob/12a0627d18e5ea37abd1838b7161a21fc389913f/templates/style.php#L246-L248
