### ISSUE TITLE
Make get_validated_url_file_path function compatible with non-static files

### ISSUE THREAD

**Issue by aristath** [ampproject/amp-wp#1849]
In some cases and projects we need to dynamically generate CSS.
If the URL is `domain.com/?action=my-theme-get-styles&foo=bar` and not a static file like `domain.com/something.css` then the validation fails due to the missing file extension and the CSS never gets parsed by AMP

**Comment by westonruter** [comment]
Humm. I thought this would work now. See https://github.com/ampproject/amp-wp/issues/1317.and https://github.com/ampproject/amp-wp/pull/1357.

What is the validation error? What is the full markup?

**Comment by aristath** [comment]
The error:

![screenshot_2019-02-03 errors for single url demo wordpress](https://user-images.githubusercontent.com/588688/52175417-36dfb700-27ac-11e9-8fec-cf00981a9610.png)

The URL it tries to get is `http://localhost?action=kirki-styles`
the markup:
```html
<link rel='stylesheet' id='kirki-styles-css'  href='http://localhost?action=kirki-styles' type='text/css' media='all' />
```

**Comment by aristath** [comment]
perhaps it's because I'm on localhost (no TLD)?

**Comment by westonruter** [comment]
I don't think that should matter. From the condition here:

https://github.com/ampproject/amp-wp/blob/d0f36c9d313c941bad8c942a4734774bbd6ff409/includes/sanitizers/class-amp-style-sanitizer.php#L717-L718

It seems like that should be just what you need. Because it is a `disallowed_file_extension` error, it should then fall through to treat it like it is fetching an external stylesheet. The `fetch_external_stylesheet` method should really be named `fetch_stylesheet_over_http`.

**Comment by westonruter** [comment]
@aristath I've opened a PR with some changes which I think will fix what you're seeing here. Please give the build linked here a try: https://github.com/ampproject/amp-wp/pull/1852#issuecomment-460475798

**Comment by aristath** [comment]
Confirmed, that PR fixes the issue :+1:
