### ISSUE TITLE
Turned on paired mode, 3 hard errors with AMP validation

### ISSUE THREAD

**Issue by nicopujol** [ampproject/amp-wp#1851]
Hi, 

We are looking to update our AMP theme and are testing the new paired mode. It successfully filters incompatible code on one of our sites. On the bigger install, there are 3 issues remaining that the sanitizer cannot remove, apparently related to amp-boilerplate. https://bit.ly/2BjD3RP. The logo is also appearing oversized, when viewed in desktop mode, but correct in mobile mode.  Thanks!

**Comment by westonruter** [comment]
Yes, I can see that on https://www.laylita.com/recettes/oeuf-cocotte-au-roquefort-lardons-et-champignons/?amp

The problem is that the AMP boilerplate `noscript` CSS is getting pushed into the body:

```html
...
</head>
<body>
<div id="laylita-2018v1"></div>
<meta name="pinterest-rich-pin" content="false">
<!--AdThrive JW Collapsible Player Header-->
<!-- Global site tag (gtag.js) - Google Analytics -->
<meta name="generator" content="AMP Plugin v1.0.2; mode=paired">
<link rel="icon" href="https://www.laylita.com/recettes/wp-content/uploads/2016/07/cropped-LAY512x512-32x32.png" sizes="32x32">
<link rel="icon" href="https://www.laylita.com/recettes/wp-content/uploads/2016/07/cropped-LAY512x512-192x192.png" sizes="192x192">
<link rel="apple-touch-icon-precomposed" href="https://www.laylita.com/recettes/wp-content/uploads/2016/07/cropped-LAY512x512-180x180.png">
<meta name="msapplication-TileImage" content="https://www.laylita.com/recettes/wp-content/uploads/2016/07/cropped-LAY512x512-270x270.png">
<noscript><style amp-boilerplate>body{-webkit-animation:none;-moz-animation:none;-ms-animation:none;animation:none}</style></noscript>
...
```

The problem seems to be that you have this `<div id='laylita-2018v1'></div>` tag that is getting output in the `head`. You can see this on your non-AMP page: https://www.laylita.com/recettes/oeuf-cocotte-au-roquefort-lardons-et-champignons/

When PHP DOM parser is parsing the elements in the `head` and it comes across an element that shouldn't be in the `head`, then it just short-circuits the `head` right there.

So where is that `div` coming from?

**Comment by nicopujol** [comment]
We use the Genesis framework (popular parent theme for WordPress). In the Header and Footer Scripts area, we insert this div for our ad partner to target the right locations on non-AMP pages for ad insertion. 

For AMP we use a different ad insertion tool (Ad inserter plugin). So we could potentially move this offending line of code elsewhere that would only load on canonical/non-AMP pages. Where would be best?

![genesis parent theme header and footer scripts](https://user-images.githubusercontent.com/1319146/52240170-13d50600-2885-11e9-83c7-c58b0d5a9294.jpg)

**Comment by westonruter** [comment]
It's illegal to put `div` in the `head`, so that's not the right place to put it. So you should move it even in non-AMP pages. You can see this by [checking the (non-AMP) validity](https://validator.w3.org/nu/#textarea) of a basic HTML5 page with that tag present:

```html
<!DOCTYPE html>
<html lang=en>
  <head>
    <meta charset="UTF-8">
    <title>Title of the document</title>
    <div id='laylita-2018v1'></div><!-- 👈 -->
  </head>
  <body>
    Hello.
  </body>
</html>
```

You can see that this is not valid HTML5:

![image](https://user-images.githubusercontent.com/134745/52240640-40d5e880-2886-11e9-8583-8c7b5fa416a3.png)

So you should instead add something like this to your theme's `functions.php` or a custom plugin:

```php
add_action( 'wp_footer', function() {
    echo '<div id="laylita-2018v"></div>';
} );
```

**Comment by nicopujol** [comment]
Thanks! This resolved the errors. Down to usability issues, great that AMP pages are now valid in paired mode.
