### ISSUE TITLE
Set before/after animation sequence

### ISSUE THREAD

**Issue by ThierryA** [ampproject/amp-wp#1882]
- [x] Add field for determining whether an element should be animated after another element finishes animating.

**Comment by swissspidy** [comment]
Based on our discussions, in a first round this should be a simple dropdown where one could say "Start after XY finishes"

In order to do this, we need a list of all elements on the current story page with an animation.

Some `select( 'core/editor' )` functions that might be helpful: `getBlocks`, `getSelectedBlockClientId`, `getBlockHierarchyRootClientId`, and `getBlock`.

However, we probably need to create our own separate store for all animated elements. This would be easier to implement and future-proof (think full-fledge animation control in a timeline).

Speaking of that, I wonder what we could actually show in that dropdown. For each block, we have its type and its attributes/content, so maybe the dropdown could look like this:

```
Start animation after the following element:

* Immediately
* "Lorem ipsum dolor" (Text block)
* "Blue Montains" (Image)
* "Buy now" (CTA)
```

This will depend a bit on our reworking of layers, so maybe we need to hold off on this one for a bit at first.

@westonruter Thoughts?

**Comment by westonruter** [comment]
Coming up with names for the elements in the drop-down could be a challenge. If you have two images in a page, how would we differentiate one from the other in the list? Rely on attachment title? What about external embeds like YouTube? The Block Navigation component does not provide helpful contextual snippets. Seems like something that should be part of core, no?

**Comment by swissspidy** [comment]
Yep, it's definitely something we need to figure out along the way.

There's an issue for the Block Navigation component about this, but without much traction: https://github.com/WordPress/gutenberg/issues/11010. The following project is mentioned there as well, which shows excerpts of headings: https://github.com/sortabrilliant/guidepost

Compared to regular posts, AMP stories allow only a limited set of blocks, which might make it a bit easier for us to implement here. After that, we can refine things and then try to propose something for inclusion in Gutenberg.

**Comment by swissspidy** [comment]
As suggested by @ThierryA, I had a look at how Apple's Keynote does handle animations.

At first, the UI only exposes a simple numbered dropdown, as you can see in the sidebar on this screen here:

![screenshot 2019-02-21 at 14 34 09](https://user-images.githubusercontent.com/841956/53172563-ee1a6180-35e5-11e9-989b-215d94d6a83c.png)

It works very simple: If you select **1** for an element, the current number 1 will be placed second.

For more complex arrangements, one can click on **Build Order** to see something more like we have discussed previously:

![screenshot 2019-02-21 at 14 33 18](https://user-images.githubusercontent.com/841956/53172726-58cb9d00-35e6-11e9-9f67-4602a6cfd1e9.png)

The label on the left is either an excerpt, the image name, or the type of shape. The label on the right is the animation type.

At the bottom of the modal window you can change the delay for each animation and whether it should start after or together with a previous animation.

In our use case, we only have 1 animation per element, which makes things a bit easier.

**Comment by ThierryA** [comment]
@swissspidy I would also advise to take a look at Google Slides way of handling animation. It is pretty close to keynote but you might get some useful inspiration from that tool too.

**Comment by swissspidy** [comment]
Google Slides:

![screenshot 2019-02-22 at 17 39 48](https://user-images.githubusercontent.com/841956/53342349-0a800c00-390e-11e9-944f-96d5bc2655cd.png)
![screenshot 2019-02-22 at 17 39 18](https://user-images.githubusercontent.com/841956/53342351-0a800c00-390e-11e9-8258-7604076c6b06.png)
![screenshot 2019-02-22 at 17 38 54](https://user-images.githubusercontent.com/841956/53342352-0b18a280-390e-11e9-8913-320da060d9cd.png)

**Comment by westonruter** [comment]
So Google Slides tries to show a little thumbnail of the element being animated and Keynote provides a text description.
