### ISSUE TITLE
Page horizontal viewing

### ISSUE THREAD

**Issue by ThierryA** [ampproject/amp-wp#1903]
- [x] Remove up/down movement block arrows in page controls, or replace with right/left arrows
- [x] Implement carousel animation to show adjacent pages as you cycle through

**Comment by dawidmlynarz** [comment]
👋 Hello! I have been exploring possibilities for the horizontal navigation between AMP Stories. For now, I called each of the items _Slides_ as it somehow fitted more than a _Page_.

Given the fact that this is a highly interactive project, I have produced Principle prototype to show you more interactions and flows instead of a static screen that may cause a lot of questions. Please take a look at the video attached and share your thoughts.

![amp stories - horizontal](https://user-images.githubusercontent.com/8026823/53483385-ad0ccc00-3a81-11e9-812f-d02cd1272cc3.gif)

Besides that, I have also created [Invision prototype holding some static screens](https://invis.io/NSQQARUCY79) so you can leave comments inside. Please have a look at the link below and check your emails as you should get the invitations.

Looking forward to your feedback!

**Comment by ThierryA** [comment]
Heya @dawidmlynarz, overall I really like it, awesome work 💥 I left a few comments on [Invision](https://invis.io/NSQQARUCY79).

One additional comment since it applies globally throughout the design is to increase contrast overall for accessibility purposes.

Looking forward to the round of reviews.

**Comment by dawidmlynarz** [comment]
Thanks for the input @ThierryA - all the comments on Invision are addressed. Really good point about accessibility, I ave increased the contrast of the cards and some elements. I was mainly using colors according to the WordPress palette from Sketch UI Kit so let me know if they need to be optimized even more.

Please find the revised prototype below with the fading and slightly revised bottom navigation. Now indicators are positioned in the center below the active slide.

![amp stories - horizontal browsing - v2](https://user-images.githubusercontent.com/8026823/53489718-2dd3c400-3a92-11e9-9307-6cdedc17ef1c.gif)

If you think (from engineering perspective) that we need to refine the design, please also let me know and we will work until the feasible version. I'm open to iterate!

🙌 Looking forward to your feedback!

**Comment by ThierryA** [comment]
Great, round of reviews is great.

> I called each of the items Slides as it somehow fitted more than a Page

Coming back to the comment above, AMP Stories have the concept of "Book Pages" and are referred as pages throughout the AMP Stories docs so I would suggest to stick to it.

Will take a other pass at the review with @albertomedina before it moves to engineering 😉

**Comment by dawidmlynarz** [comment]
Thanks!

> Coming back to the comment above, AMP Stories have the concept of "Book Pages" and are referred as pages throughout the AMP Stories docs so I would suggest to stick to it.

In that case, I couldn't agree more! That makes total sense to keep the **Pages** name. I will update Invision so everything is consistent.

**Comment by swissspidy** [comment]
Currently working on this in the https://github.com/ampproject/amp-wp/tree/amp-story/1903-horizontal branch. It is based off of #1904.
