### ISSUE TITLE
[AMP Stories] Overlapping Inserter Button

### ISSUE THREAD

**Issue by amedina** [ampproject/amp-wp#2047]
when I am editing a page or a block within a page, The default inserter on top overlaps the block controls; and also it seems the inserter associated for the block appears misplaced. 
<img width="547" alt="Inserter-Bug" src="https://user-images.githubusercontent.com/506089/55417085-dd360780-5524-11e9-8a54-1b80fcb22cea.png">

**Comment by swissspidy** [comment]
I'd also like to point out the inserter button on the right side of the page. It only appears when editing a block within the page, not the page itself, which is a bit odd.

My suggestions:

1. Block inserter above page block  
  Does not make sense IMO because of the horizontal navigation we have. **Remove**
2. Block inserter above image block (or any block within the page, for that matter)  
  Does not make sense IMO, especially when blocks are positioned freely on the page and even rotated. **Remove**
3. Block inserter on the right side of the page  
  Should always be visible, and have the size of an actual page.
