### ISSUE TITLE
[AMP Stories] Improve template preview

### ISSUE THREAD

**Issue by miina** [ampproject/amp-wp#2061]
Investigate improving the preview of a template.

Since a template (or "skeleton template") doesn't include background image and other images by default then it doesn't necessarily reflect how it could actually look like.

Some ideas were discussed for improving this, for example:
- Adding a featured image to each template which could be the background image where relevant and displayed in the preview;
- Adding a featured image to each template which would be a preview of that template when completely populated and this image would display when hovering on the template.

One complication with the approach is that templates are not static and the user might modify the template this resulting in the preview not being accurate anymore or the background image not matching with the design anymore.

**Comment by westonruter** [comment]
When there are reusable blocks, the inserter will show a preview of them when hovering over one of them. For example, I added this cover image block as a reusable block:

![image](https://user-images.githubusercontent.com/134745/55588933-e91bf800-56e3-11e9-979b-17a43ea314db.png)

I can then hover over the block and see a preview of it:

![image](https://user-images.githubusercontent.com/134745/55588987-0650c680-56e4-11e9-8618-0b32b27111c7.png)

Granted, the previous is horribly incorrect. (I guess that is a known issue?) But otherwise, could this be used for the template preview? Or is it not feasible?

Otherwise, I was sure there was some way to use canvas to capture the screenshot of a DOM element, with some restrictions. After searching for it I don't see it as being something generally available. The main hack I see is putting the HTML inside of an `svg` and then doing `drawImage` for that SVG into a Canvas. But it lacks fidelity. There's also [html2canvas](https://html2canvas.hertzen.com/). But if this were possible, then such a screenshot could saved as metadata for the `wp_block` post and then used to display in the template inserter, independent of the featured image.
