### ISSUE TITLE
CSS issues with theme and recipe card when logged in

### ISSUE THREAD

**Issue by nicopujol** [ampproject/amp-wp#2103]
Loaded v1.1 beta 1, and noticed an issue which might exist in 1.0, noting it here. 
https://gist.github.com/nicopujol/3a8e35a493c34e699a3030cc4b16ec3b
Test page: https://www.nicolaspujol.com/spicy-pineapple-pasta-with-oil-free-seasoning/
Seems OK when logged off.

**Comment by westonruter** [comment]
@nicopujol Thanks for the report. This issue is due to the admin bar. You can see in the page source that there are stylesheets being excluded because the admin bar CSS is pushing them out. 

The immediate fix is for you to turn off the admin bar on AMP pages. You can do this in AMP settings.

The longer term fix is that we plan to ignore the admin bar for validation purposes. See https://github.com/ampproject/amp-wp/issues/1921
