### ISSUE TITLE
AMP custom elements are corrupted by force_balance_tags()

### ISSUE THREAD

**Issue by andremacola** [ampproject/amp-wp#2156]
When pasting a vídeo url on Gutenberg. The embed code do not validate with the Amp plugin. I am doing something wrong? I did not made any customization to the default wp block.

![amp-video](https://user-images.githubusercontent.com/3408809/56474864-50f96f00-6456-11e9-80d9-0740e271917c.gif)

![Captura de Tela 2019-04-21 às 16 57 23](https://user-images.githubusercontent.com/3408809/56474881-8e5dfc80-6456-11e9-9cd3-17a2ee9029e5.png)

**Comment by westonruter** [comment]
I've seen this issue come up before. It is an issue with `force_balanced_tags()` in WordPress core: https://wordpress.org/support/topic/how-to-enable-shortcodes-oembed-for-comments-in-amp-pages/#post-11427212

In short, the function is erroneously converting `<amp-youtube...` into `<amp -youtube...`.

Notice the space being added. The AMP plugin then parses the document and comes across invalid `amp` tags.

Can you confirm you are applying this function to `the_content`?

If so, as a quick fix, you can remove the filter. Otherwise, you could adapt the code linked to in the gist linked to in the support forum topic above. 

Ultimately, WordPress core needs to fix it's implementation of `balanceTags` to be aware of custom elements (which contain hyphens).

**Comment by andremacola** [comment]
Thanks for the reply.

I'm not using this filter. Actually I am not using any filter in the_content but I am using a Multisite environment and I known Wordpress filter some security stuff in the_content when using MU.

**Comment by westonruter** [comment]
> Actually I am not using any filter in the_content but I am using a Multisite environment and I known Wordpress filter some security stuff in the_content when using MU.

@andremacola I checked and it doesn't seem that `force_balance_tags()` is being added in multisite. The symptom you are reporting sure seems to be the same, however. Can you try to identify which filter on `the_content` is causing the issue? Is `has_filter( 'the_content', 'force_balance_tags' )` returning `false` on your setup where `the_content()` is called?

**Comment by andremacola** [comment]
@westonruter You were right, some other developer did a very old commit using `force_balance_tags` to remove empty paragraphs. Can close the ticket

**Comment by westonruter** [comment]
I'm going to leave this open for now to track getting a WordPress core fix for this, since it has come up twice now.

**Comment by westonruter** [comment]
I filed a core ticket with the fix: https://core.trac.wordpress.org/ticket/47014
