### ISSUE TITLE
[AMP Stories] A saved AMP Story displays as unsaved when first loading

### ISSUE THREAD

**Issue by miina** [ampproject/amp-wp#2172]
Steps to reproduce:
- Create a new AMP Story, add some blocks and content.
- Save the story.
- Refresh the page.
- See the "Update" button of the Story being active, it shouldn't be.

**Comment by swissspidy** [comment]
**Steps to reproduce**

1. Create a new AMP Story, add some blocks and content.
1. Save the story.
1. Refresh the page.
1. Verify that the post is displayed as "Saved" and cannot be updated (since there were no changes)

It should basically look like this:

<img width="338" alt="Screenshot 2019-05-14 at 11 17 21" src="https://user-images.githubusercontent.com/841956/57721781-ec3aca00-7639-11e9-81ed-2ba0ca5419fa.png">

**Comment by csossi** [comment]
Verified in QA - "Update" not appearing after refresh:
![image](https://user-images.githubusercontent.com/16945664/57748684-fe078600-76a8-11e9-8936-1da27bc3a2a4.png)
