### ISSUE TITLE
Background color of story title block doesn't automatically extend to wrapped lines

### ISSUE THREAD

**Issue by westonruter** [ampproject/amp-wp#2210]
When text wraps in the Story Title block, I would expect the background color to extend to the new line. Instead, it only appears on the first line:

![image](https://user-images.githubusercontent.com/134745/56926776-5c1c5280-6a87-11e9-81a8-cac191958ae8.png)

![image](https://user-images.githubusercontent.com/134745/56926809-6b9b9b80-6a87-11e9-831d-7ae1beebbfb2.png)

This is even before I tried resizing the height of the block. 

The issue seems to be that it has an initial `height` defined. If it had an initial `height` of `auto` then this wouldn't be a problem.

**Comment by westonruter** [comment]
Note that I am able to resize the block to make the background take up both lines, but having a fixed height would have undesirable effect if, for example, the story were viewed in a display that was wider and didn't require wrapping.

**Comment by westonruter** [comment]
Another symptom of this problem, given a story date block without a background color:

![image](https://user-images.githubusercontent.com/134745/56927597-6b9c9b00-6a89-11e9-8ade-09c43f6639bc.png)

Upon setting the background color, notice that the margin at the bottom is too small:

![image](https://user-images.githubusercontent.com/134745/56927633-88d16980-6a89-11e9-9447-0e5d4366aeb5.png)

Again, I believe this is due to the fact that the block gets an initial `height` value which should instead be left undefined until the user manually resizes.

**Comment by swissspidy** [comment]
> Note that I am able to resize the block to make the background take up both lines, but having a fixed height would have undesirable effect if, for example, the story were viewed in a display that was wider and didn't require wrapping.

Sounds like we'd need a way to reset the height to `auto` once you started changing it?

**Comment by swissspidy** [comment]
Wanted to give this a shot myself, to see how it goes.

### Step 1: Adding the title block for a story with a long title.

Editor:

<img width="385" alt="Screenshot 2019-05-10 at 11 35 52" src="https://user-images.githubusercontent.com/841956/57558104-5816ed00-7331-11e9-80f8-1f9a3e6213a3.png">

Frontend:

<img width="463" alt="Screenshot 2019-05-10 at 11 36 13" src="https://user-images.githubusercontent.com/841956/57558107-5baa7400-7331-11e9-813c-74ac3215a59d.png">

**Observation:**

The block is very small in the editor, and the text overflows the container. On the frontend the text is displayed normally.

**Expectation:**

* The initial block height is large enough to fit the whole title
* The font size is just big enough to fit the container (which itself might be a bit taller too) -> basically amp-fit-text
* `overflow:hidden` on the frontend because the block is not that tall
* The font size in the editor and on the frontend match better

### Step 2: Adding background color

Editor:
<img width="428" alt="Screenshot 2019-05-10 at 14 40 29" src="https://user-images.githubusercontent.com/841956/57558199-a75d1d80-7331-11e9-8309-f36ab1ad0ac5.png">

Frontend:
<img width="492" alt="Screenshot 2019-05-10 at 14 40 35" src="https://user-images.githubusercontent.com/841956/57558202-a9bf7780-7331-11e9-8dbd-be389319940e.png">

**Expectation:**

* Same expectations above about the height
* Background is for the whole text, not just the first line

### Step 3: Resizing the block

Editor:

<img width="420" alt="Screenshot 2019-05-10 at 14 40 47" src="https://user-images.githubusercontent.com/841956/57558216-b3e17600-7331-11e9-8396-aa71955eeb16.png">

Frontend:

<img width="510" alt="Screenshot 2019-05-10 at 14 40 52" src="https://user-images.githubusercontent.com/841956/57558210-b217b280-7331-11e9-8d49-4c48cad76c9a.png">

**Expectation:**

* I could use [multi-line padded text](https://css-tricks.com/multi-line-padded-text/)
* Same expectations about the font size differences

### Conclusion

* We should support `amp-fit-text` here
* Font size discrepancies need to be addressed
* Create new feature request for multi-line padded text

**Comment by swissspidy** [comment]
**Testing instructions**

1. Create new story with a long title
2. Insert story title block, both with and without background colors
3. Verify that the block's initial height is enough so that the whole text fits in it
4. Verify that the block can be resized, both with the "Automatically fit text to container" option and without it
5. When disabling "Automatically fit text to container", verify that the block cannot be made smaller than the space allocated by the text (i.e. the text cannot overflow the container)

**Comment by csossi** [comment]
I can get the text to overflow the container here when disabling "automatically fit text to container":

![image](https://user-images.githubusercontent.com/16945664/58115504-325ad500-7bc8-11e9-88b6-ad144fad676f.png)

**Comment by swissspidy** [comment]
Looks like the issue disappears as soon as one clicks anywhere else in the editor or when clicking on Save. So it is a bit of an edge case.

**Comment by miina** [comment]
@swissspidy When testing then the issue did not disappear as soon as I clicked anywhere else, in addition, changing the width adjusted the height of the title block to sill try to fit the text inside the title.

Not sure if that's intended. For example, originally, this title block had around 300px as height but after making it narrow, this happened:
![Screen Shot 2019-05-23 at 11 37 16 AM](https://user-images.githubusercontent.com/3294597/58242576-5bf23880-7d4f-11e9-81b5-660d938b456a.png)

The expected behavior should be that the width or height should not change if the area tries to go smaller than the text needs. I think it would be good to create a separate issue for that specifically, seems to do with resizing and minimum measures more than the original task of this bug. I'll create a separate issue for that.

However, I can reproduce another issue which seems to do more with the original issue:
![Screen Shot 2019-05-23 at 11 42 04 AM](https://user-images.githubusercontent.com/3294597/58242943-04080180-7d50-11e9-818d-1691d7acc3c3.png)

Looks like the background color does not extend to the block lines in case of Author and Date meta blocks. Note that this is when amp-fit-text is turned off.

**Comment by swissspidy** [comment]
>  I'll create a separate issue for that.

Fair enough.

> However, I can reproduce another issue which seems to do more with the original issue

That should be trivial, just need to add some `height: 100%` I think. Although I thought that was fixed, since this is what the original issue was about 🤔

**Comment by miina** [comment]
@csossi Could you re-test this again?

Note that what requires testing here is:
- Make sure that the background color extends to the wrapper lines in case of Text block, Author, Story Title, and Story Date blocks.
- This should happen for both "Automatically fit text to container" setting on and off.

Note that for the issue you found and mentioned in https://github.com/ampproject/amp-wp/issues/2210#issuecomment-494474035 we created a separate issue since it involved issues a bit out of the scope of this issue, so please ignore that specific issue when testing.

**Comment by csossi** [comment]
Verified in QA
