### ISSUE TITLE
Grouping blocks 

### ISSUE THREAD

**Issue by amedina** [ampproject/amp-wp#2216]
It would be useful to have the ability of group blocks so that they can be dragged/rotated all at once. 

I created two overlapping blocks and it was virtually impossible to select one of them.

**Comment by swissspidy** [comment]
Gutenberg now has a group block that can contain other blocks. Example:

<img width="1341" alt="Screenshot 2019-05-16 at 13 37 38" src="https://user-images.githubusercontent.com/841956/57885454-d36c1900-77df-11e9-9a57-4515ba259581.png">

The only missing piece there is you cannot yet select multiple blocks and then click "group blocks". That would be really sweet.

**Comment by swissspidy** [comment]
> The only missing piece there is you cannot yet select multiple blocks and then click "group blocks". That would be really sweet.

Quick update! This has now been added to Gutenberg 5.9: https://github.com/WordPress/gutenberg/pull/14908

The only thing is that block selection in AMP Stories does not really work the same as in the regular post editor, because of all the dragging and such. We'd need to look into that.

Another way to group blocks would be via keyboard shortcuts, which is currently under consideration: https://github.com/WordPress/gutenberg/issues/15980

**Comment by swissspidy** [comment]
Once #2787 is fixed upstream in Gutenberg, I don't think there's anything left to do here.
