### ISSUE TITLE
Auto resizing text block doesn't act as intended

### ISSUE THREAD

**Issue by MackenzieHartung** [ampproject/amp-wp#2233]
When resizing a text block I would assume the text would shrink to fit inside a single line as I extend the size horizontally, however, I need to massively exaggerate the size of the text box to get the auto resized text to appear on one line.

**Comment by miina** [comment]
@MackenzieHartung I was planning to add an issue for the automatic font size not respecting the limits of the resized box, would this ticket already cover it or did you have something else in mind?

Screenshot of the issue:
![Screen Shot 2019-05-02 at 12 45 00 PM](https://user-images.githubusercontent.com/3294597/57071387-9af61680-6cda-11e9-8661-d84db62fab37.png)

The text should fit inside the resized box instead of being on two lines.

**Comment by swissspidy** [comment]
**Testing instructions**

1. Create text block.
2. Ensure "auto fit text" is turned on
2. Resize block at will
3. Verify that the font size changes according to available space.

**Comment by miina** [comment]
@csossi Sorry for that but could you test this again? Looks like it wasn't deployed to the environment.

**Comment by csossi** [comment]
Verified in QA

Text is remaining in container

Example 1:
![image](https://user-images.githubusercontent.com/16945664/57667148-823a0a80-75d0-11e9-92ff-bf69d687fcf1.png)


Example 2:
![image](https://user-images.githubusercontent.com/16945664/57667175-9a118e80-75d0-11e9-89e1-c821c0989579.png)
