### ISSUE TITLE
Allow dragging rotated blocks without selecting them

### ISSUE THREAD

**Issue by swissspidy** [ampproject/amp-wp#2252]
As a follow-up to #2014 and #1974, we should revisit allowing drag & drop of rotated blocks without the need to select them first.

This way, one can more easily position them on the right side of the screen.

**Comment by miina** [comment]
@swissspidy I'm thinking of picking this up soon, let me know if you already had a potential approach figured out for this. Couldn't find information about it from the previous issues at this moment so I'm assuming that not :)

**Comment by swissspidy** [comment]
@miina No potential approach in mind, but it might sense to first solve the issue of dragging blocks by clicking anywhere, without the block mover. Getting rid of the block mover (with `IgnoreNestedEvents` etc.) might affect rotation handling

**Comment by miina** [comment]
@swissspidy Is the requirement of being able to drag blocks by clicking anywhere logged somewhere? I remember that this was under discussion and the conclusion was that it didn't make sense since otherwise selecting text within a block, for example for making it italic/bold, or for copying etc., would be complicated. Additionally, the pointer style would be confusing -- should it hint clicking or dragging if both actions are available. Basically, the conclusion was that it could be quite confusing UX.

Let me know if there has been an alternative discussion out of GitHub meanwhile.

**Comment by miina** [comment]
How about being able to drag from any of the borders instead of _anywhere_? Like it is in Google Slides for example.

**Comment by miina** [comment]
Also, I'm thinking that perhaps we should keep the rotation while the block is selected -- especially now when the usage of Top Toolbar is enforced it shouldn't be an issue anymore, previously the settings buttons rotated as well and that was quite confusing, however, now that issue is removed. This would also be similar behavior to Google Slides, keeping the block rotated.

Leaving the block rotated gives a better preview of how it actually looks like and removes all the additional movement of a block + makes it much more straightforward to drag/rotate, etc.. Thoughts?

cc @amedina  @westonruter

**Comment by miina** [comment]
> I think the goal is to make it more similar to other apps like Instagram, where you can just drag anywhere, and if you want to select some text, you would first tap on it (i.e. select the block) and then perform the action.

What would happen if the user would like to copy some text from a block (selecting part of the text), or selecting part of the Text to mark it italic/bold -- this would basically be impossible then and result in dragging instead? Not sure if hijacking the whole block area by dragging is the best way to go 🤷‍♀ 

> But let's hear the others before jumping straight into this :-)

Yep, agreed. I started looking into positioning the clone correctly when dragging a rotated block but that'll be required in any approach.

**Comment by swissspidy** [comment]
**Testing instructions**

1. Create multiple text blocks
2. Rotate the blocks and drag them around
3. Verify that rotation is not reset while dragging

**Comment by swissspidy** [comment]
Reopening because of issues with the resizing of rotated blocks.

Demo: https://cloudup.com/c_nacwQlmHq

**Comment by swissspidy** [comment]
As for the resizing, we use Gutenberg's `ResizableBox` component which uses [`re-resizable`](https://github.com/bokuweb/re-resizable) under the hood and just sets some sensible defaults.

Perhaps we can somehow incorporate the rotation angle into the `onResizeStart` / `onResize` / `onResizeStop` callbacks.

Others projects like https://github.com/mockingbot/react-resizable-rotatable-draggable demonstrate that this should be possible.

**Comment by miina** [comment]
Instructions for testing:
- Add a few different block types.
- Make sure that resizing works properly while the blocks are rotated.

Note that there are two known issues:
- Dragging doesn't work right after resizing or rotating, the block needs to be selected again to drag. #2352.
- An image doesn't resize together with the resizing box while resizing, it only resizes once finished. #2357.

**Comment by csossi** [comment]
Verified in QA
