### ISSUE TITLE
Hide Video block toggles for Autoplay and Plays Inline

### ISSUE THREAD

**Issue by westonruter** [ampproject/amp-wp#2283]
Extracted from https://github.com/ampproject/amp-wp/pull/2255, where default values have been provided for `autoplay` and `playsinline`, but what is remaining:

- [x] The Autoplay toggle for the Video block needs to be hidden/removed in AMP Stories, because `autoplay` is required.
- [x] The "Play Inline" toggle for the Video block needs to be hidden/removed _always_ since it is not allowed in AMP.

These depend on https://github.com/WordPress/gutenberg/issues/6023.

![image](https://user-images.githubusercontent.com/134745/57563262-e0f15100-7350-11e9-877b-d7d8d5266eab.png)

**Comment by swissspidy** [comment]
I just noticed that the order of panels in the block sidebar is different right after inserting a block vs. when selecting it later. Since the CSS relies on that order, the toggles are sometimes still visible.

Just inserted:

<img width="1112" alt="Screenshot 2019-05-14 at 12 53 37" src="https://user-images.githubusercontent.com/841956/57727989-a422a400-7647-11e9-9e79-4cb8d8457298.png">


Selected later:

<img width="1146" alt="Screenshot 2019-05-14 at 12 53 46" src="https://user-images.githubusercontent.com/841956/57728000-aa188500-7647-11e9-8b55-21ee6cf362ee.png">

Would be good to have some consistency here. I suppose we need to work  with some filter priorities.

**Comment by swissspidy** [comment]
Looks like that's a Gutenberg issue...

**Comment by swissspidy** [comment]
Opened an issue upstream to get some feedback: https://github.com/WordPress/gutenberg/issues/15641

Maybe this can be fixed by changing the order in which the components are wrapped/returned. Will have to try it out.

**Comment by swissspidy** [comment]
Since this has been tested in #2109, and https://github.com/WordPress/gutenberg/issues/15641 is something I haven't been able to find a workaround for, I'm closing this for now.
