### ISSUE TITLE
Animation - Fly In Top - Starting Position

### ISSUE THREAD

**Issue by csossi** [ampproject/amp-wp#2302]
Noted that If I select Fly In Left/Right/Bottom, the text is not visible at all and then "animates" into position. For Fly In Top, text is already appearing in display before animation starts:

![image](https://user-images.githubusercontent.com/16945664/57666063-9419ae80-75cc-11e9-8775-7c16f4902559.png)

**Comment by kienstra** [comment]
**Question About Issue**

Hi @csossi,
Thanks for testing this. Do you still see the issue?

It looks like the "Fly In" animations for images work as expected. 

For example, here's a [testing story](https://story-test-wordpress-amp.pantheonsite.io/stories/chicago/) with a "Fly In Bottom" animation:

![fly in](https://user-images.githubusercontent.com/4063887/57903927-27095180-7836-11e9-90ad-aeead0edeb4f.gif)

**Comment by swissspidy** [comment]
That gif is for the "Fly in Bottom" animation, the original description mentions all the other Fly In animations though. Do they work well too for you?

**Comment by kienstra** [comment]
**"Fly In" Animations**

All of the animations look to work well, except "Fly In Top" while rotated. Maybe that's what this issue refers to, sorry if I missed that.

Here's a [testing story](https://story-test-wordpress-amp.pantheonsite.io/stories/chicago/) with those "fly in" animations.

All of them look right. Except rotated text blocks with "Fly In Top" actually appear like "Fly In Bottom":

![when-rotated](https://user-images.githubusercontent.com/4063887/57951298-41cbdc80-78af-11e9-832b-c348cce41fb1.gif)

**Comment by swissspidy** [comment]
From a technical perspective the behavior seems to make sense.

Let's say we add a regular text block with the content "Hello World". This should result in a HTML structure like this on the frontend:

```html
<amp-story-grid-layer>
  <div class="amp-story-block-wrapper">
    <h1>...</h1>
  </div>
</amp-story-grid-layer>
```

We rotate the block by 180 degrees. `.amp-story-block-wrapper` is now flipped on its head using `transform: rotate(180deg);`.

Then, we choose "Fly In Top" as an animation for the block.

`<h1>...</h1>` turns into `<h1 animate-in="fly-in-top" animate-in-duration="500ms">...</h1>`

This is the element that AMP now animates.

Due to the rotation of its parent element, `.amp-story-block-wrapper`, the element technically flies in correctly relative to its parent's top location.

Since the `transform` of the animation would clash with the `transform` for rotation (that's why we have `.amp-story-block-wrapper`), the only way I can think of to fix this is by reversing this.

Given this HTML:

```html
<amp-story-grid-layer>
  <div class="amp-story-block-wrapper">
    <h1>...</h1>
  </div>
</amp-story-grid-layer>
```

We would rotate `h1`, and animate `amp-story-block-wrapper`.

Not sure how feasible this is though for all the block types...

**Comment by swissspidy** [comment]
^ pinging @miina to get another pair of eyes here

**Comment by miina** [comment]
@swissspidy Reversing this should work, for all the blocks, as far as I know. Can't think of another way either other than reversing the attributes assigned that you suggested. If it would be possible to animate `amp-story-grid-layer`, things would be easier.

We should probably make the change as early as possible, considering that it'll break all the previously existing blocks (and templates).

**Comment by miina** [comment]
Note: I'll start working on this.

**Comment by swissspidy** [comment]
**Testing instructions**

1. Create new story
2. Add new block
3. Rotate block
4. Add fly-in animation
5. Verify that the fly-in direction is not affected by the rotation

**Comment by csossi** [comment]
This still doesn't seem right to me, based on what I originally reported. FlyIn Left and Right are fine, but FlyInTop and FlyInBottom don't seem right. I'm assuming here that the start of each animation is for NO text to appear on screen. 

For example, see https://story-test-wordpress-amp.pantheonsite.io/?post_type=amp_story&p=1229&preview=true . The page loads with the text partially already appearing before the animation starts

**Comment by miina** [comment]
@swissspidy @westonruter Could this be an issue with AMP Animation generally? That it's not considering rotated elements. Not sure if there's a way how to fix it within the plugin.

It looks like the starting position is on the very edge of the story Page, and rotating it reveals part of the block.

Thoughts?

**Comment by swissspidy** [comment]
Yeah that would be an issue in AMP itself. In fact, there is apparently already a report for it: https://github.com/ampproject/amphtml/issues/22329

Given that this otherwise works, I am moving this to "Ready for Merging".
