### ISSUE TITLE
Allow for a floating tool bar to display above the page within the editor view

### ISSUE THREAD

**Issue by MackenzieHartung** [ampproject/amp-wp#2309]
As a user, I would like to see a tool bar located directly above the page inset inside in the editor. This would allow for a more direct relation between the page being edited and the editing tool bar.

**Comment by swissspidy** [comment]
Besides this being difficult to implement due to Gutenberg's limitation, a big downside of such a floating toolbar is that it would not feel natural to Gutenberg's existing UI elements. In other words, there's no precedent for that.

I could see some potential improvement already when removing the post title field. The post title is eventually going to be a block (see https://github.com/WordPress/gutenberg/issues/11553) anyway, so we could replace our custom `amp/amp-story-post-title` block with that. Without the post title field, the controls would already be way closer to the blocks:

<img width="1176" alt="Screenshot 2019-05-14 at 11 32 03" src="https://user-images.githubusercontent.com/841956/57722772-11303c80-763c-11e9-838c-e2d57399dfcf.png">
