### ISSUE TITLE
Restore suppression of validation error warnings appearing in Reader mode

### ISSUE THREAD

**Issue by swissspidy** [ampproject/amp-wp#2311]
Introduced in #2143 and pointed out in https://github.com/ampproject/amp-wp/pull/2143#issuecomment-483997810:

> Note: One side effect of the changes here (specifically 4645a4a) is that making changes to non-story posts when in Reader mode will start to show the validation error messages. Previously the validation warnings would only be shown when in Native/Transitional mode. The validation notices will likely be a source of complaints for users when in Reader mode, since they would be reported as if the Transitional mode is active.

**Comment by westonruter** [comment]
Relates to #2202.

**Comment by westonruter** [comment]
When in Reader mode, and editing a non-Story post, the validation error warnings should not be displayed (at least for the time being). This was the behavior prior to adding stories, and it needs to be restored at least until the error messages are more user friendly; even more importantly, the warnings should not be displayed before the reader templates are sent through the post processor (#2202), since the validation errors would be coming from the theme template and not from the reader templates.

# Testing Instructions
1. Enable Reader mode.
1. Add a Custom HTML block to a post, save, and a validation error warning should **_not_** appear.
1. Add a Custom HTML block to a story, save, and a warning _should_ appear.

Then:

1. Enable Native (Standard) or Transitional mode.
1. Add a Custom HTML block to a post, save, and a validation error warning _should_ appear.
1. Add a Custom HTML block to a story, save, and a warning _should_ appear.

**Comment by csossi** [comment]
Verified in QA
