### ISSUE TITLE
Enforce last position for CTA block

### ISSUE THREAD

**Issue by swissspidy** [ampproject/amp-wp#2358]
As discussed in https://github.com/ampproject/amp-wp/issues/1974#issuecomment-494309338, the CTA is forced to always be the last layer on page on the frontend already. In the editor, this is only partially true.

We need to:

* [ ] Remove block position controls for CTA block
* [ ] Ensure last position in the editor
  * Use some z-index trickery so that the CTA is always on top of the other blocks
  * When moving around other blocks up and down, make sure they take the CTA block into account
  * Subscribe to content changes to move CTA block to the end in case the order gets messed up

**Comment by swissspidy** [comment]
> Subscribe to content changes to move CTA block to the end in case the order gets messed up

We might consider this one optional / nice-to-have

**Comment by miina** [comment]
Instructions for testing:
- Add two Pages.
- Add CTA block to the second Page
- Verify that the CTA block always displays on top of other blocks.
- Verify that the CTA block is not considered in the block order when reordering other blocks. For example, if the page has the CTA block and only one other block, then the Block Position controls should not appear in the sidebar since in terms of the block order, the one block is considered to be the last and the first block of the Page -- CTA block is excluded. Also, if there are more blocks on the page then the Block Position controls should be disabled and enabled accurately, not considering the CTA block.
- Verify that the CTA block doesn't have Block Order controls in the sidebar.

**Comment by csossi** [comment]
Verified in QA

![image](https://user-images.githubusercontent.com/16945664/58635881-ff49cd00-82bc-11e9-8760-c960f66043c1.png)
