### ISSUE TITLE
Wrapper elements causes problem for conversion in Block Resolving for Stories

### ISSUE THREAD

**Issue by westonruter** [ampproject/amp-wp#2370]
I made a story page as depicted in #2368 and then when I tried switching to the branch, I got the expected:

![image](https://user-images.githubusercontent.com/134745/58129702-33dbcb80-7bcf-11e9-8364-1c0cdf85eb3b.png)

When clicking “Resolve” the suggested resolution is not correct:

<img width="1166" alt="Screen Shot 2019-05-21 at 13 47 20" src="https://user-images.githubusercontent.com/134745/58129730-46560500-7bcf-11e9-8b18-b48a50b59c57.png">

The `amp-story-grid-layer` and the `amp-story-block-wrapper` are incorrectly getting added a second time.

Fixing this will be very important once stories are in a stable release, in addition to making sure that we start maintaining `deprecated` conversions.

**Comment by swissspidy** [comment]
Note: Also reported in #2376.

**Comment by swissspidy** [comment]
I cannot reproduce this with the steps outlined in #2376, which would have been a more likely scenario than switching branches.

However, given that theses divs are added by `wrapBlocksInGridLayer`, I wonder if that function could simply check `element` to see whether these divs already exist.

Also, since this function is hooked to `blocks.getSaveElement`, maybe this is a bug in Gutenberg. https://github.com/WordPress/gutenberg/issues/9811 looks relevant here.

**Comment by swissspidy** [comment]
@westonruter That‘s not really common, is it? When we change the markup in the future we‘d properly deprecate the old one.

**Comment by westonruter** [comment]
Well, it _has_ happened very frequently. I _hope_ it wouldn't happen after we release, but there should still be graceful handling if it does happen (e.g. if someone tries editing the HTML directly).

**Comment by swissspidy** [comment]
Created a PR at #2484 that should theoretically fix this.

**Comment by kienstra** [comment]
**Technical QA?**

Hi @swissspidy,
Do you think the 'technical QA' as part of your #2484 is enough to move this to 'Ready for merging?' Or do you think more functional testing would help?

**Comment by swissspidy** [comment]
I think we're good here!
