### ISSUE TITLE
Can't use the navbar on mobile

### ISSUE THREAD

**Issue by zJar84** [ampproject/amp-wp#2397]
Hello, I wan't to use the navbar in [https://significadodelosgirasoles.ovh/](https://significadodelosgirasoles.ovh/) but the plugin AMP doesn't let me use the navbar collapsed.

If you click on the button with three lines at the bottom (on mobile), it doesn't do nothing.

I'm using the AMP plugin in Native mode, and the plugin Glue for Yoast SEO and AMP.

Can anyone say me the answer?

Thanks.

**Comment by westonruter** [comment]
It looks like what is needed is for the menu to have the AMP integration for toggling the necessary classes to show the menu. There are instructions for how to do this at https://amp-wp.org/documentation/playbooks/toggling-hamburger-menus/

If you get stuck, please share a ZIP of the theme so we can try. Since it is a commercial theme (apparently) you may need to share privately, though it should still be GPL licensed.

Lastly, we should document the code here for the theme so others can use it as well. Maybe the theme could actually add direct support.

**Comment by westonruter** [comment]
Also, the Yoast Glue plugin shouldn't be needed anymore.

**Comment by zJar84** [comment]
> It looks like what is needed is for the menu to have the AMP integration for toggling the necessary classes to show the menu. There are instructions for how to do this at https://amp-wp.org/documentation/playbooks/toggling-hamburger-menus/
> 
> If you get stuck, please share a ZIP of the theme so we can try. Since it is a commercial theme (apparently) you may need to share privately, though it should still be GPL licensed.
> 
> Lastly, we should document the code here for the theme so others can use it as well. Maybe the theme could actually add direct support.

I've implemented the codes on the functions.php but it doesn't work. How can I share the private ZIP?

Also I've comunicated it to the theme company to solve the problem. I'll see their answer tomorrow.

Thanks.

**Comment by westonruter** [comment]
You can send it to me on WordPress Slack if you are there.

**Comment by zJar84** [comment]
> You can send it to me on WordPress Slack if you are there.

I prefer send it via e-mail. I am not in WordPress Slack.

**Comment by westonruter** [comment]
OK, please send to westonruter+zJar84@google.com

**Comment by westonruter** [comment]
Thanks for sending. I can see that it will be a bit more complicated because when you toggle the nav menu it is not just toggling a class one single element (like the core themes do) but rather on several elements. Namely, when you click the menu it is toggling an `active` class on:

* `html`
* `body`
* `nav.site-bar`
* `.site-overlay`

It seems better if the theme's CSS were rewritten to only require toggling the `active` class on the root `html` element. Then instead of having a `.site-navbar.active` selector there could be a `html.active .site-navbar` selector.

Even without this being done, you could implement the toggle with your existing theme if you use  the patch from https://github.com/ampproject/amp-wp/pull/2327 applied (see [ZIP on PR](https://github.com/ampproject/amp-wp/pull/2327#issuecomment-495299003)), using this code plugin code:

```php

add_action(
	'after_setup_theme',
	function() {
		add_theme_support(
			'amp',
			array(
				'paired' => true,
				'nav_menu_toggle'   => array(
					'nav_container_xpath'        => '//html',
					'nav_container_toggle_class' => 'active',
					'menu_button_xpath'          => '//a[ contains( @class, "site-nav-trigger" ) ]',
				),
			)
		);
	}
);

add_action(
	'wp_enqueue_scripts',
	function () {
		wp_add_inline_style(
			'orbital-style',
			'
			@media (max-width: 1040px) {
				html.active body {
					width: 100%
				}
				html.active .site-navbar {
					-webkit-transform: translateX(0);
					transform: translateX(0)
				}
			
				html.active .site-overlay {
					opacity: 0.75;
					position: fixed;
					height: 100%;
					width: 100%;
					top: 0;
					background: #000000;
					display: block;
					z-index: 10
				}
			}
			'
		);
	},
	11
);
add_filter(
	'amp_content_sanitizers',
	function ( $sanitizers ) {
		class Orbital_Site_Overlay_Menu_Collapser extends AMP_Base_Sanitizer {
			function sanitize() {
				$xpath   = new DOMXPath( $this->dom );
				$overlay = $xpath->query( '//div[ contains( @class, "site-overlay" ) ]' )->item( 0 );
				if ( $overlay ) {
					$overlay->setAttribute( 'on', 'tap:AMP.setState({ navMenuToggledOn: false })' );
					$overlay->setAttribute( 'role', 'button' );
					$overlay->setAttribute( 'tabindex', '-1' );
				}
			}
		}
		$sanitizers['Orbital_Site_Overlay_Menu_Collapser'] = [];
		return $sanitizers;
	}
);
```

**Comment by westonruter** [comment]
Ideally the theme would ship with that `add_theme_support()` call, the fix to the CSS, and the `.site-overlay` would get those attributes added when `is_amp_endpoint()`. The direct use of sanitizers should be left as a last resort.
