### ISSUE TITLE
Native mode doesn't have the AMP's symbol on SERP

### ISSUE THREAD

**Issue by zJar84** [ampproject/amp-wp#2418]
Hello, I am using the Native mode on my web and I see webs that use AMP and get a small symbol of AMP on the SERPs of Google on mobile. Results that this symbol doesn't appears on the SERPs of my web significadodelosgirasoles.ovh.

You can search `site:significadodelosgirasoles.ovh` on Google on mobile and see it.

It is because the web doesn't have more than one week?

Thanks.

**Comment by westonruter** [comment]
Your site is not validating: https://validator.ampproject.org/#url=https%3A%2F%2Fsignificadodelosgirasoles.ovh

The problem is that you are outputting `amp-analytics` in the `head`. It must be inside the `body`.

Actually, I'm curious why the AMP plugin is not removing this itself since it is not valid AMP. In any case, if you move it to the `body` then the validation error will be fixed.

Desktop results don't currently include badges for AMP pages.

**Comment by zJar84** [comment]
Thanks!

**Comment by westonruter** [comment]
FYI: As of #2420 if you add `amp-analytics` to the `head` it will automatically be moved to the `body`. Nevertheless, it is still best to put it in the `body` to begin with.
