### ISSUE TITLE
Google detects the AMP on Native mode as the other modes?

### ISSUE THREAD

**Issue by zJar84** [ampproject/amp-wp#2424]
Hello, I have on my web [https://significadodelosgirasoles.ovh](https://significadodelosgirasoles.ovh) (2 days on Google old) AMP integrated on Native mode, with the code of `amp-analytics` on the body and Google doesn't put the symbol of AMP on the results on mobile searchs.

Google put your page on a cache with the google.com's domain in Native mode as the same as the other modes? What is the best mode a web can has?

Thanks.

**Comment by westonruter** [comment]
You'll have to wait for Googlebot to re-crawl your site. When it does, if your AMP pages are valid (which [it is](https://validator.ampproject.org/#url=https%3A%2F%2Fsignificadodelosgirasoles.ovh%2F)), you should see the AMP badge for search results on mobile, in either Native or Transitional mode. Keep an eye on your site in [Google Search Console](https://search.google.com/search-console/) for your site's status for AMP indexing. 

Otherwise, if you still don't see it appearing in search results, then this would be a better question for a Google Search forum. See https://support.google.com/webmasters/thread/2097038?hl=en
