### ISSUE TITLE
[Feature Request] Adding a Translating Panel For Arabic sites

### ISSUE THREAD

**Issue by nakib4tech** [ampproject/amp-wp#2457]
There is RTL issue with the Arabic sites, the meta information is appearing in the English language such as " leave a comment, tags, Categories, ago". And these meta information are not aligned right.

So, Please consider adding a translating panel for these words in the next update.

Regards,
Anmar

**Comment by swissspidy** [comment]
Hi @nakib4tech, thanks for your report!

I assume you are using the Classic mode aka Reader mode on your site, correct? That's where these texts usually occur.

All these texts in the plugin can be translated on the [WordPress.org translation platform](http://translate.wordpress.org/). You can find all the translations here: https://translate.wordpress.org/projects/wp-plugins/amp/

Just like all other WordPress plugins, we rely on the support of the open source community for these translations.

Since you already seem to have a WordPress.org account, you can log in with that account and suggest translations for your locale. Arabic, Moroccan Arabic, and Algerian Arabic are currently supported by the system.

Once a translation has been suggested, translation editors (people who frequently edit translations on WordPress.org) can then approve or reject these suggestions.

For example, the string "Leave a Comment" currently has a waiting translation for Arabic: https://translate.wordpress.org/projects/wp-plugins/amp/dev/ar/default/?filters%5Bterm%5D=leave+a+comment&filters%5Buser_login%5D=&filters%5Bstatus%5D=current_or_waiting_or_fuzzy_or_untranslated&filter=Filter&sort%5Bby%5D=priority&sort%5Bhow%5D=desc

Once a plugin is 95% translated, your WordPress site can automatically download these translations via Dashboard -> Updates. When you want to use the translations already before they reach 95%, you can use a plugin like https://wordpress.org/plugins/force-update-translations/ to do so.

**Alternative:** If you want such a translation panel like you suggested, you could install a plugin like [Loco Translate](https://wordpress.org/plugins/loco-translate/) to translate these strings manually for your site.
