### ISSUE TITLE
AMP Stories plugin not working in WordPress.

### ISSUE THREAD

**Issue by MomentumAdvertising** [ampproject/amp-wp#2475]
We have version 5.2.1 of WordPress
we have downloaded AMP, Gutenberg, and AMP Stories and the AMP Stories plugin does not show up in the sidebar menu. How can this be fixed?

**Comment by westonruter** [comment]
@MomentumAdvertising what theme do you have active?

**Comment by DanielCryptoK** [comment]
Considering AMP stories is a Google Plugin I am shocked at how badly designed it is !!!

Side menu to create the stories nearly impossible to navigate, complete mess. I am trying to add a text link in the description but impossible. Also I requested that Sponsored and other link attributes added to the plugin so that affiliate links can have the correct attribute, shocking that Google not included this???

The plugin works so slowly, needs speeding up.

For accessibility text, what is suppose be put there? Am i suppose to include the text for the page there??

Try to add a text link for yourself to see how bad the design of google amp stories is.
![Edit Story ‹ Bitcoin Casino No Deposit Bonus — WordPress (2)](https://user-images.githubusercontent.com/45933242/93729277-fab1d200-fbed-11ea-918a-e99f0dc53264.png)
![Edit Story ‹ Bitcoin Casino No Deposit Bonus — WordPress (3)](https://user-images.githubusercontent.com/45933242/93729314-2af97080-fbee-11ea-8298-32e65802b23f.png)

**Comment by westonruter** [comment]
@DanielCryptoK Why are you leaving this feedback here? Please submit an issue with constructive feedback on the Web Stories plugin repo: https://github.com/google/web-stories-wp/issues
