### ISSUE TITLE
Comment form “Leave a Reply” heading misbehaves in Twenty Nineteen 

### ISSUE THREAD

**Issue by westonruter** [ampproject/amp-wp#2489]
The `#reply-title` element is not getting the correctly populated in Twenty Nineteen. It is being output as:

```html
<span [text]='commentform_post_2013.replyToName ? "Leave a Reply to " + commentform_post_2013.replyToName + "" : "Leave a Reply"'></span>
```

Notice the text content of the `span` is empty, but no value of `[text]` is empty.

In `#development=1` mode, this is generating a warning:

> `Default value () does not match first result (Leave a Reply) for <SPAN [text]="commentform_post_2013.replyToName ? "Leave a Reply to " + commentform_post_2013.replyToName + "" : "Leave a Reply"">. We recommend writing expressions with matching default values, but this can be safely ignored if intentional.`

It also exhibits a strange behavior when adding comment text to the form. 

Upon entering text:

> ![image](https://user-images.githubusercontent.com/134745/58757743-64bcda00-84c6-11e9-8743-1a386f1b389d.png)

Then hit tab to go to the Submit button, and the “Leave a Reply” heading all of a sudden appears:

> <img width="852" alt="Screen Shot 2019-06-01 at 23 42 35" src="https://user-images.githubusercontent.com/134745/58757782-f62c4c00-84c6-11e9-95ac-4e02ff616b41.png">

The problem here is that Twenty Nineteen renders its comment form via `twentynineteen_comment_form()` which does:

```php
comment_form(
	array(
		'logged_in_as' => null,
		'title_reply'  => null,
	)
);
```

In particular, the `title_reply` here is supplied as `null`. This is causing problems in the `\AMP_Theme_Support::filter_comment_form_defaults()` method which is doing the following:

https://github.com/ampproject/amp-wp/blob/3985eaef6f5c412f52b0e6eed992d19d9729b89b/includes/class-amp-theme-support.php#L1162-L1191

The problem is that `comment_form()` applies filters on `comment_form_defaults`, not on the _actual_ args passed to `comment_form()`. Therefore, we don't actually know what value for `title_reply` was passed. 

This hasn't been a problem before Twenty Nineteen because themes normally are calling `comment_form()` without any args at all.

**Comment by laurelfulford** [comment]
We're running into a similar issue in Newspack, where we have a simple plugin that lets you change the comment form text, including the "reply" header:

https://github.com/Automattic/newspack-rename-comments

The Newspack theme is also a fork of Twenty Nineteen and does have the duplicate header issue, but I'm working on removing some of that code, since it's not needed. We will still need to pass a unique title to `comment_form()`, though, which gets changed to "Leave a Reply" when you interact with the form or toggle the search.

For the short term, we can work around both by hiding and replacing that title, but if it's possible to have AMP use the title value passed to `comment_form()`, that would be awesome!

**Comment by westonruter** [comment]
@laurelfulford I've opened a PR to prevent this from happening. Please test #4388.

**Comment by westonruter** [comment]
I've also opened #4389 to redo the AMP implementation of WordPress comments so that we can achieve full feature parity.
