### ISSUE TITLE
Adding video block to story page causes error

### ISSUE THREAD

**Issue by westonruter** [ampproject/amp-wp#2517]
Adding a video as the background media for a page works fine, but adding a video block is causing an error:

> ![image](https://user-images.githubusercontent.com/134745/58998885-e909a880-87b7-11e9-8530-cd94d1c6118d.png)

Video: https://youtu.be/duoh93c6Y-0

```
TypeError: Cannot read property 'load' of null
    at t.value (index.js?ver=1559767834:14)
    at qi (react-dom.min.fa9ca8c8.js:130)
    at ui (react-dom.min.fa9ca8c8.js:133)
    at react-dom.min.fa9ca8c8.js:158
    at unstable_runWithPriority (react.min.f4c1469c.js:27)
    at Vc (react-dom.min.fa9ca8c8.js:158)
    at Sc (react-dom.min.fa9ca8c8.js:158)
    at Z (react-dom.min.fa9ca8c8.js:156)
    at Kc (react-dom.min.fa9ca8c8.js:155)
    at ya (react-dom.min.fa9ca8c8.js:153)
```

Nevertheless, if I Save Draft and reload the video block is there:

![image](https://user-images.githubusercontent.com/134745/58999063-c1671000-87b8-11e9-9717-cc3bfd5fc4b8.png)

**Comment by swissspidy** [comment]
I cannot really reproduce this, at least not consistently. The only warning I got was this:

```
Warning: Cannot update during an existing state transition (such as within `render`). Render methods should be a pure function of props and state.
```

**Comment by westonruter** [comment]
@swissspidy Even when inserting this video on the story-test env? Could it be because it has the featured image assigned?

**Comment by swissspidy** [comment]
Oh, I think I found the issue.

In 2a430d4b19dc13bda3408f2ee987c485db3c4c7a we changed the code so that a video's featured image would be automatically added as a poster if it exists.

In Gutenberg there's some special logic when the poster image changes to (re)load the video:

https://github.com/WordPress/gutenberg/blob/ff70de60086e8f505de51a9f9883d77bf5eda119/packages/block-library/src/video/edit.js#L84-L86

Now, by the time we update the block attributes (which happens quite fast), `this.videoPlayer.current` is still `null`, causing this error.

**Comment by kienstra** [comment]
**Testing Steps**

Hi @csossi,
Hope you're having a great day. Could you test this please?

1. Create a new story
2. Add a "Video" block
3. Select a video for it
4. Go to the JS console in the developer tools
5. Expected: there's no error like the one [shown above](https://github.com/ampproject/amp-wp/issues/2517#issue-452778347):

```
TypeError: Cannot read property 'load' of null
```

**Comment by csossi** [comment]
Verified in QA
