### ISSUE TITLE
Allow reordering of pages by dragging the carousel indicators

### ISSUE THREAD

**Issue by swissspidy** [ampproject/amp-wp#2525]
Underneath the pages there are little bars for every page in the story.

For faster creation of stories it could be useful to be able to quickly reorder pages by dragging around these editor carousel indicators.

**Comment by swissspidy** [comment]
For reference, #2910 was a previous attempt at this.

**Comment by miina** [comment]
Starting looking into this.

**Comment by miina** [comment]
Any thoughts on if / how to make it more understandable where to is the reordered page being moved? E.g. perhaps displaying small Page numbers on each indicator while dragging is happening?

![reordering-carousel](https://user-images.githubusercontent.com/3294597/65621708-8a657600-dfc4-11e9-9330-a45c3f7bd7ef.gif)

cc @cathibosco @swissspidy

**Comment by swissspidy** [comment]
You mean showing the page numbers below _all_ indicators while an element is being dragged? That could work.

**Comment by miina** [comment]
Thoughts, @swissspidy? 

![with-numbers](https://user-images.githubusercontent.com/3294597/65762899-661fab80-e122-11e9-81b6-b74096c6723c.gif)

I wonder if it might make sense to always display the numbers instead since it can get confusing with multiple pages, e.g.:

<img width="482" alt="Screenshot 2019-09-27 at 12 32 42" src="https://user-images.githubusercontent.com/3294597/65763108-ef36e280-e122-11e9-917c-46afcc2b5f79.png">

Not sure. @cathibosco any thoughts? Perhaps there's a better alternative.

**Comment by cathibosco** [comment]
@miina Based on the mockups above, I do think it makes sense to have the number displayed for the page sequence... 
It also makes sense to have them always display (rather than to display only on drag action) based on the UX of the editor currently. 
Of the two mockups ups above: I think the position of the number in this mock up is the most useful. 
![65762899-661fab80-e122-11e9-81b6-b74096c6723c](https://user-images.githubusercontent.com/4819761/65880831-6e652a00-e360-11e9-94f3-51a939d88d40.gif)


Note: As the user selects the page to move or work on, the bar or page indicator gets highlighted - perhaps the number could also become a darker color or bold to highlight as well.

**Comment by miina** [comment]
Screencast: https://www.dropbox.com/s/fbwwj1uky3shhm5/reordering_carousel.mp4?dl=0

**Comment by miina** [comment]
Instructions for testing:
- Add a few pages
- Verify that the pages have page numbers displayed in the carousel below
- Verify that it's possible to reorder the pages by dragging the carousel indicators (and that they are moved to the correct location).

**Comment by barklund** [comment]
> Am unable to drag the bars along the bottom successfully - pages above aren't changing position

Yes, there's a bug for it in #3464.

**Comment by miina** [comment]
Looks like #3412 (using hooks where possible) caused this regression. _Looking into this_

**Comment by miina** [comment]
Ok, looks like #3412 removed the `DropZoneProvider`, assuming that unintentionally and will add it back.
