### ISSUE TITLE
Insert blank pages in a fully 'blank' state

### ISSUE THREAD

**Issue by amedina** [ampproject/amp-wp#2541]
Currently when a new page is created, it is inserted into the story as a blank page with a text box in it. 

Usually the creation flow is to add an asset to the page first and then add the text. By having a text box inserted from the start, it forces the user to either type some text, then add a background image/color/video, and then go back to the text to edit it and configure it. It would be better to insert blank pages totally blank, and let the user decide on the order she wants to insert the components of the page. 

/cc @pbakaus

**Comment by pbakaus** [comment]
I think that makes sense!

For what it's worth though, I don't think the shortcuts on the top in the top bar for text and image are very accessible – they're tiny icons, next to other icons I don't understand (if I'm not familiar with Gutenberg), and don't even have a label.

If we implement this change, it would be good to invest into making it super easy to discover what you can do, at first glance.

**Comment by swissspidy** [comment]
> If we implement this change, it would be good to invest into making it super easy to discover what you can do, at first glance.

Absolutely, that‘s a requirement. If there is just a blank sheet you have no idea what you should do next.

That‘s the whole reason why the regular Gutenberg editor has all these placeholders. Because a blank canvas is the worst place to start from as a user.

I don‘t yet see a way to communicate this to the user without having an actionable item like a text block. I highly doubt that the first thing you want to do is add a background image instead of some text.

———-

As for the shortcuts, let‘s create a separate issue to track possible improvements there. Ideally after some user testing.

**Comment by amedina** [comment]
> Absolutely, that‘s a requirement. If there is just a blank sheet you have no idea what you should do next.

Agree that guidance is needed. But having a Text block is arbitrary and still does not tell users anything about what to do after the Text box has been filled. 

Perhaps this can be addressed by some tooltip or similar mechanism that tells the user "Add a page element...", or something along those lines.

**Comment by swissspidy** [comment]
We also have #2427 which is about guidance and NUX. There i suggested using the same tips and guides as in the regular block editor. They look a bit like this:

![39301491-254981a4-4947-11e8-93ff-fbbd4819d9ed](https://user-images.githubusercontent.com/841956/59146448-63bc0900-89ee-11e9-9365-d29fd57674c1.png)

**Comment by amedina** [comment]
Yeah; I'd like that. Those notices are sleek and very useful.

**Comment by csossi** [comment]
Verified in QA

1st page has a text block - all subsequent are blank
