### ISSUE TITLE
Consider listing background media in block navigation

### ISSUE THREAD

**Issue by swissspidy** [ampproject/amp-wp#2627]
Screenshot:

<img width="1518" alt="Screen Shot 2019-06-13 at 5 09 32 PM" src="https://user-images.githubusercontent.com/841956/59497115-11b63000-8e93-11e9-80ce-74a2e0d50bf7.png">

Related: #2564

**Comment by miina** [comment]
Maybe we should just rename the "elements" to "blocks"? The background image behaves quite differently and its order isn't changeable as in case of other blocks, not sure if it would make sense to add it to the block navigation separately. Are you thinking of adding this since otherwise, it's weird that there are no elements added but it shows a background image? In this case, it might be the same case for the background gradient as well. Not sure if either would make sense 🤷‍♀ Thoughts?

**Comment by swissspidy** [comment]
Note that we changed the naming from blocks to elements on purpose, see #2522.

IIRC I opened this issue here after some feedback from Alberto on Slack.

Personally I am still a bit on the fence about this possible enhancement. I guess we'd need some more user feedback here.

> Are you thinking of adding this since otherwise, it's weird that there are no elements added but it shows a background image?

Yeah I think that is the reason.

> In this case, it might be the same case for the background gradient as well.

Sticking with the elements terminology, I'd say an image is more of an element in that case than a gradient.

**Comment by miina** [comment]
> Sticking with the elements terminology, I'd say an image is more of an element in that case than a gradient.

Yep, I was thinking of that, too, but at the same time, the gradient has its own element, too (a grid layer).

 > I guess we'd need some more user feedback here.

That would be good 👍

**Comment by swissspidy** [comment]
Related: #2699
