### ISSUE TITLE
Thumbnails have low quality on AMP pages

### ISSUE THREAD

**Issue by zJar84** [ampproject/amp-wp#2687]
Hello, I'm using the transitional mode of the AMP plugin and my page is using miniatures. The problem is that those miniatures look really bad on the AMP version of the page.

If you scroll down until the h2 "Otras recetas bajas en grasa y colesterol" you can see the images in normal mode and in AMP mode.

What can I do for see the miniatures on AMP page exactly like the miniatures on Non-AMP page?

Thanks!

Page: https://comidassingrasa.ovh/
AMP Page: https://comidassingrasa.ovh/?amp

**Comment by swissspidy** [comment]
Hi there and thanks for your report!

Looking at your site, you seem to be using a plugin or theme that uses some lazy loading technique. It does so by first displaying the low resolution images and then loading the higher resolution images using JavaScript.

You can see the same behavior when opening https://comidassingrasa.ovh/ with JavaScript disabled.

Since AMP uses `amp-img` for images, which already handles lazy loading automatically, there is no need for you to handle this on your own.

I recommend trying to disable any lazy load plugin or any option in your theme that does this.

Since you are using Transitional mode, there might be a way to disable it only for AMP pages. However, for this we might need to see the actual code responsible for it. If that's not possible, ideally you can report this to the plugin/theme developer to request this bug fix.

**Comment by zJar84** [comment]
Oh thanks! It was caused by the lazy load.
