### ISSUE TITLE
Improve logic when AMP cannot be enabled or disabled

### ISSUE THREAD

**Issue by swissspidy** [ampproject/amp-wp#2724]
I am opening this based on discussion on #2692 to look at the error messages as a whole.

There was a valid point made that the `AMP cannot be enabled because this post type does not support it` message is a bit confusing when AMP support has been deliberately turned off for the post type. The message is shown for _all_ users, not just admins.
As a regular author, I don't necessarily know what AMP is, nor should I need to know. It should "just work". Having a non-actionable notice there doesn't make sense.

It's the same when a theme explicitly declares AMP support, as you get a `Your site does not allow AMP to be disabled` warning in that case and there's nothing you can do. As a user, I would not want to see any message at all there.

----

Related: #2702.

**Comment by westonruter** [comment]
> It's the same when a theme explicitly declares AMP support, as you get a `Your site does not allow AMP to be disabled` warning in that case and there's nothing you can do. As a user, I would not want to see any message at all there.

To clarify, this is when a theme is configured to force AMP to be enabled using the `available_callback` theme support arg:

```php
add_theme_support( 
	'amp', 
	[
		'available_callback' => '__return_true',
	]
);
```

This is actually deprecated and if you use it you get a `_doing_it_wrong()` and this notice:

![image](https://user-images.githubusercontent.com/134745/60771031-9c570d00-a096-11e9-966a-fe18964f9195.png)

Otherwise, the way to make support for a template immutable is via the `amp_supportable_templates` filter:

```php
add_filter( 'amp_supportable_templates', function( $supportable_templates ) {
	$supportable_templates['is_singular']['supported'] = true;
	$supportable_templates['is_singular']['immutable'] = true;
	return $supportable_templates;
} );
```

(Aside: With this I expected the checkbox to be `disabled` for the Singular template, but it is not.)

I also somewhat doubt anyone has actually used this feature of the plugin. Nevertheless, I just realized that this is basically what I described in #2314, having forgotten about the immutable templates.

**Comment by swissspidy** [comment]
> To clarify, this is when a theme is configured to force AMP to be enabled using the available_callback theme support arg:

Uhm that's not what I see on my site. In my theme I use this to add theme support:

```php
add_theme_support(
		'amp',
		[
			'paired'              => true,
			'templates_supported' => 'all',
			'comments_live_list'  => true,
		]
	);
```

And I still get the warning in the block editor that I cannot disable AMP.

**Comment by westonruter** [comment]
Good catch. I missed that one! Then `'templates_supported' => 'all'` theme support flag causes this to appear in the admin screen:

![image](https://user-images.githubusercontent.com/134745/60829966-0b9e3100-a16b-11e9-9273-600ebfc1b567.png)

It also seems that this is _wrong_. It doesn't make any sense for a theme that supports _paired_ mode to also _require_ that all templates support AMP, since paired AMP entails that all templates do _not_ require AMP. So this should only be enforced when Standard mode is selected.

**Comment by westonruter** [comment]
After thinking about this more, I think we need to eliminate `templates_supported` entirely. It turns out to not even be enforced right now because you can still have a site with `'templates_supported' => 'all'` which also is in Transitional (`paired`) mode. The original intention of this theme support flag (as demonstrated in #1864) is to _prevent_ a user from turning off AMP, with the goal of preventing a site with a theme that depends on AMP from entering a broken state where the theme uses AMP components but the AMP plugin doesn't do its post-processing. But again, this is not the case currently because a site can be switched to Transitional mode and all templates will be servable as non-AMP anyway.

@swissspidy Does this make sense to you?

**Comment by westonruter** [comment]
On a related note: I think that `paired => true` should be the default when `add_theme_support('amp')` is added because, again, the reality is that all themes need to support when AMP is on or off.

I think the `paired` flag is actually of extremely little value. At best it is a signal for which mode a theme prefers to be in. But the user can always override. We should consider removing it as well.

**Comment by amedina** [comment]
This is an important change, making the plugin more user-centric by minimizing the surface touch points on programmatic access.

**Comment by schlessera** [comment]
**QA passed**

Tested various combinations in both the Gutenberg editor:

![Image 2020-07-16 at 12 48 37 PM](https://user-images.githubusercontent.com/83631/87662590-b6740280-c762-11ea-86b9-3f39a20b86c9.png)

... as well as the Classic editor:

![Image 2020-07-16 at 12 48 22 PM](https://user-images.githubusercontent.com/83631/87662617-c12e9780-c762-11ea-9686-672d8e74a17a.png)
