### ISSUE TITLE
Error message: "this block contains unexpected or invalid content"

### ISSUE THREAD

**Issue by vinaymahag** [ampproject/amp-wp#2734]
Repro steps:

1. I created a story last week
1. My role was changed from author to editor (not sure if this step is required to repro)
1. I opened the story today, and I see the following error messages.
![image](https://user-images.githubusercontent.com/38660603/60518770-2c204400-9cb0-11e9-84da-e0db1fa5dcde.png)

**Comment by swissspidy** [comment]
Related: #2728, #2685.

Pretty sure this is because of the author role.

Reason:

When saving a story as an author, WordPress currently strips some of the HTML and CSS because of security reasons (we're working on fixing that!).
Then, when opening the story again, the editor complains that the block is invalid because of the malformed HTML.

**Comment by vinaymahag** [comment]
When I clicked "Resolve", it displayed a blank page, effectively deleting the previously saved story.

**Comment by westonruter** [comment]
The block resolution can be seen here: https://story-test-wordpress-amp.pantheonsite.io/wp-admin/revision.php?revision=2444

![image](https://user-images.githubusercontent.com/134745/60519539-9cbb6680-9c98-11e9-9634-f77ac56f00d0.png)

Now that you are an Editor I would hope that you could restore to the previously-saved revision from 5 days ago and that there shouldn't be the same issue.
