### ISSUE TITLE
Assets missing from template

### ISSUE THREAD

**Issue by ithinkihaveacat** [ampproject/amp-wp#2756]
Some (?) templates seem to be missing assets when selected:

<img width="768" alt="Screenshot 2019-07-05 at 15 49 18" src="https://user-images.githubusercontent.com/51244/60809269-31830000-a182-11e9-8440-47e9f99b0207.png">

Reproduce:

1. Select AMP Story template with text "Add Story title…"

Actual:

1. Template appears as shown, without background, and style (e.g. red box around "spoilers alert").

Expected:

1. Template looks almost exactly the same in the editor as in the screenshot.

(Note: perhaps this is intentional/necessary for some reason, but from a user point of view it's a bit unexpected.)

This is maybe related to #2289 (but seems like the opposite problem?).

**Comment by swissspidy** [comment]
Thanks for testing @ithinkihaveacat!

This was actually implemented on purpose. The reason is that upon template insertion it's most likely that you want to use different images and colors. However, they're still in the preview to give you a sense of how it could look like.

#2289 was an issue that we opened to re-evaluate this, because we haven't found a true consensus on this. We'll probably end up implementing both options in some way, giving users the choice over the template insertion.
