### ISSUE TITLE
Font preview does not match actual font

### ISSUE THREAD

**Issue by ithinkihaveacat** [ampproject/amp-wp#2757]
The selected font doesn't seem to 100% match the preview? (Preview makes it look like the font is an outline font, but when embedded in the story it's not.)

<img width="997" alt="Screenshot 2019-07-05 at 15 53 25" src="https://user-images.githubusercontent.com/51244/60809704-2f6d7100-a183-11e9-9b82-0c81a0ed77a1.png">

**Comment by swissspidy** [comment]
Thanks, that's a good point.

To give a little background to this: for performance reasons, the editor uses SVGs of the fonts instead of loading the actual font. It's entirely accurate that the SVG needs some further tweaking.

**Comment by swissspidy** [comment]
Absolutely. In fact, we already scheduled font improvements for this current sprint:

* #3026 - Including more fonts from Google Fonts
* #3027 - Use a searchable dropdown for the font picker
* #3028 - Automatically create these preview SVGS or alternatively actually load them (in a performant way) to have a more accurate presentation

Since especially #3028 covers this, I am closing this issue here as a duplicate. 

@ithinkihaveacat @vinaymahag Please follow that issue for progress on this matter.
