### ISSUE TITLE
Photo editor UI is a bit confusing

### ISSUE THREAD

**Issue by ithinkihaveacat** [ampproject/amp-wp#2760]
Just some UI feedback, but in my experience, the photo resize tool behaves a bit unexpectedly. It's possible to drag the image not only out of bounds of a page, but also sort of across multiple pages. (It's cropped to the boundaries of a page when published/previewed, but still a bit strange.) Also the way scaling a cropping works is a bit unexpected--in certain cases you can do both at the same time, via the same control.

Video here:

https://photos.app.goo.gl/xdciHqGAVSKSxv5j6

**Comment by ithinkihaveacat** [comment]
Related, it's very easy to position block outside the bounds of the page. This might be intentional but it's a bit weird (especially since they can be positioned over _other_ pages):

<img width="905" alt="Screenshot 2019-07-05 at 16 54 44" src="https://user-images.githubusercontent.com/51244/60811078-7315aa00-a186-11e9-8ef5-6e47a4c3b8ec.png">

**Comment by miina** [comment]
Positioning elements (partly) outside of a Page was intentional indeed since some other tools allow going over the borders, however, we should handle this better, e.g. not allow dragging an element fully out of the Page's borders and definitely not allowing positioning an element on another Page. One option could potentially be allowing X% go over the borders.
