### ISSUE TITLE
Re-evaluate maximum image size in stories

### ISSUE THREAD

**Issue by swissspidy** [ampproject/amp-wp#2835]
_Based on a [discussion in the AMP Slack workspace](https://amphtml.slack.com/archives/C9ARUE6Q6/p1561810803118000) (link needs [registration](https://bit.ly/amp-slack-signup))_

In the Stories editor we currently limit images to a maximum height of 1440px, while the official recommendation is 720p for image and video assets.

The conclusion from the discussion was that it might be worth experimenting with those values where possible and seeing how they impact performance in practice.

**Comment by westonruter** [comment]
Copying the conversation here to extract from Slack:

![is it a good rule of thumb to constrain images to a max height (resolution) of 1440px in Stories? When an image is being used as fill for a story page in either portrait or landscape, should it never have more than 1440 pixels in height? ](https://user-images.githubusercontent.com/134745/61474539-b8cc3280-a93d-11e9-8d0d-f34da09a2c16.png)

![sorry I was out for quite some time.  I think it’s fine for tools to be opinionated about what is performant.  1440px seems reasonable to me; the only cases that would fail that is someone operating at almost 4k resolution at 1x.  It’s especially okay for tools to do this since you can change this at any time (though old stories won’t get updated) ¶ Our official recommendation is 720p for image and video assets, but if it’s for full-bleed landscape, maybe you could do more.  Are you able to tell on the tooling side what they’re using the assets for? ¶ Yes, we can tell what they are using the images for. The 1440px height here is basically a fallback in cases where we can't figure it out. So the Photon module of Jetpack can use this 1440px maxheight to prevent images from ever having a greater vertical resolution than that. ¶ And the 1440px is what we use as vertical resolution for images inserted as the full bleed page background images. ¶ But maybe we should be using 720px max instead? ¶ Or media query to switch between 720 and 1440? ¶ Hmm, yeah, I don’t have all the data, but it might be worth even experimenting with those values where possible and seeing how they impact performance in practice](https://user-images.githubusercontent.com/134745/61474565-c8e41200-a93d-11e9-8f2f-a4584038966d.png)

**Comment by westonruter** [comment]
@newmuis Where is official recommendation located for the vertical resolution?

I see 720px as the _horizontal_ recommendation for [poster images](https://amp.dev/documentation/guides-and-tutorials/develop/amp_story_best_practices/#specify-a-poster-attribute):

> The recommended dimensions for a poster image are: 720p (720w x 1280h) .

But this is 1280px high not 720px.

**Comment by westonruter** [comment]
@swisspidy Should change the dimensions of the image size to be 1280h instead of 1440h? Then we should do the same for Photon: https://github.com/Automattic/jetpack/pull/12821

**Comment by swissspidy** [comment]
Hmm would be good to be aligned with the official recommendations. But that means changing the existing image size, which seems like quite a big change for existing content.

Note: This came up in #2881 as well.

**Comment by westonruter** [comment]
Looking at some desktop stories, and the vertical resolutions of images:

* 1189h: https://www.washingtonpost.com/graphics/2019/world/amp-stories/hong-kong-protests/?noredirect=on
* 1313h: https://www.washingtonpost.com/graphics/2019/world/amp-stories/hong-kong-protests/?noredirect=on (page 12)
* 1433h: https://www.washingtonpost.com/graphics/2019/world/amp-stories/hong-kong-protests/?noredirect=on (page 13)
* 1200h: https://www.washingtonpost.com/graphics/2019/world/amp-stories/hong-kong-protests/?noredirect=on (page 16)
* 1468h: https://www.washingtonpost.com/graphics/2018/world/amp-stories/photos-of-war-in-yemen/
* 1175h: https://projects-sfchronicle-com.cdn.ampproject.org/c/s/projects.sfchronicle.com/2019/visuals/camp-fire-ballet/
* 1175h: https://www-washingtonpost-com.cdn.ampproject.org/c/s/www.washingtonpost.com/graphics/2019/national/amp-stories/2019-state-of-the-union-reactions/

These all look fine on a display with 3360x1890, though they could look even better on desktop if they had a higher on desktop. Nevertheless, if we capped the vertical resolution to 1280px then the WordPress editor should be generating stories similar in visual quality to the above.

I think what we should do is:

1. Change the current page image size from 1440h to 1280h.
2. Replace the current `<amp-img>` in the save function with an `<img>` as normally done in WordPress, but retaining `layout=fill` and being sure to _add_ the `wp-image-{$attachment_id}` class. This will then allow for `wp_make_content_images_responsive()` to process the images and inject the `srcset`. The image sanitizer will then convert this to `amp-img` automatically. (The Jetpack PR would not be required to process `<amp-img>`, though it still should.)
3. Consider adding a new image size for desktop which has a vertical resolution of 1800px, which should automatically be included among the `srcset` and used when the screen allows for it.

Note that step 2 will deprecate the `amp-story-page` block.

**Comment by newmuis** [comment]
Sorry @westonruter that I'm just seeing this now.  To clarify, do we have a "soft" cap (beyond which we issue a warning), a "hard" cap (beyond which we do not allow assets to surface, either by downsampling them or by outright rejecting the upload), or both?

**Comment by westonruter** [comment]
@newmuis It's more about what will produce the best results, and what the recommendations are. We currently have a max height of 1440px for images, and this was apparently a doubling of the 720px number… which is actually for the width. So actually the height of images should be set to 1280px for mobile. With this in place, another larger image size (e.g. 1800px high) could be also generated for larger displays when requested via `srcset`. Does this seem reasonable?

**Comment by newmuis** [comment]
Sounds good to me, with the caveat that `srcset` is explicitly about the size of the browser window rather than the size of the `amp-story-page`; is this only for the full-bleed desktop?

**Comment by westonruter** [comment]
I think it would be the same on desktop whether the story `supports-landscape` or not, right? If on a display that is 1800px tall, then if the story is displayed full-bleed or not in both cases the image with more vertical resolution should be used.

**Comment by swissspidy** [comment]
**Testing instructions**

1. Create new story
2. Upload large image as page background
3. Preview story
4. Verify that in the source code the img has a `srcset` and an `alt` attribute
5. Verify that template insertion still works as usual

**Comment by csossi** [comment]
Verified in QA
