### ISSUE TITLE
Strip HTML comments in AMP output

### ISSUE THREAD

**Issue by swissspidy** [ampproject/amp-wp#2842]
_This was something that was suggested in the [support forums](https://wordpress.org/support/topic/post-processor-cache-keeping-getting-disabled/#post-11743847)_

Currently, the AMP plugin warns you when there's randomly generated content on a page. That doesn't work well with the post-processor cache.

In the case from the support forums, that randomly generated content was likely due to some HTML comments. Now the question is whether random content in HTML comments can be ignored for this purpose, e.g. by simply removing any HTML comments from the source code. That would make the cache logic more robust.

**Comment by westonruter** [comment]
A problem with stripping the comments is that we'd need to restore them after post-processing. Also, the removal would need to be suspended when doing validation because comments are how invalid markup is attributed to plugins/themes. 

We may also need to consider whether the post processor is just not robust enough of an idea to be feasible and if it should be yanked. Better to have someone rely on a page cache.

**Comment by westonruter** [comment]
See also https://github.com/ampproject/amp-wp/issues/2694#issuecomment-506967997

**Comment by akkiverma** [comment]
Is there any way, any hack using which I may strip off the HTML comments for now?

**Comment by westonruter** [comment]
@akkiverma Where are the comments coming from in your case?

**Comment by westonruter** [comment]
Closing in favor of #4455.
