### ISSUE TITLE
Allow users to see blocks snap to position (vertical and horizontal) when rotating.

### ISSUE THREAD

**Issue by MackenzieHartung** [ampproject/amp-wp#2876]
As a user I want a block to snap at quarter angles when I am rotating it.

AC1: When rotating a block, at each quarter angle it should snap into place to allow the user to achieve perfect alignment with the angle.

**Comment by swissspidy** [comment]
While I haven't seen this being done for rotation so far in a React component, perhaps we can learn something from #2875.

Also, I wonder if it would help adding a rotation range control to the block sidebar, to help further tweak the the radius. For example, when you want to use a 45 or 60 degrees angle for every block.

Perhaps we should snap at 45 degrees too.

**Comment by swissspidy** [comment]
Will add testing instructions after deploying to the test environment

**Comment by westonruter** [comment]
Question: what if I want to rotate between two snap points? For example, I could have some image that I want to “perfectly” align (responsive issues notwithstanding) the text with some feature in the image.

**Comment by swissspidy** [comment]
I see two options:

1. Add a range control to the sidebar to fine-tune the rotation
2. Adjust snap gap so there's more room between snap targets

Only the first one will allow for full control though.

cc @miina @kienstra 

Thoguhts?

**Comment by miina** [comment]
Hmm, lowering the snap gap might make the snapping not noticeable enough, perhaps if we'd change it just a little bit (e.g from 10 to 8).

One option could be reducing the number of snap targets, e.g. having the snap targets only after every 45 degrees (`-180, -135, -90, -45, 0, 45, 90, 135, 180`). This way the main degrees would still be covered but it would leave the area between larger where the user could position it as they'd like.

Or perhaps that's what you meant as well, @swissspidy? I thought initially that you were thinking of changing the `BLOCK_ROTATION_SNAP_GAP`.

Thoughts?

**Comment by miina** [comment]
For aligning perfectly we'd still need a range control. An alternative could be allowing switching snapping off but perhaps the range control would make more sense.

**Comment by westonruter** [comment]
What if the block had a toggle in the block inspector for whether it should snap to grid?

**Comment by miina** [comment]
> What if the block had a toggle in the block inspector for whether it should snap to grid?

That's kind of what I was thinking of with "switching snapping off".

Wasn't sure about this since maybe this shouldn't be a block setting -- would it make sense to save the setting value block-based if snapping should be off for that specific block?

Perhaps a setting in the editor which would be saved as a general setting could make more sense? Toggling this value wouldn't have an effect on the already saved values.

Maybe this would also be good for the case where the user generally prefers editing without snapping, for the future snapping features as well (grid snapping)?

**Comment by westonruter** [comment]
I think it makes more sense on the block level. I can imagine it would be the exception rather than the rule to have snapping. It would only be for the one-off block that you'd want to disable the snapping.

**Comment by miina** [comment]
> I can imagine it would be the exception rather than the rule to have snapping.

The user could just turn it on right away for editing the next block, it should definitely be an easily accessible toggle setting if it's general. Something like a "mode", e.g. "Snapping mode on/off" toggle. Are you thinking that it would be better on the block level since otherwise, the extra general toggle setting would be unnecessary "noise" in most cases?

> I think it makes more sense on the block level.

It just wouldn't necessarily feel ideal that we'd extend all the existing blocks to add an extra setting even though its value is not relevant for displaying the block in the FE / for the content.

In this sense adding a block setting where the user could change the rotation degrees (e.g. a range control as Pascal mentioned) could make more sense to me since that's a value that we're using and that needs saving as a block setting. This, however, would be less user-friendly.

**Comment by westonruter** [comment]
I don't feel strongly either way. Having a global toggle would work, but a user may be concerned that re-enabling snapping could destroy previous non-snapped rotations.

**Comment by swissspidy** [comment]
> It just wouldn't necessarily feel ideal that we'd extend all the existing blocks to add an extra setting 

I'd certainly not want to save any such choice as a block attribute at all.

As for a local setting that only works for the current block, what about disabling snapping when the user holds down, say, the <kbd>CMD</kbd> key? That should be possible to implement. However, it would also mean we'd need to have the same functionality for the upcoming snapping enhancements.

> Something like a "mode", e.g. "Snapping mode on/off" toggle

I like the idea of having a global "Snapping mode on/off"  toggle in the "More tools & options" menu, especially in the future with more snapping features:

![Screenshot 2019-08-12 at 20 01 38](https://user-images.githubusercontent.com/841956/62886740-0882fb80-bd3c-11e9-8937-7c97f22d4d50.png)

With good labelling I don't think it would be confusing, although only usability testing will tell.

---- 

So my suggestion would be:

1. Add range control to the block sidebar.
2. Add global "Snapping mode on/off"  toggle as well as <kbd>CMD</kbd> key support in the future as part of the [block snapping enhancements](https://github.com/ampproject/amp-wp/issues/2875#issuecomment-519550459).

**Comment by swissspidy** [comment]
**Testing instructions**

1. Add new text block
2. Rotate it
3. Verify that during rotation it snaps at certain angles, making it easier to rotate it nicely at e.g. 90 or 180 degrees

**Comment by csossi** [comment]
Verified in QA
