### ISSUE TITLE
Allow plugins to add metadata to AMP Stories

### ISSUE THREAD

**Issue by cathibosco** [ampproject/amp-wp#2968]
- I am optimizing my Story for **Search** & for **Social** using the Yoast plugin

- When I publish a Story, it IS being crawled and being added to Search results when I optimize with the Yoast plugin. ✅ 
- However, when I add my story to Slack or Social (Social/Share), it is not fetching the image or description. We think this is a bug. 😐

**Comment by westonruter** [comment]
Please share the URL of the story.

**Comment by cathibosco** [comment]
Here is a link to an experimental story that was published... thanks!
https://cathibosco.com/stories/nikko/

**Comment by westonruter** [comment]
The Schema.org metadata is:

```json
{
    "@context": "http://schema.org",
    "@type": "BlogPosting",
    "author": {
        "@type": "Person",
        "name": "Cathi Bosco"
    },
    "dateModified": "2019-08-06T17:16:35+00:00",
    "datePublished": "2019-06-24T13:40:57+00:00",
    "headline": "Nikk\u014d T\u014dsh\u014d-g\u016b, Japan",
    "image": {
        "@type": "ImageObject",
        "height": 1600,
        "url": "https://cathibosco.com/wp-content/uploads/2019/06/Nikko-FI-cathi-bosco-1.png",
        "width": 1200
    },
    "mainEntityOfPage": "https://cathibosco.com/stories/nikko/",
    "publisher": {
        "@type": "Organization",
        "logo": {
            "@type": "ImageObject",
            "height": 1,
            "url": "https://cathibosco.com/wp-content/uploads/2019/01/cathibosco-design-logo-ux-design-leader.svg",
            "width": 1
        },
        "name": "Design + Business + Technology = UX Awesome!"
    }
}
```

For Google Search, I can see there is an error with the publisher logo image: the SVG format is not allowed.

![image](https://user-images.githubusercontent.com/134745/62665548-84440900-b934-11e9-98f8-3b1e52156b24.png)

See https://search.google.com/structured-data/testing-tool#url=https%3A%2F%2Fcathibosco.com%2Fstories%2Fnikko%2F

Now, Slack and other social providers are a different… story.

It appears Slack only supports Twitter and Facebook meta: https://api.slack.com/docs/message-link-unfurling#classic_unfurling

These would normally be added by Jetpack or Yoast, but in the AMP Story template ([`single-amp_story.php`](https://github.com/ampproject/amp-wp/blob/develop/includes/templates/single-amp_story.php)) we do not invoke `wp_head()` in order to prevent arbitrary theme/plugin code from interfering with the story format.

One option would be to manually create the Twitter and Facebook meta ourselves, but this would reinvent the wheel. We should rather rely on Jetpack or Yoast to do this.

Probably what we should do here is introduce a new `amp_story_head` action which such plugins can use to target the injection of AMP markup into this template. This would be similar to how WordPress has an [`embed_head` action](https://github.com/WordPress/wordpress-develop/blob/98642e4893cb06f69f9393b073e1896360a7f560/src/wp-includes/theme-compat/header-embed.php#L23-L30) which fires in the Post Embed template.

While doing this, we can remove hard-coded `head` code:

https://github.com/ampproject/amp-wp/blob/d2971f2b8752ac88919f1d18c155f13c720d0e51/includes/templates/single-amp_story.php#L15-L24

And we can instead hook into this `amp_story_head` action instead. Then Jetpack or Yoast could output their own Schema.org metadata instead as well.

Aside: The `v0.js` and AMP boilerplate style should really be getting injected by the post-processor anyway (see also #1778).

**Comment by swissspidy** [comment]
> Probably what we should do here is introduce a new amp_story_head action which such plugins can use to target the injection of AMP markup into this template.
>
> While doing this, we can remove hard-coded head code:
>
> Aside: The v0.js and AMP boilerplate style should really be getting injected by the post-processor anyway

Sounds good to me!

**Comment by westonruter** [comment]
Opened Jetpack PR to add support for this: https://github.com/Automattic/jetpack/pull/13416

**Comment by westonruter** [comment]
And support for Yoast has been drafted via https://github.com/Yoast/wordpress-seo/pull/13446
