### ISSUE TITLE
Discovery for downsampling of videos

### ISSUE THREAD

**Issue by MackenzieHartung** [ampproject/amp-wp#2984]
AC1: Look into which external tool to use to aid in downsampling of videos

**Comment by schlessera** [comment]
### Observations

* A) 3 concepts are involved:
	* __Transcoding__ - going from one format (video compression + audio compression + container format) & resolution (size + framerate) to another one
	* __Hosting__ - should be offloaded to a CDN
	* __Picking output target__ - when displaying the video, the optimal format + resolution combination for the given device should be used
* B) Output format & resolution target depends on display device & context
	* This means you cannot transcode to 1 specific resolution/format, but rather would need to transcode to a wide matrix that covers all expected display devices & resolutions instead, and then have the visitor's browser/JS player decide which one to pick.
	* This also means that building an extension point that allows for multiple providers would mean we might need to configure this matrix ourselves and keep it current to the browser/device landscape evolution, making this blow out in scope with regards to maintainability, especially.
* C) Asynchronous operation - takes minutes to hours to complete
	* This means it cannot be done in one step, but needs to include a "pending" status that displays and acts accordingly.

### Possible solutions

1. VideoPress
	* Hosted solution, with transcoding and delivery network, custom-built for WordPress
	* Supports MP4 (.mp4, .m4v), QuickTime movies (.mov), Windows Media Video (.wmv), Audio Video Interleave (.avi), MPEG (.mpg), Ogg (.ogv), 3GPP (.3gp) and 3GPP2 (.3g2).
	* Upload limit ~1.4GB
	* Included in WP.com Premium (max 13 GB) & Business (unlimited) and Jetpack Premium (unlimited) & Professional (unlimited)
	* Converts file into MP4 (H.264 & AAC lossy) and Ogg (Theora & Vorbis lossy), all optimized for progressive loading formats. 
	* Required from user:
		1. WP.com or Jetpack account that incldues VideoPress (cannot be bought independently)

2. Provider agnostic extensibility/API to hook up to a cloud service for hosting videos
	* Basic flow:
		1. User uploads video file
		2. Block is set to "pending"
		3. File is uploaded to hosting service
		4. When encoding is finished, hosting service returns URL
		5. URL to hosted video is used in block to display video
	* Required from user:
		1. Account with transcoding service (user needs to create account and provide credentials in settings screen)
		2. [Optional] Account for CDN
	* Possible providers:
		* [Cloudinary](https://cloudinary.com/solutions/video_management)
		* [Amazon Media Convert](https://aws.amazon.com/mediaconvert/)
		* [Zencoder](http://zencoder.com/)


3. Provider agnostic extensibility/API to hook up to a cloud service for transcoding and then hosting on own server
	* Basic flow:
		1. User uploads video file
		2. Block is set to "pending"
		3. File is uploaded to transcoding service
		4. Transcoding service is told which formats to generate
		5. For each finish transcoding, server downloads result to own or remote filesystem
		6. URL to local video or to CDN-hosted video is used in block
	* Required from user:
		1. Account with transcoding service (user needs to create account and provide credentials in settings screen)
		2. [Optional] Account for CDN
	* Due to B) above, would mean we need to take care of cross-browser/cross-device compatibility concerns ourselves, which might be undesirable.
	* Possible providers:
		* [Google Anvato](https://www.anvato.com/products/video-encoding-transcoding/)
		* [Amazon Elastic Transcoder](https://aws.amazon.com/elastictranscoder/)
		* [Bitmovin](https://bitmovin.com/)
		* [Encoding.com](https://encoding.com)
		* [Hybrik](https://www.hybrik.com/)
		* [Zencoder](http://zencoder.com/)
		* ...

4. Transcoding on server
	* Would be an option for DevOps-based projects, but not for the run-of-the-mill WordPress sites on shared hosting
	* Required from user:
		1. Server with necessary transcoding tools like `ffmpeg` and all codecs that are needed for the targeted format matrix
		2. [Optional] Account for CDN

5. Transcoding in client
	* Although this is technically feasible nowadays with web assembly, it will probably be a non-option due to time (browser needs to run uniterrupted) or size (entire video + at least 1 encoded version needs to fit into memory + local storage) constraints
	* Required from user:
		1. Leaving the browser window open during transcoding (potentially for hours)
		2. [Optional] Account for CDN

### Recommended Approach

Given that:

* We want this to be a drop-in solution with as little setup as possible ...
* ... that works everywhere that people run WordPress ...

I suggest going with __VideoPress (Solution 1)__ in a first iteration, with a very lightweight wrapper (action/filter-based or extensible OOP) so that it can be exchanged for something more complex on sites that are powered by dev teams.

This first iteration makes use of the already existing Jetpack/WP.com infrastructure to provide a no-friction solution, and would allows us to fine-tune the UX already while discussing more complex integrations with partners for the long run.

Preliminary set of actions/filters (rough draft for now):

* `amp_story_supports_video_uploads` - if `false`, you can only embed videos, not upload them
* `amp_story_initiate_video_upload` - the user has dragged a video file into the editor, so we can now override the default `videopress` target and let another hosting service take over
* `amp_story_video_upload_complete_callback` - the callback to notify when the upload was completed, as this operation has to be async
* `amp_story_video_url` - the URL to use for rendering the video block with an uploaded video
* `amp_story_video_html` - the complete HTML snippet to use for rendering the video block, in case the URL is not flexible enough

The default implementation could detect WP.com or Jetpack and directly tie into their VideoPress implementation to reuse their credentials. This way, there would be no additional setup needed as long as the user already meets this basic requirement.

We could also easily experiment with additional providers in separate plugins this way. It would avoid tying the official AMP plugin too much to a particular encoding solution provider.

**Comment by schlessera** [comment]
I made some assumptions when writing up the above:
a.) we need a solutions for AMP Stories irregardless of WP Core/Gutenberg
b.) the solution does not only need to work during export, but also during live work/preview/publishing on the site

If one or both of these are not true, the recommended approach needs to be adapted.

If a.) is not true: then we scrap this issue, and just use whatever the media library will hand us over. Core & plugins can already hook into that and modify as needed. If more people hit issues with video uploads, someone will build a defacto standard plugin for that.

if b.) is not true: then the action/filter might not make sense and we could probably focus on a file-based approach, maybe even at a script-level instead of within PHP.

**Comment by swissspidy** [comment]
For reference, here's the documentation for the video formats that AMP Stories currently supports: https://amp.dev/documentation/guides-and-tutorials/develop/amp_story_best_practices/?format=stories#video-formats

**Comment by swissspidy** [comment]
To complete the discussion here I am citing the [notes](https://docs.google.com/document/d/18UwCHA1hyKz1dAGhwbKszemXwLSpe9CUkhlQmG8fWAg/edit#) from last week's meeting:

* Both assumptions are correct:
  1. Solution needs to work for AMP Stories irregardless of WP Core/Gutenberg
  2. Work not just during export, but also during editing/live preview/publishing/etc.
* AMP Stories only support a limited set of [video formats](https://amp.dev/documentation/guides-and-tutorials/develop/amp_story_best_practices/?format=stories#video-formats), which means we don't have to worry about a huge list. So it's not a WordPress limitation, but specifically enforced by AMP Stories.  
  * For MP4, use `H.264`.
  * For WEBM, use `VP9`.
  * For HLS or DASH, use `H.264`.
* In a first step, we will build a solution that uses VideoPress to optimize videos for all users of WordPress.com / Jetpack Premium. Authentication / API is handled by Jetpack, so it would "just work".
* Next, we will leverage this to build an extensible solution that supports other providers as well.

Some concerns have been raised too:

* We should avoid relying on paid solutions whenever possible.
* Even though Jetpack is quite big, most AMP Stories editor users do not fall into the “work automatically” category
* How do users get assets from devices to use in Stories?

**Comment by swissspidy** [comment]
Created #3045 for implementing the VideoPress integration.

Closing this one for now.
