### ISSUE TITLE
Font Picker: Generate preview SVGs for Google Fonts

### ISSUE THREAD

**Issue by swissspidy** [ampproject/amp-wp#3028]
See #2877 and #3026 for details.

For the bundled Google Fonts, we should create the SVG previews automatically (ideally during build / download of the font list) so that we can use those in the font picker.

https://github.com/danmarshall/google-font-to-svg-path could potentially serve as an inspiration for this.

If this turns out to be unfeasible for whatever reason, an alternative approach would be changing the font picker to lazy-load the font stylesheets instead.

**Comment by swissspidy** [comment]
Just so this doesn't get lost:

In #2757, it was previously reported that the SVG previews don't look good for certain fonts. These should be used as a yardstick for evaluating whether we can continue with using (better) SVGs, or use lazy-loaded styles instead.

**Comment by spacedmonkey** [comment]
I spent sometime in looking at https://github.com/danmarshall/google-font-to-svg-path . Not sure it is really compatible with that we are doing here. The code written in type script and includes some large libraries. I also found this library https://github.com/samuelmeuli/font-picker-react but this uses API KEY, so I don't think will scale. The library this uses https://github.com/samuelmeuli/font-manager might also work, but again written in typescript. 

I am starting to believe this is preview is going to have to be custom written, which is going to take quite a bit of time.

**Comment by spacedmonkey** [comment]
I spent sometime looking into the [opentype.js](https://opentype.js.org/) library. Getting the library to run in the npm / grunt is extremely hard, because of this [line](https://github.com/opentypejs/opentype.js/blob/a2259ae390d9ea5af85328142c8f6d29688f463c/src/opentype.js#L376). It expects that if you are running locally, that font files are local as well. This is an issue, as means all font files need to be downloaded first, something not easy or fast to do. 

But even with a local font, it doesn't seem to work. I can't understand why. I am going to try if I can do this another way. But it maybe not be possible in node.

**Comment by spacedmonkey** [comment]
I have managed to fix this issue as part of #3027, but lazy loading the font stylesheets as the results are rendered for each font in the autocomplete. This ticket is not longer required.

**Comment by spacedmonkey** [comment]
Fixed in #3155

**Comment by swissspidy** [comment]
Marking as a duplicate of #3027 as the attached PR #3155 will handle this with actually enqueueing the styles instead of dealing with SVGs.
