### ISSUE TITLE
Infogram embed support

### ISSUE THREAD

**Issue by mlaroy** [ampproject/amp-wp#3036]
Would it be possible to add [Infogram](https://infogram.com/) to the list of supported embeds? Currently, the embed generates JavaScript which gets stripped out by the plugin. 

Currently supported embeds:
https://amp-wp.org/documentation/how-the-plugin-works/amp-content-rendering-in-wordpress/native-wordpress-embed-and-shortcode-support/

**Comment by westonruter** [comment]
The list of embeds directly supported by the plugin is generally scoped to what WordPress Core directly supports. For other embeds, it should be handled by another plugin, like here the [Infogram](https://wordpress.org/plugins/infogram/) plugin.

If not added directly to the Infogram plugin, a standalone plugin could be added similar to what you can see for adding support for Vidyard embeds: https://gist.github.com/westonruter/db093fd74797a965fbb4f3af232db47c

**Comment by mlaroy** [comment]
thanks @westonruter  - would a solution like that vidyard example work in a gutenburg embed block?

**Comment by westonruter** [comment]
Yes, it should.

**Comment by swissspidy** [comment]
Since Infogram supports [oEmbed](https://developers.infogr.am/oembed/), you could suggest adding native support for it in WordPress core.

You can do so by opening a new ticket on [WordPress Trac](https://core.trac.wordpress.org/) and answering the questions outlined here: https://make.wordpress.org/core/handbook/contribute/design-decisions/#whitelisting-oembed-providers

**Comment by westonruter** [comment]
In the mean time, using a plugin like the one for Vidyard will get you AMP support for Infogram. (I assume it ultimately can be represented with an `amp-iframe`.)
