### ISSUE TITLE
Glue for Yoast SEO & AMP conflict with AMP Stories

### ISSUE THREAD

**Issue by jdelia** [ampproject/amp-wp#3041]
Using the latest beta version of the AMP plugin (Version 1.2.1-beta2-20190813T202856Z-ccd10eec), Yoast SEO (latest 11.3) and Glue for Yoast SEO & AMP (Version 0.4.3 ) is generating the following warning when viewing an AMP Story. 

`Warning: array_merge(): Argument #2 is not an array in /app/public/wp-content/plugins/amp/includes/class-amp-story-media.php on line 154`

https://cl.ly/8f4e6e8130a7

Disabling the Glue for Yoast SEO & AMP plugin removes the warning. I've tested this on three sites all with the same warning. I did not receive a warning using the current 1.2.0 release of the AMP plugin.

**Comment by westonruter** [comment]
Thanks for reporting.

The code in question is:

https://github.com/ampproject/amp-wp/blob/3362b66ca9337e9de02ffc89404b0f577540b0a1/includes/class-amp-story-media.php#L144-L155

This code comes from #2930.

I'm guessing it is due to the Yoast AMP Glue plugin doing something here:

https://github.com/Yoast/yoastseo-amp/blob/876424820e752c1042ae12e0233d59bc4f0d5478/classes/frontend.php#L221-L223

I thought the AMP Stories code accounted for this however. This could ultimately be a bug with the Yoast AMP Glue plugin.
