### ISSUE TITLE
amp-sidebar immediately disappears after opening

### ISSUE THREAD

**Issue by billerickson** [ampproject/amp-wp#3048]
I have the following sidebar based on the [amp-sidebar documentation](https://amp.dev/documentation/components/amp-sidebar/?format=websites):

```html
<amp-sidebar id="sidebar1" layout="nodisplay" side="right">{content here}</amp-sidebar>
<a class="mobile-menu-toggle" href="#" on="tap:sidebar1">Toggle</a>
```

When the menu toggle is clicked, the sidebar appears but immediately disappears: https://cl.ly/ebe6c34ae2b0

If I remove `layout="nodisplay"`, it appears on pageload and disappears immediately: https://cl.ly/a3bca636a674

Even when I remove all styling from my WordPress theme I have the same experience (this time with `nodisplay`, like the first example): https://cl.ly/a5038fe4e335

`<amp-sidebar>` is a direct descendent of `<body>`. I originally had it at the bottom of the document, but after reading #1574 I moved it to the first child of body, but the issue persists.

**Comment by westonruter** [comment]
@billerickson I pasted that code into the top of Twenty Nineteen's `header.php` (after `wp_body_open()`) and it worked as expected. Have you tested in 1.2.1-beta2?

**Comment by billerickson** [comment]
I'm sorry, it was an issue on my end.  When I used the `script_loader_tag` filter to add the `async custom-element=""` part it affected scripts from the AMP plugin itself.

Is there a better way to enqueue AMP components? Here's how I'm doing it:

```
/**
 * AMP Scripts
 *
 */
function ea_amp_scripts() {
	if( ! ea_is_amp() )
		return;

	wp_enqueue_script( 'amp-auto-ads', 'https://cdn.ampproject.org/v0/amp-auto-ads-0.1.js', array(), '0.1', false );
	wp_enqueue_script( 'amp-sidebar', 'https://cdn.ampproject.org/v0/amp-sidebar-0.1.js', array(), '0.1', false );
}
add_action( 'wp_enqueue_scripts', 'ea_amp_scripts' );

/**
 * Customize AMP script tags
 *
 */
function ea_customize_amp_script_tags( $tag, $handle, $src ) {
	if( in_array( $handle, array( 'amp-auto-ads', 'amp-sidebar' ) ) )
		$tag = '<script async custom-element="' . $handle . '" src="' . esc_url_raw( $src ) . '"></script>';
	return $tag;
}
add_filter( 'script_loader_tag', 'ea_customize_amp_script_tags', 10, 3 );
```

**Comment by westonruter** [comment]
@billerickson There is no need to add the `async` or `custom-element` attributes because the AMP plugin does this for you. It also registers the scripts for you. So all you should need is:

```php
/**
 * AMP Scripts
 *
 */
function ea_amp_scripts() {
	if( ! ea_is_amp() )
		return;

	wp_enqueue_script( 'amp-auto-ads' );
	wp_enqueue_script( 'amp-sidebar' );
}
add_action( 'wp_enqueue_scripts', 'ea_amp_scripts' );
```

Beware that your mileage may vary when AMP components outside of AMP pages. The intention is to directly support this in the future under the [Bento AMP](https://blog.amp.dev/2019/05/01/amp-as-your-web-framework/) initiative.

See:

* Script registration: https://github.com/ampproject/amp-wp/blob/e8bb226c35c391ec5d27aff9c14b61edf57933fd/includes/amp-helper-functions.php#L393-L476
* Injection of attributes: https://github.com/ampproject/amp-wp/blob/e8bb226c35c391ec5d27aff9c14b61edf57933fd/includes/amp-helper-functions.php#L525-L583
