### ISSUE TITLE
Odd notices when choosing a story page template

### ISSUE THREAD

**Issue by jdelia** [ampproject/amp-wp#3063]
Testing the latest v1.2.1-RC1 with Genesis 3.1 and am seeing odd notices in the templates.

https://cl.ly/4beb4da9cfe5

See lots of these errors in the console. 

https://cl.ly/aa0257af9e0f

I've got one WP5 site without Genesis that is not showing this issue 

https://cl.ly/13a3d313001a

I'll continue to troubleshoot to see what is different.

**Comment by westonruter** [comment]
@miina Should this not have been address by the bumping the version for the stories templates?

**Comment by jdelia** [comment]
When I roll back to the previous beta version, I do not see the issue.

**Comment by miina** [comment]
@westonruter Yep, it should. Just checked that the version in beta2 is `0.3.6` and in RC `0.3.8`, looks like the templates' update was not triggered in this case, however, not sure why.

Just tried installing beta2 and then RC and it seems to update properly. I wonder what caused the failure in this issue's case.

Also wondering if we should instead of always updating the templates' version and then doing the update, do the update first and only update the version if it succeeded? Or perhaps, if it didn't succeed, display a manual update CTA instead? Thoughts?

**Comment by jdelia** [comment]
On my testing sites, I downloaded the RC built zip and then deleted the current beta2 plugin, and installed the new zip.

**Comment by jdelia** [comment]
Apparently the zip file here: https://cl.ly/afc69f45e481 was not the one I should have been testing. Thank you @swissspidy for pointing that out in our discussion here #2084

Using the amp.zip file here [https://github.com/ampproject/amp-wp/releases/tag/1.2.1-RC1](url) I am not seeing any issues with the AMP Story templates. They are working.  :)
