### ISSUE TITLE
importing stories in raw format not showing valid

### ISSUE THREAD

**Issue by Amanrazdan** [ampproject/amp-wp#3078]
When trying to migrate and host the stories on Wordpress the only good option we have is to use amp stories plugin from Wordpress and that what we have been doing for very long. But now when we try to import stories to our WP it shows error and doesn't convert it into a block. However, in the preview mode, the code still exists 

here is how to replicate this issue
1. we create a new story and edit it as Html 
here is a sample story - https://github.com/ampproject/docs/raw/master/tutorial_source/amp-pets-story.zip
![image](https://user-images.githubusercontent.com/28403318/63568867-98bf0d00-c594-11e9-97fc-50e0ab70d74f.png)

2. we add the custom story code broken down into pages 
![image](https://user-images.githubusercontent.com/28403318/63568952-ecc9f180-c594-11e9-8b1e-28ef10738fe7.png)
3.then it shows this error 
![image](https://user-images.githubusercontent.com/28403318/63568966-fa7f7700-c594-11e9-9034-4b0c03d0d533.png)
4. when we try to resolve it shows  nothing as valid
![image](https://user-images.githubusercontent.com/28403318/63569014-31ee2380-c595-11e9-85a1-3517b262fa50.png)

**Comment by swissspidy** [comment]
Hi there!

Thanks for raising this. It's a really interesting use case and not really one that we have been thinking of so far.

You mention that you want to import multiple stories. Are you planning on editing them later within WordPress too, or is it basically just a one-time thing?

The problem with importing a story this way is that it can't be transformed 1:1 into a story that works within the WordPress editor. That's because all the styling is done by using components like `amp-story-grid-layer`, whereas in our editor blocks can be freely positioned by dragging them anywhere on the page, and the styling being part of the block's attributes.

So while you can totally recreate the "Joy of Pets" example story in the WordPress editor, it wouldn't be easily possible to import that story as-is and then continue editing it in WordPress.

**Comment by Amanrazdan** [comment]
I think for the beginning I will just focus on importing raw zip files which are bundle files of finished amp and it can work simultaneously with custom amp story but can't be edited. I am trying to work on that but confused about how the media and other files will be mapped on post structure. Or we can just add it as a reference in custom post type.

**Comment by Amanrazdan** [comment]
Thanks for considering it though
