### ISSUE TITLE
Reusable blocks go unavailable

### ISSUE THREAD

**Issue by nagpai** [ampproject/amp-wp#3081]
### Summary 
When AMP plugin version 1.2.1 is active, the Gutenberg editor does not show the option of Reusable Blocks when you click the + symbol to add a new block

### Steps to reproduce
1. Create a test WordPress site
2. Create a post or a page, and save any test block as a Reusable block
![Screenshot 2019-08-23 at 3 09 04 PM](https://user-images.githubusercontent.com/4162931/63583253-468fe300-c5b8-11e9-99b3-aa3ab127adbc.png)
3. Activate AMP plugin
4. Open up another post and try to add the reusable block. You will not see the group
![2019-08-23 15 14 10 future-seahorse jurassic ninja ebb112ddb30a](https://user-images.githubusercontent.com/4162931/63583460-b1d9b500-c5b8-11e9-94c6-b70451b7f55b.png)
5. Deactivate AMP plugin and open a new page in editor, you see the reusable blocks again:
![2019-08-23 15 16 19 future-seahorse jurassic ninja f7419f8ea56d](https://user-images.githubusercontent.com/4162931/63583611-fbc29b00-c5b8-11e9-95f6-b5d9ac227197.png)

### Impact of the bug
Users who had Reusable blocks before updating their AMP plugin to 1.2.1, would all of a sudden see all these blocks go missing.

**Comment by swissspidy** [comment]
Yikes, that sounds like a bug! Thanks for reporting this.

We might have been a bit overzealous in #2879. Since story templates are reusable blocks, we want them to be visible in the Stories editor, but not the regular block editor. Previously they were listed as reusable blocks though, even when one is not using AMP Stories.

Now it seems that no reusable blocks are shown in the block editor when AMP Stories is not active. This needs to be fixed.

@nagpai As a temporary workaround, I suggest turning on the Stories experience in the AMP plugin settings. You don't have to use it though and it won't have any impact on your website when it's turned on. But it will bring back your reusable blocks.

**Comment by swissspidy** [comment]
Another report: https://wordpress.org/support/topic/updated-new-amp-plugin-it-is-conflicting-with-gutenberg-reusable-blocks/

**Comment by Ipstenu** [comment]
You can't use Stories unless you have the Gutenberg Plugin installed and active, which I do not have on my *production* site. So that's not really a great workaround for people.

**Comment by westonruter** [comment]
Let's do a hotfix release for this bug next week.

**Comment by miina** [comment]
Testing instructions:
- Add a Reusable block (add a block, click "More Options" block menu and choose "Add to Reusable Blocks")
- Turn off AMP Stories Experience (uncheck AMP Stories from AMP General Settings)
- Verify that the added Reusable block can be found in Block Inserter of a regular post (can be searched by its name, too).
- Verify that the saved reusable block appears under `/wp-admin/edit.php?post_type=wp_block`
- Verify that the Story Templates do not appear under the Reusable blocks (not in search nor in `/wp-admin/edit.php?post_type=wp_block`).

Turn on AMP Stories Experience and verify the same things.
Additionally, verify that the Templates to appear as expected in the Templates Inserter.

**Comment by miina** [comment]
New ticket for reference: https://github.com/ampproject/amp-wp/issues/3105

**Comment by nagpai** [comment]
@westonruter I tested with latest stable WordPress test instance, and it works perfectly now. I am now able to see the reusable blocks settings correctly. Thanks to the team!
