### ISSUE TITLE
Create aliases and deprecations to adapt to new  terminology

### ISSUE THREAD

**Issue by schlessera** [ampproject/amp-wp#3111]
Some terminology was changed, but the code was not adapted to take this into account.

As an example, here's part of the documentation:
![Image 2019-08-28 at 4 16 10 PM](https://user-images.githubusercontent.com/83631/63863974-5db34400-c9af-11e9-9849-8b796611f629.png)

This flag should work just as well if you set `'transitional' => true`, documentation should be adapted accordingly, and after a set period of time, `'paired' => true` should still work but throw a deprecated notice.

**Comment by westonruter** [comment]
This is a bit confusing. The term “Paired AMP” is a thing. It entails that you have a `canonical` non-AMP page that has a `link[rel=amphtml]` pointing to a separate AMP version. In this way, both “Transitional” mode _and_ “Reader” mode are examples of `paired` modes. This is indicated in the mode descriptions:

![image](https://user-images.githubusercontent.com/134745/63894593-d90df900-c9a1-11e9-8e1b-1b067d9ae51b.png)

This is why the `paired` theme support argument was not changed to `transitional` when the “Paired” mode was renamed to “Transitional”.

So I don't think a change is necessary here. A change _would_ have been needed of the theme support flag was `mode` and had values `standard` or `transitional`. But since it's `paired` then I think it's OK as is.

Assuming the mode has not been set in the admin screen, the default modes are specified in code as follows:

# Standard mode (formerly “Native”)

Either:

```php
add_theme_support( 'amp' )
```

or 

```php
add_theme_support( 'amp', [ 'paired' => false ] )
```

# Transitional mode (formerly “Paired”, but still a paired-type mode)

```php
add_theme_support( 'amp', [ 'paired' => true ] )
```

# Reader mode (formerly “Classic”, but also a paired-type mode)

No code change, since this remains the default. However, as of #1384 the default could change to Standard or Transitional modes, unless an `amp` directory is in the theme in which case it could remain defaulting to Reader (per #2931).

**Comment by westonruter** [comment]
For more information about “Paired AMP” see this post: https://blog.amp.dev/2019/05/01/amp-as-your-web-framework/
