### ISSUE TITLE
Getting "Missing or invalid structured data item" on Category Pages

### ISSUE THREAD

**Issue by joseph-farruggio** [ampproject/amp-wp#3174]
I have 63 pages (almost all category or tag archive pages) reporting "Missing or invalid structured data item" in Search Console.

When I run individual pages through the AMP validator I see that each page is a Valid AMP page. Below in "Suggested actions" I get "Missing or invalid structured data item.
A required property in your structured data is missing, misspelled, or has an invalid value."

When I click "Test your structured data", I see zero errors or warnings.

Here's an example URL: https://www.mightymoms.club/category/incredible-infants/better-sleep/

What can/should I do about this?

**Comment by westonruter** [comment]
I'm not seeing any issues when testing the structured data for that URL: https://search.google.com/structured-data/testing-tool/#url=https%3A%2F%2Fwww.mightymoms.club%2Fcategory%2Fincredible-infants%2Fbetter-sleep%2F

![image](https://user-images.githubusercontent.com/134745/64209414-4663d300-ce55-11e9-95ac-ef9cb13a9f0d.png)

Since Yoast is generating the Schema.org metadata on that URL, this would be a better question for them: https://kb.yoast.com/kb/support/
