### ISSUE TITLE
Discovery: Stories Ranking Well in Search Results

### ISSUE THREAD

**Issue by MackenzieHartung** [ampproject/amp-wp#3179]
To do: What requirements are needed for Stories to rank well in search results? If jetpack and yoast do not cover the requirements identify other plugins we need to engage with to ensure we provide users the proper capabilities.

**Comment by spacedmonkey** [comment]
Some work with Yoast seems to already been done here. See https://github.com/Yoast/wordpress-seo/pull/13446

**Comment by spacedmonkey** [comment]
This is now been merged. https://github.com/Automattic/jetpack/pull/13416

**Comment by spacedmonkey** [comment]
Recommendation:

There seems to be have been a fair bit of work already done on this. There are two PR already open for Yoast and Jetpack already. See 
Yoast/wordpress-seo#13446
Automattic/jetpack#13416

The yoast PR still needs a little work, so that is an action. Otherwise, the AMP template seem pretty SEO friendly already with work being put into ALT tags and screen reader text going a long way to help with the complete visual elements on the stories. 

The only one item I might flag, is by default many of the stories do no contain any h tags, speically H1s. This is possible by adding a text block and changing the text type. However, this option is a somewhat hidden and the is no visual indicator when the text type is changed. I believe it might be better to have another header block and break out and remove option from the text block. This might push users to add header tags to they pages and improve SEO.

**Comment by spacedmonkey** [comment]
@westonruter I noticed that the two PRs for Yoast and Jetpack, don't override `amp_get_schemaorg_metadata`. If either of these plugins are active, should the open graph values generated by these plugins override the defaults in the AMP plugin?

**Comment by westonruter** [comment]
@spacedmonkey In the case of Yoast, the AMP-generated Schema.org metadata is overridden entirely. In the case of Jetpack, they _do_ integrate with the AMP-generated Schema.org meta here: https://github.com/Automattic/jetpack/blob/a9959f247ae98b07aeb5a3c1814477c30a0744ec/3rd-party/class.jetpack-amp-support.php#L39

I think there should be a merge, not an outright override on either end.

**Comment by spacedmonkey** [comment]
As a proof of concept, I added a commit https://github.com/Yoast/wordpress-seo/pull/13446/commits/ba929abcda8020508cf393d4635290f8e480680f to the existing yoast PR. This overrides article schema and replaces it with schema generated by the amp plugin. 

@MackenzieHartung As the action point to this ticket, should I create a ticket to track the work on the yoast plugin on our board?

**Comment by spacedmonkey** [comment]
Jetpack 7.8 beta 1 released - https://github.com/Automattic/jetpack/releases/tag/7.8-beta
This contains SEO fix for AMP Stories.

**Comment by spacedmonkey** [comment]
It is clear what the actions are for this. 
1. Integration Yoast ld data with AMP stories data. 
1. Integration Jetpack ld data with AMP stories data. 

Both of these actions are work that is required on these plugins and not the AMP plugin. I will create issues, but the PRs will not be here. 

Worth noting that the Jetpack work is already complete and will be released in 7.8 of the plugin. For that reason I will not create a issue to track it.
