### ISSUE TITLE
Illegible Text Warning

### ISSUE THREAD

**Issue by jauyong** [ampproject/amp-wp#3303]
## Feature description

As a user I want to be warned when my text is illegible so that my stories look good and are engaging.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* AC1: When text is illegible(?) due to color contrast, a warning should be displayed to the user

Notes:
- This is dependent on the outcome of https://github.com/ampproject/amp-wp/issues/3298
- It is possible this could be implemented via AI.
- Animations should be taken into consideration for this as well. 
 
## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by barklund** [comment]
## Background

This is a question of [color contrast](https://medium.muz.li/the-science-of-color-contrast-an-expert-designers-guide-33e84c41d156). [Web Content Accessibility Guidelines (WCAG) 2.0](https://www.w3.org/TR/WCAG20/#visual-audio-contrast) defines a minimum color contrast* based on the standard level (AA is minimum standard, AAA is enhanced standard):

| Standard | AA | AAA |
| - | - | - |
| Small text† | 4.5:1 | 7:1 |
| Large text† | 3:1 | 4.5:1 |

One possible interpretation of these varying standards could be to issue an error if AA is not met and a warning if only AAA is not met.

Font legibility is both relevant for text and images with text. We will however only considered text added through the AMP editor directly, not text in images, videos or external content.

* Color contrast is calculated as [the difference in relative luminance](https://www.w3.org/TR/WCAG20/#relativeluminancedef). There's a very simple [javascript package](https://github.com/tmcw/relative-luminance) for this calculation.
† Small text is defined as smaller than 18px for regular weight fonts and smaller than 14px for bold weight fonts.

## Elements

### Text on known background

The regular **Text** element can have a non-transparent background. The **CTA** element is required to have a non-transparent background. For both of these cases the color of the text and background can be selected freely and a color contrast validator is built into the color selection panel alerting users about bad contrasts.

If the _Color Settings_ panel is collapsed, the warning is currently completely hidden. The panel collapses by default once a new selection is made.

This warning might have to be moved from here to the general global error handling system used for this ticket.

The **Table** element allows users to select either a transparent background or a non-transparent background. However, the text color cannot be changed from the default black and only very bright backgrounds are allowed. Thus no warning is ever needed for known backgrounds here.

### Text on unknown background

The following elements allowed in the AMP story editor (can) contain text on transparent background:

* Text
* List
* Quote
* Story title
* Story author
* Story date
* Code
* Pullquote
* Preformatted
* Verse
* Table

However, the **Text** element will be the most important one to consider, as it will be the most used text-carrying element.

For all these, the legibility of the text depend on the text color plus whatever other element, if any, is placed in their background.

**Pullquote** and **Text** actually allow the user to customize the text color. All other elements on the above list only allow default black text. All of them allow or require the element to have transparent background.

The Custom HTML element allows the (HTML-savvy) user to do whatever they like - including colors. Because the Custom HTML element is so liberal in what it allows, it will not be considered in the following implementation. If you use the Custom HTML element, you've already deviated from the set of tools given and you're on your own regarding color contrast validation.

### Limitations

As mentioned above, Custom HTML is excluded, as it allows users to do whatever they like. This however only goes for 

If a background is an external element (embed or page attachment), the client can't always read the contents of this element, and no proper validation can be made. A warning could be displayed urging the editor to be aware of potential color contrast problems with the external content.

If a background element is a video or an animated gif, only the poster image/first image will be used for this calculation. A warning could be displayed urging the editor to be aware of potential color contrast problems during the playback.

If the text element or any background element animates, any check will only be made every 1 second of the animation. Thus if an element animates in less than a second, only the initial and final state of the elements will be considered. If it's a long animation, intermediate states will also be examined, but not every possible state.

## Implementation

Whenever a text element is displayed on a transparent background (any of the above 11 listed), we will continually* compare the font color with the "average" background color.

This will be done using HTML2Canvas on the background content rendering the background as an image, cropping this image to look at larger chunks of background at a time and comparing the background color for each chunk with the font color using the relative luminance calculation mentioned above.

This allows us to do everything from merely saying the some part of the text is hard to read, to actually highlight the problematic area.

Here's a demo of the idea in action (without animation support): https://codepen.io/barklund/pen/wvvBZax - feel free to play around.

* we will check on registry updates debounced 100ms, thus no more often than every 100ms.

**Comment by spacedmonkey** [comment]
My worry here is performance. As long these checks are not done on live and only performed when a user updates the post or otherwise requests validation, then I am okay with this implementation as documented above.

**Comment by miina** [comment]
I did not read everything through in detail yet, however, one small note for consideration after a quick look:
- The Quote block also has a White style:
<img width="911" alt="Screenshot 2019-10-09 at 21 26 43" src="https://user-images.githubusercontent.com/3294597/66513516-93ce0280-eadb-11e9-8185-02340154be3b.png">

Worth noting that it's a custom style added within the plugin and not a default Gutenberg style.

**Comment by miina** [comment]
Q: Do I understand correctly that by "background color" you mean the background color directly under the text only? Or would this include the background under the whole element containing the text?

Asking just in case since (at least) in case of post meta blocks (such as Story Title), the `h1`/`div` element which includes the text covers the whole block, even if the text is just taking a small part of the block.

**Comment by ThierryA** [comment]
Blocked by #3298
