### ISSUE TITLE
Add support for forcing AMP on protected posts

### ISSUE THREAD

**Issue by indieisaconcept** [ampproject/amp-wp#3428]
## Feature

Presently password-protected posts are excluded from AMP processing. However as `post_password_required` is used to determine if a post should be processed, this behaviour is only temporary. Should the `wp-postpass_*` be present & valid for the current post/page then processing occurs without issue.

I would like to propose making available a filter which would allow theme authors to have more control over whether something should be processed as AMP.

The rationale for this is to be able to better support protected posts when running a site as a **PWA** with **AMP Shadow Doc**.

Consider the code below. If one, or both where available it would provide a greater degree of control & negate the need for registering a filter for `post_password_required` to workaround this.

**amp-helper-functions.php**

```php
function post_supports_amp( $post ) {

    $errors = AMP_Post_Type_Support::get_support_errors( $post );
    $errors = apply_filters( 'amp_post_supports_amp', $errors );

	return 0 === count( $errors );
}
```

**AMP_Post_Type_Support:get_support_errors**

```php
function get_support_errors( $post ) {

    ......

    return apply_filters( 'amp_get_support_errors', $errors );
}
```

Should the team see value in such a proposal I'd be more than happy to implement.

Alternatively if there is something far more suitable & presently available it would be great to know.

Thanks.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by westonruter** [comment]
Thanks for the issue. I actually think that we should remove password protection from disabling AMP entirely. Disabling it doesn't make sense to me now. It was disabled a loong time ago in https://github.com/ampproject/amp-wp/commit/abcf20823e0befb070ee07c874124056c76c1bc3 and it may have been due to AMP not supporting forms way back then. Now, however, forms are fully supported in AMP. In fact, in Standard or Transitional modes, you can just comment out these lines:

https://github.com/ampproject/amp-wp/blob/d0fbe68c53922f4c4b919e42318e390275510122/includes/class-amp-post-type-support.php#L91-L93

And password-protected posts are perfectly accessible in AMP. In order to make them work in Reader mode, we'd just need to incorporate the same password protection checks and inclusion of the password form rather than the normal post content. In the mean time, all that would be required is this:

```diff
diff --git a/includes/class-amp-post-type-support.php b/includes/class-amp-post-type-support.php
index 5c77b0b2..34a5d3d7 100644
--- a/includes/class-amp-post-type-support.php
+++ b/includes/class-amp-post-type-support.php
@@ -88,7 +88,7 @@ class AMP_Post_Type_Support {
 			$errors[] = 'post-type-support';
 		}
 
-		if ( post_password_required( $post ) ) {
+		if ( ! current_theme_supports( 'amp' ) && post_password_required( $post ) ) {
 			$errors[] = 'password-protected';
 		}
 ```

**Comment by indieisaconcept** [comment]
@westonruter thanks for the feedback. I'll review.

**Comment by csossi** [comment]
Verified in QA
