### ISSUE TITLE
<figure> element wrapping an <amp-img> element is mis-sized

### ISSUE THREAD

**Issue by schlessera** [ampproject/amp-wp#3493]
## Bug Description

When wrapping an `<amp-img>` element with `layout="intrinsic"` in a `<figure>` element, the wrapping `<figure>` has a height that is a few pixels larger then the image it wraps.

This problem seems to be unrelated to any CSS being parsed, so I assumed this is JavaScript behavior inside the `<amp-img>` element that is broken.

## Expected Behaviour

When wrapping a `<figure>` around an `<amp-img>`, both should have the same height (unless otherwise styled).

## Steps to reproduce

Markup to reproduce:

```html
<figure>
    <amp-img src="https://via.placeholder.com/580x300"
             width="580"
             height="300"
             layout="intrinsic"></amp-img>
</figure>
```

See https://codepen.io/schlessera/pen/BaaKaxo

## Screenshots

![Image 2019-10-14 at 11 53 04 AM](https://user-images.githubusercontent.com/83631/66743052-5bcb1480-ee79-11e9-97b3-f6e2082f52fa.png)

## Additional context

 - Browser: Google Chrome Version 77.0.3865.120 (Official Build) (64-bit)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by schlessera** [comment]
Submitted bug report to `amphtml`: https://github.com/ampproject/amphtml/issues/25032

**Comment by westonruter** [comment]
I'm not sure this is a bug with AMP as it happens with regular `img` as well as `amp-img`: https://codepen.io/westonruter/pen/zYYqKRX

AMP has this style rule for intrinsic images:

```css
.i-amphtml-layout-intrinsic {
    display: inline-block;
    position: relative;
    max-width: 100%;
}
```

We could fix the issue on our side by adding a rule like this:

```css
amp-img[layout=intrinsic] {
    vertical-align: middle;
}
```

**Comment by westonruter** [comment]
Ref: https://github.com/ampproject/amp-wp/pull/3403#issuecomment-541297278

> The "spacing discrepancies" mentioned above seem to be related to the `<amp-image>` element or its parent `<figure>` element, and the way they size themselves. However, I couldn't find out the specific problem yet.
>
> ![Image 2019-10-12 at 9 31 18 AM](https://user-images.githubusercontent.com/83631/66697242-23d69c80-ecd4-11e9-9f87-41de1927a565.png)
> 
> The `<amp-img>` contains an image at 580x300px and is also explicitly set to these dimensions. The computed height is 300px.
>
> For the surrounding `<figure>`, though, the computed height is 308px. It shows a small gap at the bottom of the image where it leaves 8px of space. I couldn't find any CSS that would account for this gap.
> 
> I assume for now that this spacing is incorrectly calculated inside of `<amp-img>`'s JS code.

**Comment by westonruter** [comment]
Does the `img` have any such `vertical-align` in the non-AMP version?

**Comment by schlessera** [comment]
No, but it does have a `display: block;` Setting that on the `<amp-img>` seems to fix the issue.

**Comment by westonruter** [comment]
I see. The `display:block` is coming from Twenty Twenty:

![image](https://user-images.githubusercontent.com/134745/66940025-09186680-eff9-11e9-9151-80edf14d1756.png)

And in AMP this is getting overridden:

![image](https://user-images.githubusercontent.com/134745/66940115-3a913200-eff9-11e9-9b41-4bdadc5d3cf4.png)

Because of the `intrinsic` layout like you correctly identified.

It's interesting that Twenty Twenty gives `img` a `display:block` with this selector. 

It looks like Twenty Nineteen also gives such `img` a `display:block` but it is targeted directly at image blocks:

![image](https://user-images.githubusercontent.com/134745/66940289-8d6ae980-eff9-11e9-97a9-1e48be0ac279.png)

And this increase of selector specificity causes it to override the `display` that `intrinsic` layout applies:

![image](https://user-images.githubusercontent.com/134745/66940340-a5426d80-eff9-11e9-8294-d561dc378ee4.png)

I wonder if this is a bug in Twenty Twenty's block styles.

In any case, I wonder if adding a style rule to the core theme sanitizer specifically for Twenty Twenty would be the best fix in the immediate term:

```css
.entry .entry-content .wp-block-image img {
    display: block;
}
```

**Comment by amedina** [comment]
@schlessera @westonruter Should we add that fix for now? Let's decide on that and then close this issue.

**Comment by schlessera** [comment]
This was fixed via https://github.com/ampproject/amp-wp/pull/3403/commits/bd4e2b9fd9cd378adc5efd226f9014de93c8b867
