### ISSUE TITLE
Images unexpectedly cropped on frontend

### ISSUE THREAD

**Issue by swissspidy** [ampproject/amp-wp#3498]
## Bug Description

Depending on the viewport size images can sometimes render with the sides cropped of. This is due to usage of `object-fit: cover;` for images.

https://github.com/ampproject/amp-wp/blob/2fbe020d4fb1150fb2c18a5cdc24b767b777a9f3/assets/css/src/amp-stories-frontend.css#L115-L117

Originally introduced in #2166 and adapted in #2250.

## Expected Behaviour

Images should not be cropped in an unexpected way. Images should be displayed responsively with consistent aspect ratio.

## Steps to reproduce

1. Visit https://cathibosco.com/stories/amp-contributor-summit-2019-amp-story-wordpress-beta/
2. Use dev tools to resize viewport
3. Notice how the AMP logo is sometimes cropped

## Screenshots

https://canddstudios.d.pr/XErATL

## Additional context

 - WordPress version: 5.2
 - Plugin version: 1.3
 - Gutenberg plugin version (if applicable): 6.6
 - Browser: Chrome

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by swissspidy** [comment]
@miina @westonruter Do you know why we originally implemented that this way?

**Comment by miina** [comment]
@swissspidy IIRC:
Otherwise, the images either were not responsive after resizing and lost their actual ratio (stretched out);
or alternatively the resizing didn't work as expected, e.g. you could resize an image to be very tall due to keeping the ratio it didn't really change the height. This, as well, was considered unexpected.

It wasn't possible to resize the image to the wished size if it didn't match the ratio, by "cropping" the user was given more options without having to crop an image to the exact size before using it on the stories.

**Comment by miina** [comment]
Basically, if we would not "crop"  and keep the ratio at the same time then the following could (and would) happen:
- The user resizes the image in the editor so that it's exactly from left to right edge and moves it so that it's exactly until the line of the bottom edge (or to some other block based on the snapping lines, etc.).
- The width will be assigned a value in % based on resizing and the height would be auto ( to keep the image ratio correct without cropping)
- In the FE, the image would be displayed from the left to the right edge (width responsive, based on the assigned %), however, since the height of the viewport is different, then the image would not reach to the end of the Page and there would be some space between the image and the end of the Page which does not show in the editor + the size of the space would differ based on the viewport.

This behavior feels like worse user experience compared to "cropping the edges off to match the resized area". WDYT?

Any thoughts so far for resolving the issue without "cropping"?

**Comment by barklund** [comment]
I think we need to expose a user setting for _cover_ or _contain_ object fit. Users will probably always want one or the other, so I don't think we need more options.

_Cover_ is great for photographs, but _contain_ is necessary for drawings, diagrams, logos and the like. Companies would **hate** to see their logos cropped off.

We could even default `jpg`'s to _cover_ and `gif`/`png`/`svg` to _contain_, as that's probably a sane default.

**Comment by miina** [comment]
Good point about the logos! Having an option to choose from would be a solution indeed.

**Comment by jauyong** [comment]
Hey @swissspidy I am not seeing the amp logos being cropped anymore. The only one that has an issue is this one when I set it to iPad. Is it still happening for you? 

![image](https://user-images.githubusercontent.com/5874851/67887616-000fb500-fb22-11e9-9a47-aabcdfe929eb.png)

**Comment by swissspidy** [comment]
Ah, I think https://cathibosco.com/stories/amp-contributor-summit-2019-amp-story-wordpress-beta/ was updated in the meantime to try to work around the issue. But what you're seeing on that screenshot is the same bug. Depending on the screen size (iPhone, iPad, desktop), the image are unexpectedly cropped — because of how `object-fit: cover;` works in CSS>
