### ISSUE TITLE
Twenty Twenty nav menu dropdown button does not reveal submenu on mobile

### ISSUE THREAD

**Issue by westonruter** [ampproject/amp-wp#3559]
## Bug Description

When opening the mobile menu on Twenty Twenty, attempting to expand a submenu currently does not cause the children to expand. It does, however, cause the button's arrow to toggle its state.

Introduced in #3403. Part of #3342.

## Expected Behaviour

Submenus should be displayed when toggling the submenu dropdowns.

## Steps to reproduce

0. Activate Twenty Twenty in Transitional or Standard AMP mode.
1. Create a nav menu with nested menu items.
2. View an AMP page in mobile viewport.
3. Open nav menu.
4. Attempt to expand a submenu item.

## Screenshots

Non-AMP on left, AMP on right:

![image](https://user-images.githubusercontent.com/134745/67131340-30b62d00-f1b9-11e9-92a5-dac7a0012a43.png)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by schlessera** [comment]
I couldn't replicate the above issue:

![Screen Recording 2019-10-21 at 12 47 PM](https://user-images.githubusercontent.com/83631/67199202-fccd4880-f400-11e9-8879-654edcf60535.gif)

However, what I did notice is that:
- The admin bar offset fix you added targets one specific modal (`.menu-modal`), instead of all modals (`.cover-modal`). That's why the search modal is still missing the offset.
- Clicking outside of a modal does not close the modal. I think the original theme does that, though.

I'll introduce separate issues for both of these.

**Comment by westonruter** [comment]
If it helps, my menus are assigned to locations like so:

![image](https://user-images.githubusercontent.com/134745/67225280-cb944e80-f3e7-11e9-8357-76aea7b750a9.png)

Here's the page output so you can see what I do: https://codepen.io/westonruter/pen/dyyNppm

**Comment by schlessera** [comment]
What I've found out so far from the above codepen is that the `<ul class="sub-menu">` that should receive the `active` class when the toggle is being clicked does not have an ID (all elements targeted by AMP actions are meant to have an ID be enforced).

So, likely culprits are:
- `xpath_from_css_selector()` might create an erroneous Xpath that does not yield the wanted result
- a same ID is added to multiple elements and stripped in the browser
- the markup changes so significantly that the CSS selector provided through the data attribute is not matching anymore

**Comment by schlessera** [comment]
I think this is due to something mangling the `data-toggle-target` attribute and escaping its HTML entities, turning the CSS `>` qualifier into `&gt;` instead:

![Image 2019-10-22 at 3 49 11 PM](https://user-images.githubusercontent.com/83631/67295263-2eb8da80-f4e7-11e9-98ea-05737b5e5571.png)

Now, how to find the culprit...

**Comment by westonruter** [comment]
I see that the `ul.submenu` for the button doesn't have an `id` attribute, when I expected it to have `id="amp-wp-id-10"`:

![image](https://user-images.githubusercontent.com/134745/67298629-5fc1ec80-f4a0-11e9-9358-7f4de4a2fe01.png)

However, I _do_ see the `id` being added to the same nav menu that is assigned to another location in the template:

![image](https://user-images.githubusercontent.com/134745/67298432-1a052400-f4a0-11e9-94bc-d296bb700bb8.png)

**Comment by schlessera** [comment]
Yes, that's what I noticed as well (https://github.com/ampproject/amp-wp/issues/3559#issuecomment-544889412).

I'm trying to find out why the `data-toggle-target` attribute is getting mangled, because that is what should point to the submenu and cause it to receive an ID as well.

**Comment by csossi** [comment]
Verified in QA
