### ISSUE TITLE
The the amp plugin is removing all the scripts and styles enqueued by other plugins  can you please contact AMP support?

### ISSUE THREAD

**Issue by samiJordan** [ampproject/amp-wp#3563]
## Additional context

 - WordPress version:
 - Plugin version:
 - Gutenberg plugin version (if applicable):
 - AMP plugin template mode:
 - PHP version:
 - OS:
 - Browser: [e.g. chrome, safari]

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by swissspidy** [comment]
Arbitrary JavaScript is not allowed in AMP. You cannot use JS `<script>` tags unless they are for loading [AMP components](https://amp.dev/documentation/components/) (which the AMP plugin will add for you automatically). In order for a page to be served as AMP, the invalid JS code must be removed from the page, which is what happens when you **accept** sanitization. Learn more about [how AMP works](https://amp.dev/about/how-amp-works/). As an alternative to using custom JS, please consider using a pre-built AMP functionality, including [actions and events](https://amp.dev/documentation/guides-and-tutorials/learn/amp-actions-and-events/) (as opposed to JS event handler attributes like `onclick`) and the [`amp-bind`](https://amp.dev/documentation/components/amp-bind/) component; you may also add custom JS if encapsulated in the [`amp-script`](https://amp.dev/documentation/components/amp-script/) tag.

This is why the plugin removes custom JavaScript from other plugins by default.

CSS is not removed unless it is not used on the page at all or if it exceeds AMP's limit of 50 KB for custom CSS.

I recommend you to check out [the plugin documentation](https://amp-wp.org/documentation/getting-started/) to get started with AMP in a WordPress context.

If you are using Reader mod, you can add other elements to the head of the page via the `amp_post_template_head` action. You can find out more about reader mode customization on the dedicated section of the [plugin website](https://amp-wp.org/documentation/how-the-plugin-works/classic-templates/).

If there's a specific JavaScript-heavy you'd like to use, you can also contact the developer of the plugin to ask about AMP status.
