### ISSUE TITLE
Add way to automatically center the CTA button

### ISSUE THREAD

**Issue by swissspidy** [ampproject/amp-wp#3615]
## Feature description

While #3343 added some good short term improvements to the CTA block's positioning, the current solution is far from perfect.

After a few discussions we came back to the idea of automatically centering the CTA block if, and only if, the block hasn't been moved already.

Miina also brought up an interesting solution to that:

> What about a block setting of "Center automatically" instead, to make things more understandable as to why something is happening?

This might actually be useful for other blocks as well.

Note: the eventual introduction of snapping will certainly have an affect on the UX here.

Related: #3476

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* After adding text to the CTA for the first time, clicking out of the CTA (exit text entry) and the CTA has not been moved, it should be centred automatically.

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by jauyong** [comment]
Hey @swissspidy,
RE: 
> if, and only if, the block hasn't been moved already
Can you explain the different scenarios here? At first I translated this to "as soon the CTA block is added", because if it's recently added for sure it hasn't been moved and then we can centre it by default. Then I saw the part about @miina's "centre automatically" solution and thought I may be missing something here.

**Comment by miina** [comment]
Hey @jauyong,

On "if, and only if, the block hasn't been moved already:
The idea here would be that _by default_, originally when added, the CTA button is centered, this means that yes -- as soon as the CTA block is added. And it would continue to center automatically unless the block is dragged, and then it couldn't be centered again automatically.

An alternative solution would be to keep the button as it is right now and add a new block setting something like "Center automatically" which would center the button automatically and disable the dragging feature for positioning.

I'm strongly in favor of the second option of "Center automatically" since this feels more consistent and better user experience, however, if someone else feels like centering automatically until moved, and then never center again is a better option then we could definitely discuss the two options more with the UX, too.

**Comment by swissspidy** [comment]
@samitron7 @cathibosco WDYT about such a "Center automatically" button for the CTA block?

**Comment by cathibosco** [comment]
I think we outlined this as a good solution in the design review, like this:
It is centered automatically, unless I move it. 
We discussed after a user stops typing (essentially,) it moves to centered... only once, and after that a user can move it anywhere within the allowed section if they prefer to. 

Does that make good technical sense to you?

**Comment by jauyong** [comment]
@cathibosco if a user adds text to the CTA and it is centred automatically, what happens if they edit or add to that text? I want to clarify the part where you said "only once"

**Comment by cathibosco** [comment]
@jauyong The thinking is that once or after a users adds the text, the CTA automatically centers. 
If they edit the text again or relocate the button it would not automatically center the CTA again.  This allows some control and some help with alignment without interfering. I suspect that alignment lines and snapping will also improve user experience as we get those features too.
