### ISSUE TITLE
Story don't allow Vimeo video

### ISSUE THREAD

**Issue by joseconti** [ampproject/amp-wp#3675]
Hi,

There's a validation error adding a Vimeo video in stories.
Stories > New > Add element > Embeds > Embed > add a Vimeo link https://vimeo.com/265111898 > Update

Error "There is 1 issue from AMP validation" "Invalid element: amp-vimeo"

Vimeo video needs this custom element:

`<script async custom-element="amp-vimeo" src="https://cdn.ampproject.org/v0/amp-vimeo-0.1.js"></script>`

And the video has to be added like this:

`<amp-vimeo data-videoid="265111898" layout="responsive" width="9" height="16"></amp-vimeo>`

Thank you

**Comment by westonruter** [comment]
Embeds like Vimeo are not currently allowed in AMP Stories. The allowed elements inside of a story page can be found at: https://github.com/ampproject/amphtml/blob/467ca77d10c507a7371af1815413848da808a679/extensions/amp-story/validator-amp-story.protoascii#L628-L763

Support for Vimeo, YouTube, and other such embeds can be tracked in this core issue: https://github.com/ampproject/amphtml/issues/15847

In the mean time, the AMP plugin should not be allowing you to add such embeds in the first place. So that is a bug.

**Comment by swissspidy** [comment]
To be precise, it's a bug in Gutenberg. We've fixed it a while ago, so this sounds like a regression:

https://github.com/WordPress/gutenberg/issues/15883
https://github.com/WordPress/gutenberg/pull/15885
