### ISSUE TITLE
There is content which fails AMP validation. Nevertheless, the invalid markup has been automatically removed?

### ISSUE THREAD

**Issue by george2178** [ampproject/amp-wp#3699]
Hello we just installed AMP Plugin to our website and we get this message now for every post we post/save ready for posting live.

There is content which fails AMP validation. Nevertheless, the invalid markup has been automatically removed. 

Invalid elements: script (23)

Invalid attributes: border

How can this be fixed and how  can it be served properly in AMP for all of our content article pages?

Do we have to add anything to our code on our website?

![amp screenshot](https://user-images.githubusercontent.com/57482957/68378235-bfafc880-0119-11ea-84be-1e6801907004.JPG)

**Comment by george2178** [comment]
Hello: UPDATE:

Also our Google Analytics Tag wasnt working when the AMP PLUGIN was enabled, now we have disabled it and GA is working .

What is causing this issue with our Wordpress Site?

**Comment by westonruter** [comment]
What mode are you using? Transitional or Standard? Please share the URL to your site to be able to best advise.

As for Google Analytics, we recommend using the [Site Kit plugin](https://wordpress.org/plugins/google-site-kit/), which is the official Google plugin for adding Google Analytics to your site. It is AMP-compatible.

----

In general, you are getting those validation errors because the theme and/or plugins on your site are not apparently AMP-compatible. 

The AMP plugin removes markup that does not confirm to its <a href="https://amp.dev/documentation/guides-and-tutorials/learn/spec/amphtml/">specification</a>, and that includes CSS that goes above the 50KB limit (after the plugin tries to minify it) and any custom JS scripts. Removal of JS can still result in an acceptable AMP experience as long as the theme/plugins are designed to gracefully degrade when JS is turned off in the browser. So it's up to you to look at the site in AMP and decide whether the removal of the invalid markup is acceptable. If not, then you have three options:

<ol>
	<li>Switch to <a href="https://amp-wp.org/ecosystem/">AMP-compatible theme/plugins</a>.</li>
	<li>Create a child theme and/or custom plugins which prevent the output of invalid markup in favor of adding <a href="https://amp.dev/documentation/components/">AMP components</a>. As an example of this, see <a href="https://gist.github.com/westonruter/b904977a296da091584a7a2264df2882">this child theme</a> of Noto Simple which adds AMP-compatibility. See <a href="https://amp-wp.org/documentation/getting-started/getting-started-developers/">developer documentation</a>.</li>
	<li>Lastly, switch to Reader mode. This will result in AMP pages that do not look the same as the rest of your site, but you shouldn't have to do any work to make it compatible.</li>
</ol>

The ecosystem of AMP-compatible themes and plugins is growing but it is still relatively small. So unless you are a developer, switching to Reader mode will likely be the best option for you unless you are able to switch theme/plugins.
