### ISSUE TITLE
Problem: "URL validation failed to due to the absence of the expected JSON-containing AMP_VALIDATION comment after the body"

### ISSUE THREAD

**Issue by Lofesa** [ampproject/amp-wp#3887]
When validate url this message show:
"URL validation failed to due to the absence of the expected JSON-containing AMP_VALIDATION comment after the body."

## Expected Behaviour

Show the errors of validation

- WordPress version: 5.3
 - Plugin version: 1.4.1
 - Gutenberg plugin version (if applicable):
 - AMP plugin template mode: transitional
 - PHP version: 7.3
 - OS: Centos 7
 - Browser: [e.g. chrome, safari] Firefox

In the log files I have messages related to the use of is_amp_function related to a plugin, but when this plugin is disabled, the messages go away and the issue with validat url continue.

In the acces log file I get this:
`/wp-admin/edit.php?post_type=amp_validated_url&amp_validate_error=response_comment_absent&amp_urls_tested=0 `

I have tried adding ?amp&amp_validate (as stated in #1733) to the url, get the same mesage when a try to view the validation errors.

iconv is installed as estated in #3207 

With all plugins disabled and a default theme, the issue is here.
I have a list of plugins that when enabled the amp validator icon in admin side have issue, but cannot view cause this:

Autoptimize
jQuery Updater
Sassy Social Share
Lazy Loader

But urls get amp validated in google and in amp validator.

![Captura](https://user-images.githubusercontent.com/22342793/70283099-48c12a80-17c0-11ea-8697-0cdc24bfe1bb.jpg)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by westonruter** [comment]
@Lofesa Thanks for the report. When you access a URL on the frontend and provide `?amp&amp_validate`, it is expected that the page would end in this:

```html
...
	</body><!--AMP_VALIDATION:{
    "results": [],
    "queried_object": {
        "id": 701,
        "type": "post"
    }
}
--></html>
```

Do you see something different?

If you look at your PHP error log, do you see anything?

**Comment by Lofesa** [comment]
Hi @westonruter 
No, none of these, not json snipet nor php error.
When I disable these plugins (Autoptimize, jQuery Updater, Sassy Social Share, Lazy Loader) I got a green AMP in the admin bar, but when I try to validate, the message about no JSON sow.

How I can help to debug this? do you need access to the WP admin? In such case I need a IP cause the acces is IP white listed.
I have enabled  define('WP_DEBUG', true); and define('WP_DEBUG_LOG', true); but no log file is created, the error sow at screen. File permission in directory and owner are rigth.
As far as the error exists when a default theme is set and no others plugins.... maybe a server missconfiguration?
Tell me how I can help.

**Comment by westonruter** [comment]
> How I can help to debug this? do you need access to the WP admin? In such case I need a IP cause the acces is IP white listed.

@Lofesa This may actually indicate the problem. What happens if you go to Site Health in the WordPress admin under the Tools menu? Are there any test failures for loopback requests? If so, you may need to make sure that you whitelist your own site's IP.

**Comment by Lofesa** [comment]
@westonruter  The public IP anf the loopback are whitelisted. In Site Health only have warnings about plugins and themes not used. No failures in loopback

**Comment by westonruter** [comment]
It will be difficult for me to give you an IP to whitelist as I am traveling.

I'm confused as to why the JSON comment is not appearing at the end of the body. For example, on my own site when I am logged-in, I can go to https://weston.ruter.net/?amp_validate and I can see after the `</body>` the aforementioned HTML comment like `.

Are the pages being generated valid AMP? In other words, if you copy the HTML response and paste it into https://validator.amp.dev/ does it validate? (You can ignore any validation error about dev mode, as this appears when the admin bar is showing.) If so, then this indicates the AMP post-processing is working properly.

Are other HTML comments being removed from responses?

**Comment by Lofesa** [comment]
Hi @westonruter 
Thank you for give me the clue to solve the issue.
".... Are other HTML comments being removed from responses?" 
I don´t realize thi´s an html comment.... I´m thinking is a json script.
Yes HTML comments are removed by the PageSpeed Module, I add &PageSpeed=off to the url and the comment is here:
```
<!--AMP_VALIDATION:{
    "results": [],
    "queried_object": {
        "id": 12137,
        "type": "post"
    }
}
-->
```

**Comment by westonruter** [comment]
OK! That is excellent news. So the need here is to prevent the comments from getting removed during validation requests. Is there a way you can prevent comments from being removed when an `amp_validate` query param is present rather than `PageSpeed=off`?

In the meantime, you can also try patching the plugin like so:

```diff
--- a/includes/validation/class-amp-validation-manager.php
+++ b/includes/validation/class-amp-validation-manager.php
@@ -1820,6 +1820,7 @@ class AMP_Validation_Manager {
 		$added_query_vars = [
 			self::VALIDATE_QUERY_VAR   => self::get_amp_validate_nonce(),
 			self::CACHE_BUST_QUERY_VAR => wp_rand(),
+			'PageSpeed'                => 'off',
 		];
 		$validation_url   = add_query_arg( $added_query_vars, $url );
 ```

But we'd want to find a permanent solution for compatibility with PageSpeed.

**Comment by Lofesa** [comment]
Hi
I have tried to disable PageSpeed in the /wp-admin/ location (I use nginx) but no chance.
I will try with the parameters, disabling pagespeed when contain amp_validate.
I´m thinking.... AMP plugin works (when in native or transitional mode) catching the output of the "normal" page and the converting this in an amp page, rigth?
A possible solution maybe cheking the headers. PageSpeed module set a x-page-speed (in nginx) or x-modpage-speed (in apache) and if where present add the PageSpeed=off

**Comment by westonruter** [comment]
> I will try with the parameters, disabling pagespeed when contain amp_validate.

We may want to make the URL filterable so that you can add those query params via a plugin.

> I have tried to disable PageSpeed in the /wp-admin/ location (I use nginx) but no chance.

This wouldn't help because the the `?amp_validate` requests are being made on the frontend. Yes, you initiate the request to validate from `/wp-admin/` but this request results in WordPress doing a loopback request on the frontend with `?amp_validate` in the URL. 

> I´m thinking.... AMP plugin works (when in native or transitional mode) catching the output of the "normal" page and the converting this in an amp page, rigth?

That's right. The AMP plugin uses output buffering to capture the output of a template and then it makes the necessary conversions for AMP while also removing anything that is not valid AMP. When you make the request with `?amp_validate` then it does additional work to identify the themes and plugins that were responsible for the invalid markup. 

> A possible solution maybe cheking the headers. PageSpeed module set a x-page-speed (in nginx) or x-modpage-speed (in apache) and if where present add the PageSpeed=off

The `X-Page-Speed` and `X-Mod-Pagespeed` headers are sent in the _response_, correct? We wouldn't want to conditionally add `PageSpeed=off` to the URL if those response headers are present, because then it would mean we'd have to make two requests. First without `?PageSpeed=off` and then again with `?PageSpeed=off` when we determine that PageSpeed is running.

----

As an alternative to all of this, it would probably be more robust if we consider not sending the validation results back in JSON data contained in an HTML comment. The results could instead have the results written directly into the DB when making the request, as opposed to sending the results back in the response. That would help the situation here, but it could also introduce other problems.

Maybe instead of putting the data in an HTML comment we should rather put it inside of a `<script type="application/json">` tag. That would probably make it less prone to be corrupted.

**Comment by Lofesa** [comment]
Hi
I have tried to add PageSpeed=off to the parameters via an nginx if:
`if ( $args ~*  (.*amp_validate.*) { set $args $args&PageSpeed=off; }`
but no luck, don´t work.
I can explore the option to disable remove_comments filter in PageSpeed module code when parameters in url contains amp_validate, but....

> Maybe instead of putting the data in an HTML comment we should rather put it inside of a `<script type="application/json">` tag. That would probably make it less prone to be corrupted.

this option sound better, cause not only PageSpeed can remove html comments, most of minifiers plugins can do and I think the AMP plugin can´t test the presence of all these plugins or software that delete the html comments and disable it for the request.

**Comment by westonruter** [comment]
@Lofesa I believe I have an even better solution in #3898.

Please test: https://github.com/ampproject/amp-wp/pull/3898#issuecomment-562873898

**Comment by Lofesa** [comment]
@westonruter 
Tested the v1.5.0-alpha-20191207T181223Z-c3e9208b in one site. It works. If I found some issue I will report here.
