### ISSUE TITLE
The attribute 'height' in tag 'amp-iframe' is set to the invalid value

### ISSUE THREAD

**Issue by anonymous-developer-786** [ampproject/amp-wp#4192]
I am facing this issue. Any help will be highly appreciated.
here's the screenshot of google AMP test https://www.screenpresso.com/=pwzqg

**Comment by westonruter** [comment]
The issue is this `iframe` in the [non-AMP page](https://duino4projects.com/making-sound-noise-machines-using-arduino/):

```html
<iframe width="100%" height="100%" src="//eboundservices.com/ads/video.php" frameborder="0" allowfullscreen="true" webkitallowfullscreen="true" mozallowfullscreen="true"></iframe>
```

However, when I load your AMP URL in the validator I see no validation error: https://validator.amp.dev/#url=https%3A%2F%2Fwww.anduril.band%2F%3Famp

In fact, now I see:

```html
<amp-iframe src="https://eboundservices.com/ads/video.php" allowfullscreen="" sandbox="allow-scripts allow-same-origin" height="400" width="768"></amp-iframe>
```

Nevertheless, the issue of `height=100%` being stripped was fixed recently via #3728. This is not yet released, but you can try a v1.5.0-alpha-20200128T224531Z-6021df7db pre-release build here: [amp.zip](https://github.com/ampproject/amp-wp/files/4130688/amp.zip)

This results in the above iframe being rendered as:

```html
<amp-iframe src="https://eboundservices.com/ads/video.php" frameborder="0" allowfullscreen="" layout="fill" sandbox="allow-scripts allow-same-origin"><span placeholder="" class="amp-wp-iframe-placeholder"></span><noscript><iframe width="100%" height="100%" src="https://eboundservices.com/ads/video.php" frameborder="0"></iframe></noscript></amp-iframe>
```
