### ISSUE TITLE
Pinterest share button does not pull any images

### ISSUE THREAD

**Issue by chvillanuevap** [ampproject/amp-wp#4195]
## Bug Description

I have enabled Jetpack sharing on my blog posts. You can see an example here: https://thepostmansknock.com/how-to-make-the-perfect-calligraphy-envelope/

When I click on the Facebook sharing button, the popup window displays the featured image from the post. However, the Pinterest button does not display an image, just the post title.

## Expected Behaviour

The expected behavior would be for the Pinterest button to pull up an image to share considering the visual nature of the social network.

## Steps to reproduce

1. Go to this link: https://thepostmansknock.com/how-to-make-the-perfect-calligraphy-envelope/
2. Click on the Pinterest sharing button under the post title and excerpt.
3. Notice that no images are pull up to share on the social network.

I'm not sure if this is an issue I should open with Jetpack or here. If I need to post it on Jetpack, please let me know! And thanks!

**Comment by westonruter** [comment]
Hi. Have you enabled rich pins on your site? There are setup instructions here: https://developers.pinterest.com/docs/rich-pins/overview/

It seems your Schema.org metadata is being generated by Yoast, so this may not be an issue with the AMP plugin.

**Comment by chvillanuevap** [comment]
I think I do. I mean the images are pulled up correctly is AMP is disabled.

**Comment by westonruter** [comment]
Can you switch to Transitional mode so that we can compare?

**Comment by chvillanuevap** [comment]
Sure. It's set up on my staging site:

https://thepostmanskck.staging.wpengine.com/a-foolproof-day-in-the-life-sketchbook-layout-formula/

**Comment by westonruter** [comment]
The metadata in the AMP and non-AMP pages seem to be the same.

Clicking the pinterest button in non-AMP opens a window at:

https://www.pinterest.com/pin/create/button/?url=https%3A%2F%2Fthepostmanskck.staging.wpengine.com%2Fa-foolproof-day-in-the-life-sketchbook-layout-formula%2F&media=https%3A%2F%2Fi2.wp.com%2Fthepostmanskck.staging.wpengine.com%2Fwp-content%2Fuploads%2F2020%2F01%2F1sketchbook_layout-18-of-18.jpg%3Ffit%3D1200%252C983%26ssl%3D1&description=A%20Foolproof%20%22Day%20in%20the%20Life%22%20Sketchbook%20Layout%20Formula

Wheras clicking the AMP share button opens:

https://www.pinterest.com/pin/create/button/?url=https%3A%2F%2Fthepostmanskck.staging.wpengine.com%2Fa-foolproof-day-in-the-life-sketchbook-layout-formula%2F&description=A%20Foolproof%20%22Day%20in%20the%20Life%22%20Sketchbook%20Layout%20Formula%20%E2%80%93%20The%20Postman%27s%20Knock

The URL opened for AMP is lacking `media=https%3A%2F%2Fi2.wp.com%2Fthepostmanskck.staging.wpengine.com%2Fwp-content%2Fuploads%2F2020%2F01%2F1sketchbook_layout-18-of-18.jpg%3Ffit%3D1200%252C983%26ssl%3D1`

I can also reproduce the issue by putting the following into https://playground.amp.dev:

```html
<amp-social-share width="35" height="35" type="pinterest" data-param-url="https://thepostmanskck.staging.wpengine.com/a-foolproof-day-in-the-life-sketchbook-layout-formula/"></amp-social-share>
```

Could it be because robots are blocked? I can't validate that URL with the Pinterest URL debugger either: https://developers.pinterest.com/tools/url-debugger/

I think if the image is not supplied in the URL (as the AMP component is not doing) then Pinterest probably tires to fetch the image from the site. But if robots are blocked, as [they are](https://thepostmanskck.staging.wpengine.com/robots.txt) for your site, then it fails to get the image.

That's my guess. In any case, I don't think there is any problem with the AMP plugin here. It seems either to be an issue with your robots blocking or it is an issue with the AMP component itself and an issue should be opened in the [amphtml repo](https://github.com/ampproject/amphtml/).

**Comment by chvillanuevap** [comment]
The robots are blocked because it is a staging site I think. The robots are not blocked on the [production site](https://thepostmansknock.com/robots.txt). 

I'll go ahead and open an issue with the amphtml repository. Thank you for your help!

**Comment by chvillanuevap** [comment]
Ok, just for future reference, the issue is with the Jetpack plugin. The function `render_sharing_html` in `jetpack/3rd-party/class.jetpack-amp-support.php` needs to have additional parameters for Pinterest:
```
$supported_services = array(
	...
        // added these parameters myself based on https://amp.dev/documentation/components/amp-social-share/#pre-configured-providers
	'pinterest' => array(
		'data-param-media' => $pinterest_thumb_url,
		'data-param-url' => get_permalink( $post->ID ),
		'data-param-description' => $post->post_title,
	),
	...
);
I opened an issue with them [here](https://github.com/Automattic/jetpack/issues/14542).
