### ISSUE TITLE
amp-iframe stripping resizable required div[overflow]

### ISSUE THREAD

**Issue by jritterbush** [ampproject/amp-wp#4288]
## Bug Description

I'm trying to use the `resizable` attribute on `amp-iframe` to dynamically resize the `amp-iframe` based on a `postMessage` sent from within the iframe to the parent page. Currently the sanitizer seems to be stripping out the `<div overflow></div>` which is required for this to work.

The `resizable` attribute is getting passed over to the `amp-iframe` but the required div is not.

**The code of the source iframe is:**

```html
<iframe src="https://jump.sproutsocial.com/l/638801/2020-02-05/396zv" title="Time for 2020: Social Media Trends and What To Do Now" height="500" width="350" layout="responsive" resizable sandbox="allow-scripts allow-same-origin allow-forms allow-top-navigation allow-popups" frameborder="0">
    <img
            src="https://media.sproutsocial.com/uploads/bg-transparent.gif"
            height="500"
            width="350"
            layout="intrinsic"
            placeholder/>
    <div overflow tabindex="0" role="button" aria-label="Show all">
        Show all
    </div>
</iframe>
```

**The output on the AMP version is:**

```html
<amp-iframe src="https://jump.sproutsocial.com/l/638801/2019-11-07/2wxmg" title="Time for 2020: Social Media Trends and What To Do Now" height="500" width="350" layout="responsive" resizable="" sandbox="allow-scripts allow-same-origin allow-forms allow-top-navigation allow-popups" frameborder="0">
	<span placeholder="" class="amp-wp-iframe-placeholder"></span>
	<noscript>
		<iframe src="https://jump.sproutsocial.com/l/638801/2019-11-07/2wxmg" title="Time for 2020: Social Media Trends and What To Do Now" height="500" width="350" resizable sandbox="allow-scripts allow-same-origin allow-forms allow-top-navigation allow-popups" frameborder="0">
			<amp-img src="https://media.sproutsocial.com/uploads/illustration-homepage-header@2x-2.png" height="500" width="350" layout="intrinsic" placeholder="" class="amp-wp-enforced-sizes"></amp-img>
			<div overflow role="button" tabindex="0">See all</div>
		</iframe>
	</noscript>
</amp-iframe>
```

I understand that a valid HTML5 iframe may not allow content inside it (https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe), but if that is the issue, is there an option to allow an iframe to be converted to an amp-iframe and still function with resizable?

## Expected Behaviour

The sanitized amp-iframe version of our iframe should still include the `<div overflow></div>` which is required by `amp-iframe[resizable]`. 

## Steps to reproduce

1. Go to the 2 versions of the same page with iframes:
    - Non-AMP version: https://john-test.stagely.sproutsocial.com/amp-iframe-test/
    - AMP version: https://john-test.stagely.sproutsocial.com/amp-iframe-test/?amp
2. View the source/inspect source in the AMP version
    - The following error appears in the AMP version's console: `Overflow element must be defined for resizable frames:`
    - The JS in the iframe is sending a resize event to the parent as well and follows the requirements in the AMP documentation: https://amp.dev/documentation/components/amp-iframe/#iframe-resizing

## Additional context

 - WordPress version: 5.3.2
 - Plugin version: 1.4.2
 - Gutenberg plugin version (if applicable): n/a (Classic Editor v1.5 plugin in place)
 - AMP plugin template mode: Transitional (all templates)
 - PHP version: 7.3
 - OS: ubuntu 16.04
 - Browser: n/a
 - Device: n/a

There was a similar issue posted about this here: https://github.com/ampproject/amp-wp/issues/635, but was closed. The conversation there seemed to be more about the attribute and not an answer to the div, but correct me if I'm wrong or overlooked something.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by westonruter** [comment]
Thanks for opening this. The existing behavior does seem strange and there should indeed be a better way to specify that an iframe will be resizable, what the overflow should be, and what the placeholder should be populated with. As it stands right now, the plugin is doing a workaround hack to populate an empty placeholder which is of no value other than to bypass an AMP requirement. 

https://github.com/ampproject/amp-wp/blob/a3aabc7c8115734a9c15a4f85a19d5117c892595/includes/sanitizers/class-amp-iframe-sanitizer.php#L313-L324

Ideally it should be populated with actual _placeholder_ content not an empty element.

Something also interesting I am noticing is that when you have child elements of `iframe` as in your source HTML, these nodes are completely absent in the DOM even though they are present in the underlying source. Actually, the node is there but the HTML parser (in both Chrome and Firefox at least) treats it as text:

> ![image](https://user-images.githubusercontent.com/134745/74553380-193f4480-4f0c-11ea-9a0c-d2c048adf8c8.png)

So children of `iframe` are similar to the children of `noscript`. Interesting. This makes sense because when `iframe` was first introduced, to be compatible with browsers which didn't support it, fallback content would need to be placed inside. If a browser supports `iframe` then the fallback content should indeed be ignored. It's similar for the newer `picture` element. (Aside: AMP also has such [fallbacks](https://amp.dev/documentation/guides-and-tutorials/develop/style_and_layout/placeholders/#fallbacks) and they are explicitly marked as such via the `fallback` attribute.)

That being the case, I don't see any reason to not include children of the `iframe` from a browser compatibility perspective. Adding semantic placeholder content as a child of the iframe may even improve SEO. The only downside is not passing HTML5 validation, if that is a concern.

**Comment by westonruter** [comment]
@jritterbush I believe I've addressed the issue in #4292. Please review/test.

**Comment by jritterbush** [comment]
This seems to have resolved it on my end. I updated my test site to use your updated plugin and I am now seeing the placeholder and overflow elements in the amp-iframe versions. Feel free to check it out here:

- https://john-test.stagely.sproutsocial.com/amp-iframe-test/
- https://john-test.stagely.sproutsocial.com/amp-iframe-test/?amp

I also lowered the initial height of the iframes to make sure the overflow button appeared on the amp version (the first form has no button in the original iframe, the second example has one provided by us).

You can ignore the incorrect height on the original iframe (probably need to tweak our code for that), but the amp version seems to be setting correctly as soon as you click the button or set focus on a form field.

**Comment by csossi** [comment]
@kienstra - can you do a dev QA check on this one?

**Comment by kienstra** [comment]
**Looks Good!**

Hi @csossi,
Sure! This looks good.

Given this in a Custom HTML block

```html
<iframe src="https://www.youtube.com/embed/QHnLmvDxGTY" width="560" height="315" sandbox="allow-scripts allow-same-origin allow-forms">
    <img
            src="https://media.sproutsocial.com/uploads/bg-transparent.gif"
            height="500"
            width="350"
            layout="intrinsic"
            placeholder/>
    <div overflow tabindex="0" role="button" aria-label="Show all">
        This is the overflow div
    </div>
</iframe>
```

...the AMP source is now:
```html
<amp-iframe src="https://www.youtube.com/embed/QHnLmvDxGTY" width="560" height="315" sandbox="allow-scripts allow-same-origin allow-forms" layout="intrinsic" class="amp-wp-enforced-sizes">
        <amp-anim src="https://media.sproutsocial.com/uploads/bg-transparent.gif" height="500" width="350" layout="intrinsic" placeholder="" class="amp-wp-enforced-sizes"><noscript><img src="https://media.sproutsocial.com/uploads/bg-transparent.gif" height="500" width="350" placeholder></noscript></amp-anim>
        <!-- This is now a direct child of <amp-iframe>, as expected -->
        <div overflow tabindex="0" role="button" aria-label="Show all">
                 This is the overflow div
        </div>
        <noscript>
                <iframe src="https://www.youtube.com/embed/QHnLmvDxGTY" width="560" height="315" sandbox="allow-scripts allow-same-origin allow-forms">
                </iframe>
        </noscript>
</amp-iframe>

```

Also, there's no validation error in the plugin or the Chrome extension.

**Comment by kienstra** [comment]
If it's alright, I moved this to 'Done.'
