### ISSUE TITLE
Stylesheets recap needs clarifications

### ISSUE THREAD

**Issue by schlessera** [ampproject/amp-wp#4294]
## Feature description

I know I'm late to the party now, but I wanted to keep track of a few UX improvements I'd like to suggest for the stylesheet recap in the validation screen.

- [x] The column "Minification" is technically not minification, but tree-shaking. This could use a "wp-pointer" help text.
- [x] The small character "B" that denotes bytes can easily be misread as the digit "8".
- [ ] The column name "Status" is ambiguous, and its contents is a checkmark. This could use a "wp-pointer" help text.
- [ ] Having a positive percentage number for minification will look as if the plugin is broken, so that will need an explanation somewhere.

![Image 2020-02-14 at 6 23 57 PM](https://user-images.githubusercontent.com/83631/74584395-1c046d00-4fd2-11ea-99d7-b9073bc9d0a9.png)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by westonruter** [comment]
> * The column "Minification" is technically not minification, but tree-shaking. 

Actually, it is minification. The reduction includes not only tree-shaking but also comment deletion and whitespace removal.

> This could use a "wp-pointer" help text.

cf. #1479

> * The small character "B" that denotes bytes can easily be misread as the digit "8".

Do you think the unit is implied and can be eliminated entirely?

> * Having a positive percentage number for minification will look as if the plugin is broken, so that will need an explanation somewhere.

There is an explanation in a tooltip when hovering over the `:root:not(#_)` seletor:

![image](https://user-images.githubusercontent.com/134745/74594217-6abd0180-4fe8-11ea-98c7-b6030b2250b6.png)

The text is: _Selector generated to increase specificity for important properties so that the CSS cascade is preserved. AMP does not allow important properties._

This should be made more obvious.
