### ISSUE TITLE
class-amp-story-templates uses term_exists(), which is uncached

### ISSUE THREAD

**Issue by paulschreiber** [ampproject/amp-wp#4337]
## Bug Description
class-amp-story-templates uses `term_exists()`, which is uncached. if you used `get_term()`, this would improve performance.

https://github.com/ampproject/amp-wp/blob/develop/includes/admin/class-amp-story-templates.php#L290

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by pierlon** [comment]
Hi @paulschreiber,

The Stories experience has been deprecated since [v1.4.3](https://github.com/ampproject/amp-wp/releases/tag/1.4.3) and is no longer being actively developed here. The feature is currently being removed (see https://github.com/ampproject/amp-wp/issues/4203) and will be available as a separate plugin soon.

**Comment by paulschreiber** [comment]
@pierlon Can this performance improvement be incorporated in to the new plugin?
