### ISSUE TITLE
Add PHP static analysis via PHPStan

### ISSUE THREAD

**Issue by westonruter** [ampproject/amp-wp#4342]
## Feature description

I've only recently become aware of PHPStan, but it seems like it could help with catching subtle bugs. See https://github.com/google/web-stories-wp/pull/334 and https://github.com/GoogleChromeLabs/pwa-wp/issues/243.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by schlessera** [comment]
Yes, PHPStan is great. It will only make sense with clean and strongly typed code of course, but we're having more and more of this, so we'll probably start reaping benefits from it by now.

I've been using it with a WordPress stubs file for WP plugins: https://github.com/mwpd/basic-scaffold/blob/master/phpstan.neon.dist

**Comment by schlessera** [comment]
This will need a bit of a work-around, as PHP-Stan requires PHP 7.1.

**Comment by szepeviktor** [comment]
There is a [WordPress Extension](https://packagist.org/packages/szepeviktor/phpstan-wordpress) for PHPStan.

**Comment by swissspidy** [comment]
Thanks for opening this, @westonruter! I was about to do it after my experience with the Web Stories plugin but you beat me to it. 🙂 

The extension @szepeviktor maintains is indeed super helpful to get off the ground quickly.

@schlessera In the Web Stories plugin we run PHPStan only on 7.1 in a separate job, installing it via `composer require --no-interaction --dev szepeviktor/phpstan-wordpress --ignore-platform-reqs`. That means you cannot easily use it locally though, but it works fine for us so far. LMK if you come up with a better solution.

**Comment by schlessera** [comment]
I've done a bit of a more manual approach, as @szepeviktor's extension requires PHP 7.1+.

PHPStan is downloaded as a Phar instead, and the needed stubs are provided in the `tests/` folder (some copied from the above extension, some written as needed).

This now works so that you can run `composer analyse` on your local installation as well, without any extra effort. We could also add this to a precommit then.

**Comment by swissspidy** [comment]
Pretty cool! I also like how you snuck autoloading through Composer in there 🎉

**Comment by schlessera** [comment]
Composer was already a requirement in the plugin because of the CSS Parser library.

**Comment by swissspidy** [comment]
But we still had `AMP_Autoloader` 🙂

**Comment by szepeviktor** [comment]
> as @szepeviktor's extension requires PHP 7.1+.

It is PHPStan's requirement :)

**Comment by schlessera** [comment]
To run it, yes. But the codebase that you want to check does not need to be PHP 7.1+. The plugin is currently at PHP 5.6+, and it makes perfect sense to check the code with PHPStan. But we can't install it directly via Composer because if its requirement. That's why I'm downloading it as a Phar instead.

**Comment by schlessera** [comment]
> But we still had AMP_Autoloader

Yes, presumably because it is "extensible" for plugins wanting to extend the AMP support. However, this was broken from 2017 onwards and never fixed.

So all it does is provide a class map we need to maintain manually and that is less optimized than the one that Composer generates.
