### ISSUE TITLE
Webp Support

### ISSUE THREAD

**Issue by rsmith4321** [ampproject/amp-wp#4470]
## Feature description

Would it be possible to provide webp support with a fallback image as documented here? This would only work if webp images were already generated but there are many plugins that take care of that. https://amp.dev/documentation/components/amp-img/#example:-specifying-a-fallback-image. 

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by westonruter** [comment]
We looked at this a bit in #1316 to try adding support for the `picture` element.

It would be possible, yes, but it would be tricky. Consider stylesheets that currently target an `img` with some given class `foo`. In AMP the `img` will get converted to an `amp-img` with that same class. But if there is a fallback `amp-img` inside, will it also have that same class? If there is a style rule where `.foo { border: solid 1px black; }` would this not result in browsers not supporting WebP ending up seeing a border that is 2px wide?

It would be preferable for the WebP images to actually be served at the server level, rather than client-side. This is the recommendation from the AMP team as well: https://github.com/ampproject/amp-wp/pull/3082#issuecomment-525521319.

By all means, you can write your HTML to generate `amp-img` in this way, rather than outputting `img` which gets converted to `amp-img`. You could also create a new sanitizer which wraps `amp-img` elements when there is a WebP version available. But it would be up to you to ensure the CSS is also written appropriately.

Here is a proof of concept plugin which you can use to wrap `amp-img` elements with a WebP version: https://gist.github.com/westonruter/332abdb2adefc6b204ad6fcc1beecedf

**Comment by westonruter** [comment]
Update: This is an anti-pattern which should not be used! See https://github.com/ampproject/amphtml/issues/21912#issuecomment-617995565

The amp-img docs that used it as an example has been removed: https://github.com/ampproject/amphtml/pull/28655
