### ISSUE TITLE
Implement support for Mobile Redirection

### ISSUE THREAD

**Issue by amedina** [ampproject/amp-wp#4479]
Implement support for automatically serving mobile visitors to the AMP version, or else redirect them to the AMP version. There would still have to be a way for the user to exit the AMP version. 

For prototype, see [Mobile Redirection plugin](https://gist.github.com/westonruter/787c875e5ab724808c26014153e46ec6). Nevertheless, this plugin will not work in all hosting environments and server stacks. An alternative approach for how to handle mobile redirection is to use [JS-based redirection](https://gist.github.com/westonruter/5f4f27ed3bdd676e3f08524b9bab8bb4), redirecting mobile visitors of the desktop site over to the AMP version when it is available.

Related: #2204

**Comment by westonruter** [comment]
For a discussion about mobile redirection, see comments after https://github.com/ampproject/amp-wp/issues/2044#issuecomment-574941475.

**Comment by westonruter** [comment]
Additional requirements:

1. Add a section the admin screen which has a checkbox enable mobile redirection. This section will only be displayed when the site is in Transitional or Reader mode.
2. When a user is automatically redirected to the AMP version (or lands on the AMP version), there needs to be a way to navigate back to the non-AMP version. This can be implemented by default via a section output at `wp_footer` (or `amp_post_template_footer`) which has a centered link inside of it saying something like “Leave mobile version”; this would text would apply both to Reader mode and Transitional mode, whereas presently the Reader mode has “Exit Reader Mode”. This would be used instead the Exit Reader Mode link currently shown in the header in Reader mode, but which has problematic placement there (see #4573).
3. The “Display link to exit reader mode?” checkbox in the Customizer can remain but be rebranded to “Display link to exit mobile version”. When checked, there could also be a text field allowing the user to customize what the link text contains. In classic AMP Reader mode, there is already an AMP panel that has this setting in it; non-classic Reader mode and Transitional mode, a new Customizer section for “AMP” settings would be needed and in this section this same checkbox control can be added.
4. When the user manually navigates to the non-AMP version, auto-redirection needs to be turned off. This likely involves adding a query var (like `?noamp=1`) when linking from AMP to non-AMP, and when loading the non-AMP page this query var must prevent redirection while also setting a flag in `sessionStorage` to prevent redirecting the from non-AMP to AMP at the next page navigation.
5. Automatically add `?noamp=1` to any intra-site link URLs that AMP-to-AMP linking skips, either due to filter or the `noamphtml` link relation. In the same way, AMP-to-AMP linking should skip any URLs that have this `?noamp=1` query parameter present.
5. If the user is redirected from the AMP version to the non-AMP version due to there being kept invalid markup, redirection back to the AMP version must not be done. This may require adding a new query var, which at present is only added when the user is logged in:

https://github.com/ampproject/amp-wp/blob/710f0f70b9a7679cb69232746cdd0f244bb4af5f/includes/class-amp-theme-support.php#L2116-L2119

**Comment by westonruter** [comment]
In addition to point 2 above:

7. When a mobile user manually navigates to the `noamp` version, there should be a link displayed for mobile visitors to resume navigating the mobile version of the site (the AMP version), where available. For context, see how GitHub offers the link to the desktop version (including a means of making it permanent, which I don't think we necessarily need), and then how it offers mobile visitors to return to the mobile version:

Mobile Version | Desktop Version
---------------|-----------------
![Screenshot_20200525-204828](https://user-images.githubusercontent.com/134745/82865446-9438d380-9edb-11ea-8a30-2353d1db287f.png) | ![Screenshot_20200525-204813](https://user-images.githubusercontent.com/134745/82865464-a0bd2c00-9edb-11ea-8b36-b365e39cc212.png)

When mobile visitor is seeing the desktop version, the mobile link is shown in the header. When mobile visitor is on the mobile version, the desktop link is shown in the footer. For practical reasons, in WordPress I think we'll need to consistently show these links at `wp_footer`, at least for automatic injection. If a site owner wants to manually place the link in a menu or in some other template partial, they can do so. For Reader mode, this means the links between desktop and mobile versions both need preferences for whether to show the link automatically at `wp_footer` (and `amp_post_template_footer`).

**Comment by westonruter** [comment]
Here's how this could look:

Mobile Twenty Twenty | Mobile Classic | Desktop Twenty Twenty
---------------|--------|---------
![image](https://user-images.githubusercontent.com/134745/82866813-7882fc80-9ede-11ea-8976-2a9cc47f4f62.png) | ![image](https://user-images.githubusercontent.com/134745/82866687-42457d00-9ede-11ea-938b-7c76a58d1f73.png) | ![image](https://user-images.githubusercontent.com/134745/82868778-10361a00-9ee2-11ea-9b93-fae6f179f0a9.png)

The styling of the link is adapting what GitHub is using, which is pretty good in terms of being something color-scheme neutral.

The leave link here is not sticky to the bottom of the viewport. It would only be shown if the user scrolls to the bottom of the page. In the same way, when a mobile user navigates to the non-AMP version, the same link can be shown in the footer to allow the user to return to the mobile version. This links should only be shown if the user is on a mobile device (using the same logic as redirecting the user to the AMP version in the first place). 

I've updated the prototype mini plugin to implement the link on desktop: https://gist.github.com/westonruter/5f4f27ed3bdd676e3f08524b9bab8bb4

**Comment by westonruter** [comment]
An interesting alternative approach has been taken by @selul as [mentioned](https://wordpress.org/support/topic/great-perfomance/#post-12942287) on a the forums:

> Yes, on a few sites we use directly the standard mode, providing AMP first experience for both desktop and mobile.
>
> But for some, we use the amp first experience only on mobile, using a small code tweak, which proven to be helpful:
> 
> ```php
> add_filter( 'option_amp-options', function ( $value ) {
> 
> 	if ( wp_is_mobile() ) {
> 		$value['theme_support'] = 'standard';
> 	}
> 
> 	return $value;
> }, 99999 );
> ```
>
> Because the hosting does the page caching per device ( mobile/tablet/desktop ) the wp_is_mobile is working fine in this context.

This is an interesting approach. If a site opts-in to PHP-based mobile redirection, should we actually switch to serving the AMP version instead of redirecting to the AMP version?

I followed up on the forum as follows:

> Serving the AMP version as the mobile version is tricky especially given various server stacks. You mentioned your hosting already varies caches by device, so it's not a problem for you. 
> 
> But in general, consider a site that has a caching layer that doesn't properly segment by user agent in the same way that `wp_is_mobile()` does. If such a site used your approach, then it could result in a desktop user getting served the AMP version, or a mobile user getting the non-AMP version. For this reason, the AMP plugin by default is going to use JavaScript to redirect mobile users visiting visiting the canonical URL to rather go to the AMP version. For sites that have caching layers which support it, we'll also support a filter to opt-in to doing PHP-based redirects instead, which will be much faster of course. 
> 
> I briefly considered your approach of actually serving different versions of the site on the same URL based on the user agent, but I settled on using redirects instead. I suppose in practice this is no different than doing a redirection. But there could be some unintended side effects with how you've implemented it… 
> 
> Consider Googlebot doing mobile-first indexing. When it lands on your site, it will be treated as a mobile visitor and will get served AMP in standard mode. In this mode, there will not be any `amphtml` link to advertise a separate AMP version, since as far as it knows the AMP version is the canonical version. I don't suppose that would be a problem in and of itself. 
> 
> But let's say Googlebot uses desktop-first indexing, and indexes a page on your site. It will have the `amphtml` link since it's not standard mode; it will then at some point later index the AMP version. The Googlebot which indexes AMP pages will use the mobile user agent, as far as I understand. So when it tries doing so it will end up getting redirected from `/?amp` to `/` since the plugin thinks it is actually in Standard mode. This could end up making Googlebot very confused and your pages may not get indexed as AMP and thus they won't be able to be served with the AMP badge and served with prerendering.
> 
> There is also special guidance from Google on how to make sure that Googlebot will know that different versions of the site depend on the `User-Agent` which I believe you'll need to include in your snippet above (if your host isn't doing it already): https://developers.google.com/search/mobile-sites/mobile-seo/dynamic-serving

**Comment by pierlon** [comment]
> This is an interesting approach. If a site opts-in to PHP-based mobile redirection, should we actually switch to serving the AMP version instead of redirecting to the AMP version?

I think that's a highly opinionated approach that is best left up to the user to implement. The issue here is that the canonical URL could be AMP or non-AMP, depending on the user-agent; some people would be for it, some won't. Our current implementation of mobile redirection would serve as a solution for the majority of users, I believe.

---

> So when it tries doing so it will end up getting redirected from /?amp to /?amp since the plugin thinks it is actually in Standard mode.

@westonruter Do you mean redirecting from `/?amp` to remove the AMP query parameter?

**Comment by westonruter** [comment]
> Do you mean redirecting from `/?amp` to remove the AMP query parameter?

Yes, that's what I meant. Corrected.

**Comment by westonruter** [comment]
Regardless, we'll need to make sure that the response header `Vary: User-Agent` added to #4796 when `amp_redirect_via_js` is filtered to be `false`, as redirects can be cached.

But what would the practical difference be (from a user perspective) between redirection and dynamic serving ? If a mobile user gets redirected from `/` to `/?amp`? If the user tries going to `/` manually they'll still get redirected. In contrast, if dynamic serving is used, then a mobile user going to `/` wouldn't need to get redirected to `/?amp` in the first place. The “exit mobile version” link would just need to append `?noamp` to the current URL to override the content negotiation logic. 

My main concern about this approach has to to with _discovery_ for crawlers. In this scheme, there would not be an AMP-specific URL for the site, so there would be no `amphtml` version to link to. This being the case, there would be no guaranteed way of accessing the AMP version just by just the URL (meaning the AMP Cache . All this means that I am pretty sure this would prevent AMP pages from such a site from being served by Google search or other AMP consumers.

So I'm inclined to agree with you that this would not be the ideal approach.

**Comment by westonruter** [comment]
Nevertheless, I wonder if redirecting mobile users to the AMP version will cause problems for crawlers who are attempting to access the `canonical` URL?

**Comment by westonruter** [comment]
Aside: When the AMP Cache requests an AMP page, the `User-Agent` is currently:

```
Mozilla/5.0 (Linux; Android 6.0.1; Nexus 5X Build/MMB29P) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.92 Mobile Safari/537.36 (compatible; Google-AMPHTML)
```

**Comment by selul** [comment]
@westonruter Thanks for your thorough feedback! 
> This being the case, there would be no guaranteed way of accessing the AMP version just by just the URL (meaning the AMP Cache . All this means that I am pretty sure this would prevent AMP pages from such a site from being served by Google search or other AMP consumers.

I'm following up on this, not sure if this helps,  for themeisle.com/blog we have mobile-first indexing and use this approach of serving AMP to the mobile user on `wp_is_mobile` and Google manage to serve the page as AMP.
 
For codeinwp.com previously we have used the same mechanism but we have desktop-first indexing for this site and Google still manages to serve the AMP version correctly.

**Comment by westonruter** [comment]
The three approaches to supporting mobile devices are documented in the [Choose a mobile configuration](https://developers.google.com/search/mobile-sites/mobile-seo) guide:

1. [Responsive Web Design](https://developers.google.com/search/mobile-sites/mobile-seo/responsive-design), which corresponds to the Standard mode.
2. [Dynamic Serving](https://developers.google.com/search/mobile-sites/mobile-seo/dynamic-serving), which _mostly_ corresponds to @selul's approach. 
3. [Separate URLs](https://developers.google.com/search/mobile-sites/mobile-seo/separate-urls), which corresponds to what we've proposed here, including both [HTTP redirects and JS redirects](https://developers.google.com/search/mobile-sites/mobile-seo/separate-urls#supported-redirection-techniques).

I'm making some inquires about what any further implications to weight 2 & 3.

In the Separate URLs doc, in [Annotations in the HTML](https://developers.google.com/search/mobile-sites/mobile-seo/separate-urls#annotation-in-the-html) there is mention of needing a `link[rel=alternate]`. I'm finding out if this is needed in addition to the `amphtml` link. For example, on the canonical page there may be need for:

```html
<link rel="amphtml" href="https://example.com/?amp=1">
<link rel="alternate" media="only screen and (max-width: 640px)" href="https://example.com/?amp=1">
```

This seems pretty straightforward. It is less clear in the case of the hybrid approach of @selul where both separate URLs (for AMP discovery) _and_ dynamic serving (for mobile on origin) are being used. Nevertheless, Google Search seems to handle it just fine on themeisle.com, so there's that. Nevertheless, I'm uncertain whether non-Google crawlers will handle it as well. 

When I do a search for a post on Themeisle, I can indeed see:

![image](https://user-images.githubusercontent.com/134745/83960751-40b27800-a841-11ea-82c0-82d2918aea53.png)

Tapping that takes me to the Google AMP viewer (access with mobile user agent): https://www.google.com/amp/s/themeisle.com/blog/optimize-your-wordpress-title-and-tagline/

The URL indicates the site is in Standard mode as far as the Search index and AMP Cache is concerned. I can access that canonical URL via the AMP Cache: https://themeisle-com.cdn.ampproject.org/c/s/themeisle.com/blog/optimize-your-wordpress-title-and-tagline/

Nevertheless, if I access the canonical URL with a desktop user agent, I get a non-AMP page at https://themeisle.com/blog/optimize-your-wordpress-title-and-tagline/

This makes sense because it is no longer in Standard mode. Nevertheless, this page contains an `amphtml` link since it is in Transitional mode:

```html
<link rel="amphtml" href="https://themeisle.com/blog/optimize-your-wordpress-title-and-tagline/?amp">
```

If I try accessing the AMP version in a desktop browser, for example via the AMP Validator extension:

![image](https://user-images.githubusercontent.com/134745/83960805-d77f3480-a841-11ea-8306-1d2e506d050d.png)

I am successfully taken to https://themeisle.com/blog/optimize-your-wordpress-title-and-tagline/?amp

If I try accessing that URL with a mobile user agent, I am then redirected to the canonical URL (without `?amp`). That seems OK.

I keep trying to identify some flaw in the hybrid approach since something just doesn't seem right about it. I can't put my finger on it. Maybe I'm just wrong and it's perfectly OK. Maybe the part that feels the most uneasy for me is redirecting a mobile user who access the separate AMP URL version back to the canonical URL for dynamically serving AMP. But I can't say it's wrong.

What's certain, however, is that the AMP plugin needs to default to JS-based redirection for maximal compatibility across server environments, as indicated in the Google Search on [JavaScript redirects](https://developers.google.com/search/mobile-sites/mobile-seo/separate-urls#javascript-redirects):

<blockquote><p>If HTTP redirection is difficult to implement, you can use JavaScript to
redirect users to the URLs pointed to by the <code translate="no" dir="ltr">rel="alternate"</code>
tag. If you choose to use this technique, be aware of the latency caused
by the client side of redirection due to the need to first download the page,
then parse and execute the JavaScript before triggering the redirect.</p>
<p>There are many approaches to implementing a JavaScript-based redirect. For
example, you can use JavaScript to execute the media queries your site already
uses in the link annotations on the page using the <code translate="no" dir="ltr">matchMedia()</code> JavaScript
function.</p></blockquote>

This being the case, using “Separate URLs” as opposed to “Dynamic Serving” probably makes more sense to support in the AMP plugin since it is minimal code to support both JS and HTTP redirects. But would it be that much more code to support Dynamic Serving as opposed to HTTP redirects?

@selul I do think it is important that you make sure you send the `Vary: User-Agent` response header, as the [Dynamic Serving](https://developers.google.com/search/mobile-sites/mobile-seo/dynamic-serving) docs indicate.

**Comment by westonruter** [comment]
OK, after inquiring, the approach you're taking is legitimate. However, there is something important to be aware of. In particular, since you have mobile-first indexing, Googlebot will only ever see that you have an AMP version. This means that if you have content that is unique to the desktop version of your site, then it won't get indexed. Since you are in Transitional mode and the AMP and non-AMP versions are almost identical, then this should not be a problem for you. However, for other sites this may indeed be a problem. In particular, for sites in Reader mode which have a different theme (and no sidebar), or when heavily-modified templates are being used for AMP pages in transitional mode, then the lack of having the non-AMP version in the index could negatively impact the index for a site. For this reason, it does seem preferable to go ahead with implementing redirection as the method for serving the AMP version as the mobile version in the AMP plugin. You're free to leave that redirection capability off in your site and use the approach you are taking.

**Comment by amedina** [comment]
QA Passed.
