### ISSUE TITLE
Placeholder for iframes

### ISSUE THREAD

**Issue by bribeiro** [ampproject/amp-wp#783]
Under the assumption that it's desirable to make possible the use of iFrames anywhere on the page, and considering the documentation where it says `An amp-iframe may not appear close to the top of the document (except for iframes that use placeholder as described below). The iFrame must be either 600 px away from the top or not within the first 75% of the viewport when scrolled to the top, whichever is smaller.` I believe the method `build_placeholder` inside the file `class-amp-iframe-sanitizer.php` should create a tag `amp-img` instead of `div`, that way you can validate your page if, for one reason or another, it needs an iFrame at the very top of the page.

Thoughts?

**Comment by danielcardoso5** [comment]
I also have an issue with amp-iframes. The amp-iframe specification refers to using an amp-img inside an iframe to behave as a placeholder when the amp-iframe is loading. This is necessary to display amp-iframes on top of the document. Also, setting a <div overflow></div> is not possible using this plugin. This is also in the specification and allows for the user to expand the iframe if it's on the top of the document. Please check the "Iframe Resizing" part in the docs here: https://github.com/ampproject/amphtml/blob/master/extensions/amp-iframe/amp-iframe.md.

Would like to seed this addressed since this is breaking some embed codes I'm using.

**Comment by bribeiro** [comment]
I just sent a PR; I hope it helps.
https://github.com/Automattic/amp-wp/pull/790

**Comment by westonruter** [comment]
Custom placeholders for iframes now via #4292.
