### ISSUE TITLE
Implement REST API endpoints for managing settings

### ISSUE THREAD

**Issue by bhubbard** [ampproject/amp-wp#965]
I would love to see this plugin support the WordPress Rest API. Here are the general endpoints I could imagine.

```
/settings
    /cpt -- Enable/disable AMP post type(s) support
/design
   /Header Text Color
   /Header Background & Link Color
   /Color Scheme
```

**Comment by westonruter** [comment]
The design settings I don't think will be implemented since they are very much tied the post templates currently in the plugin. We're going to be moving away from this built-in theme in favor of pushing for themes that either support AMP directly or which are enabled for AMP by the plugin. As such, it should be core that exposes the design settings in the same way that it should expose Customizer options for any theme. So that should be a core issue.

For the AMP settings, I can see endpoints being useful potentially for the supported post types and analytics.

**Comment by westonruter** [comment]
The settings for the Reader mode templates I think are relatively unimportant, but the REST API endpoints _are_ important for revamping the settings screens to be more responsive. In general this is closely related to revamping the compatibility tool where the screens for the validated URLs and validation errors need to be re-developed using React to eliminate the poor UX of page reloads (see #2316). The same should be done for the general AMP settings screen, including endpoints for:

* Changing the mode.
* Changing the enabled experiences (website, stories).
* Selecting which templates are served as AMP
* etc

Also related is #2069 where changing a mode should not re-validation to happen synchronously.

**Comment by westonruter** [comment]
The same settings should also be exposed via WP-CLI: #1815.

**Comment by westonruter** [comment]
This is being implemented now by @johnwatkins0, although not specifically the Customizer settings. See #4827.
